/* Optional browser tests: install Playwright separately or set DEVKIT_PLAYWRIGHT. */
const {chromium}=require(process.env.DEVKIT_PLAYWRIGHT||'playwright');
const assert=require('node:assert/strict'),path=require('node:path'),{pathToFileURL}=require('node:url');
(async()=>{const browser=await chromium.launch({headless:true,...(process.env.DEVKIT_CHROME?{executablePath:process.env.DEVKIT_CHROME}:{})});try{
 const context=await browser.newContext({viewport:{width:1500,height:1050},acceptDownloads:true});const page=await context.newPage(),errors=[],network=[];page.on('pageerror',e=>errors.push(e.message));await page.route(/^https?:/,route=>{network.push(route.request().url());return route.abort();});const root=path.resolve(__dirname,'..');await page.goto(pathToFileURL(path.join(root,'index.html')).href);await page.waitForFunction(()=>typeof ddOpen==='function');
 await page.evaluate(()=>dkHome('bash'));await page.locator('[data-deep="bash"]').click();assert.equal(await page.locator('#dd-copy').isDisabled(),false);await page.getByLabel('Value',{exact:true}).first().fill('New value with $dollar and quotes');assert((await page.locator('#dd-preview').inputValue()).includes('New value'));
 // Add a repeated nested step with the contextual controls.
 const then=page.locator('.dd-lane[data-slot="then"]');await then.locator(':scope > .dd-add select').selectOption('print');await then.locator(':scope > .dd-add button').click();assert.equal(await then.locator(':scope > .dd-node').count(),2);
 const first=await page.evaluate(()=>ddState.blocks[1].slots.then[0].id),parent=await page.evaluate(()=>ddState.blocks[1].id);
 // Actual pointer drag into an empty sibling branch.
 const handle=page.locator('[data-node="'+first+'"] > .dd-node-head .dk-grip');const target=page.locator('.dd-lane[data-slot="else"] > .dd-lane-title');await target.scrollIntoViewIfNeeded();await handle.scrollIntoViewIfNeeded();const a=await handle.boundingBox(),b=await target.boundingBox();await page.mouse.move(a.x+a.width/2,a.y+a.height/2);await page.mouse.down();await page.mouse.move(b.x+b.width/2,b.y+b.height/2,{steps:20});await page.mouse.up();assert.equal(await page.evaluate(()=>ddState.blocks[1].slots.else.length),1);
 assert((await page.locator('#dd-preview').inputValue()).includes('\nelse\n'));await page.locator('#dd-undo').click();assert.equal(await page.evaluate(()=>ddState.blocks[1].slots.else.length),0);await page.locator('#dd-redo').click();assert.equal(await page.evaluate(()=>ddState.blocks[1].slots.else.length),1);
 assert.equal(await page.evaluate(({parent})=>ddMove(parent,parent,'then',0),{parent}),false);
 await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{value:{writeText:async text=>window.deepCopied=text},configurable:true}));await page.locator('#dd-copy').click();assert.equal(await page.evaluate(()=>window.deepCopied),await page.locator('#dd-preview').inputValue());const download=page.waitForEvent('download');await page.locator('#dd-download').click();assert.equal((await download).suggestedFilename(),'script.sh');
 await page.reload();await page.evaluate(()=>ddOpen('bash','bash'));assert((await page.locator('#dd-preview').inputValue()).includes('New value'));assert.equal(await page.evaluate(()=>ddState.blocks[1].slots.else.length),1);
 // Every editor renders; native field validation blocks invalid exports.
 for(const id of ['powershell','python','terraform','sql','dockerfile','yaml','json']){await page.evaluate(id=>ddOpen(id,id==='dockerfile'?'docker':id==='yaml'||id==='json'?'linux':id),id);assert.equal(await page.locator('#dd-copy').isDisabled(),false,id);}
 await page.getByLabel('Choose file to customize').setInputFiles({name:'custom.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({text:'a\nb',enabled:false,nested:[{port:80}]}))});await page.waitForFunction(()=>ddState.filename==='custom.json');assert.equal(await page.evaluate(()=>JSON.parse(ddOutput().text).nested[0].port),80);
 await page.getByLabel('Numeric value',{exact:true}).fill('oops');assert(await page.locator('#dd-copy').isDisabled());await page.getByLabel('Numeric value',{exact:true}).fill('443');assert.equal(await page.evaluate(()=>JSON.parse(ddOutput().text).nested[0].port),443);
 await page.evaluate(()=>ddOpen('yaml','linux'));await page.getByLabel('Choose file to customize').setInputFiles({name:'cycle.yml',mimeType:'text/yaml',buffer:Buffer.from('cycle: &a [*a]')});await page.waitForFunction(()=>document.querySelector('.df-zone [role=status]').textContent.includes('Cyclic'));
 await page.evaluate(()=>{const s=ddSeedFromRecipe('docker:compose');ddOpen(s.profile,'docker',s.nodes,s.filename,'docker:compose');});const service=page.locator('.dd-node').filter({has:page.locator(':scope > .dd-node-head .dd-node-title', {hasText:'Object / mapping · web'})});assert(await page.getByRole('button',{name:'+ healthcheck',exact:true}).count());await page.getByRole('button',{name:'+ healthcheck',exact:true}).click();assert.equal(await page.evaluate(()=>jsyaml.load(ddOutput().text).services.web.healthcheck.retries),3);
 if(process.env.DEVKIT_SCREENSHOTS)await page.screenshot({path:path.join(process.env.DEVKIT_SCREENSHOTS,'deep-desktop.png')});
 const backup=await page.evaluate(()=>dkBackup());assert(backup.data['devkit:workbench:v1'].includes('deep:'));assert(await page.evaluate(data=>!!dkValidateBackup(data),backup));
 await page.setViewportSize({width:390,height:844});await page.evaluate(()=>ddOpen('bash','bash'));await page.getByRole('button',{name:'Preview',exact:true}).click();assert(await page.locator('#dd-preview').isVisible());if(process.env.DEVKIT_SCREENSHOTS)await page.screenshot({path:path.join(process.env.DEVKIT_SCREENSHOTS,'deep-mobile.png')});
 await page.setViewportSize({width:1500,height:1050});await page.goto(pathToFileURL(path.join(root,'dist/devkit.html')).href);await page.evaluate(()=>ddOpen('terraform','terraform'));assert(!(await page.locator('#dd-copy').isDisabled()));assert.deepEqual(errors,[]);assert.deepEqual(network,[]);console.log('PASS: offline folder + bundle, recursive editing, pointer drag, undo/redo, draft recovery, copy/download, imports, suggestions and mobile preview.');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
