const {chromium}=require(process.env.DEVKIT_PLAYWRIGHT||'playwright'),assert=require('node:assert/strict'),path=require('node:path'),{pathToFileURL}=require('node:url');
(async()=>{const browser=await chromium.launch({headless:true,...(process.env.DEVKIT_CHROME?{executablePath:process.env.DEVKIT_CHROME}:{})});try{
 const page=await browser.newPage({viewport:{width:1500,height:1000}}),errors=[],network=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url()))network.push(r.url());});
 for(const entry of ['index.html','dist/devkit.html']){
 await page.goto(pathToFileURL(path.resolve(__dirname,'..',entry)).href);if(!await page.locator('.nav-sub-item').filter({hasText:'GitHub Actions'}).isVisible())await page.locator('.nav-toggle').filter({hasText:'CI/CD'}).click();await page.locator('.nav-sub-item').filter({hasText:'GitHub Actions'}).click();await page.getByRole('button',{name:'Build GitHub Actions →',exact:true}).last().click();await page.getByRole('button',{name:'Load starter',exact:true}).click();assert.equal(await page.locator('#dd-copy').isDisabled(),false);
 await page.getByLabel('Workflow name',{exact:true}).fill('My pipeline');await page.waitForTimeout(150);assert((await page.locator('#dd-preview').inputValue()).includes('My pipeline'));assert.equal(await page.getByLabel('Workflow name',{exact:true}).evaluate(el=>document.activeElement===el),true,'delayed editor focus stole the active block field');assert.equal(await page.evaluate(()=>dkDrafts[ddState.id].blocks[0].values.name),'My pipeline','edited workflow was not saved');
 await page.getByRole('button',{name:'← Workbench',exact:true}).click();assert.equal(await page.locator('#dk-dialog').getByRole('button',{name:/^Build .* →$/}).count(),3);await page.getByRole('button',{name:'Build GitLab CI →',exact:true}).click();await page.getByRole('button',{name:'Load starter',exact:true}).click();assert.equal(await page.getByLabel('Output filename').inputValue(),'.gitlab-ci.yml');assert.equal(await page.locator('#dd-copy').isDisabled(),false);
 await page.getByLabel('Job name',{exact:true}).fill('lint');await page.waitForFunction(()=>document.getElementById('dd-preview').value.includes('lint:'));assert(JSON.stringify(await page.evaluate(()=>dkDrafts[ddState.id])).includes('"name":"lint"'),'edited GitLab job was not saved');const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Download file',exact:true}).click();assert(['.gitlab-ci.yml','gitlab-ci.yml'].includes((await downloadPromise).suggestedFilename()));
 await page.getByRole('button',{name:'← Workbench',exact:true}).click();await page.getByRole('button',{name:'Build Jenkins →',exact:true}).click();await page.getByRole('button',{name:'Load starter',exact:true}).click();assert.equal(await page.getByLabel('Output filename').inputValue(),'Jenkinsfile');assert.equal(await page.locator('#dd-copy').isDisabled(),false);
 await page.getByRole('button',{name:'Move Sequential stage up',exact:true}).nth(1).click();let source=await page.locator('#dd-preview').inputValue();assert(source.indexOf("stage('Test')")<source.indexOf("stage('Checkout')"));await page.getByRole('button',{name:'Undo',exact:true}).click();source=await page.locator('#dd-preview').inputValue();assert(source.indexOf("stage('Checkout')")<source.indexOf("stage('Test')"));
 await page.getByRole('button',{name:'← Workbench',exact:true}).click();await page.getByRole('button',{name:'Build GitHub Actions →',exact:true}).last().click();assert.equal(await page.getByLabel('Workflow name',{exact:true}).inputValue(),'My pipeline');await page.getByRole('button',{name:'Close ✕',exact:true}).click();await page.reload();assert.equal(await page.evaluate(()=>state.activeSection),'github-actions');
 }
 await page.evaluate(()=>dkHome('cicd'));if(process.env.DEVKIT_SCREENSHOTS)await page.screenshot({path:path.join(process.env.DEVKIT_SCREENSHOTS,'cicd-platforms.png')});await page.getByRole('button',{name:'Build GitHub Actions →',exact:true}).last().click();if(process.env.DEVKIT_SCREENSHOTS)await page.screenshot({path:path.join(process.env.DEVKIT_SCREENSHOTS,'cicd-editor.png')});
 await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Preview',exact:true}).click();await page.waitForFunction(()=>[...document.querySelectorAll('.CodeMirror')].some(x=>x.getClientRects().length));assert(await page.locator('.CodeMirror:visible').isVisible());assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));assert.deepEqual(errors,[]);assert.deepEqual(network,[]);console.log('PASS: three separate builders, live edits, independent drafts, reorder/undo, download, sidebar restore, mobile and offline bundle.');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});

