const {chromium}=require(process.env.DEVKIT_PLAYWRIGHT||'playwright'),assert=require('node:assert/strict'),path=require('node:path'),{pathToFileURL}=require('node:url');
const root=path.resolve(__dirname,'..'),{createCompanion}=require('../companion/devkit-companion.cjs');
(async()=>{const companion=createCompanion({root,port:0,token:'browser-token'}),address=await companion.start(),browser=await chromium.launch({headless:true,...(process.env.DEVKIT_CHROME?{executablePath:process.env.DEVKIT_CHROME}:{})});try{for(const entry of ['index.html','dist/devkit.html']){const page=await browser.newPage({viewport:{width:1400,height:950}}),errors=[],requests=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',request=>{if(/^https?:/.test(request.url()))requests.push(request.url());});await page.goto(pathToFileURL(path.join(root,entry)).href);assert.equal(requests.length,0,'companion must stay dormant before explicit connection');
 await page.getByRole('button',{name:'Local',exact:true}).click();assert(await page.getByRole('heading',{name:'Local companion'}).isVisible());assert.equal(requests.length,0);await page.getByLabel('Companion URL').fill(`http://127.0.0.1:${address.port}`);await page.getByLabel('Companion token').fill('browser-token');await page.getByRole('button',{name:'Connect',exact:true}).click();await page.getByText(/DevKit Companion 1\.0\.0 connected/).waitFor();assert(await page.locator('.lc-tool.available').filter({hasText:'node'}).count());assert(requests.every(url=>url.startsWith(`http://127.0.0.1:${address.port}/`)));
 const input=page.getByLabel('Companion input');await page.getByLabel('Validation language').selectOption('json');await input.fill('{"service":"ready"}');await page.getByRole('button',{name:'Format',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.lc-editor')?.value.includes('\n  "service": "ready"\n'));await page.getByRole('button',{name:'Validate',exact:true}).click();await page.getByText('Valid JSON.',{exact:true}).last().waitFor();await page.getByRole('button',{name:'Read Git status'}).click();await page.locator('.lc-result').filter({hasText:'## '}).waitFor();
 await page.getByLabel('Companion URL').fill('http://example.com');await page.getByRole('button',{name:'Connect',exact:true}).click();await page.getByText(/Use a loopback URL/).waitFor();
 await page.getByRole('button',{name:'Close ✕',exact:true}).click();await page.getByLabel('Search all DevKit tools by command or intent').fill('local validation');assert(await page.locator('[data-search-id="workspace:companion"]').count());await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Local',exact:true}).click();assert(await page.getByLabel('Companion URL').isVisible());assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));assert.deepEqual(errors,[]);await page.close();}
 console.log('PASS: modular and standalone DevKit keep the companion dormant until requested, connect only to loopback, show tools and Git status, validate/format text, expose unified search, reject non-loopback URLs and stay mobile-safe.');
}finally{await browser.close();await companion.close();}})().catch(error=>{console.error(error);process.exitCode=1;});
