const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),assert=require('node:assert/strict');const root=path.resolve(__dirname,'..'),c=vm.createContext({console});for(const f of ['vendor/js-yaml.min.js','vendor/lezer-python.js','src/command-definitions.js','src/recipe-catalog.js','src/deep-model.js','src/python-model.js'])vm.runInContext(fs.readFileSync(path.join(root,f),'utf8'),c,{filename:f});
const report=vm.runInContext(String.raw`(()=>{const check=(b,msg)=>{if(!b)throw Error(msg);};const files=[];for(const id of Object.keys(PY_OPS)){if(id==='py_call')continue;const node=ddNode(pyP,id),result=ddGenerate(pyP,[node]);check(!result.errors.length,id+': '+result.errors);pyParse(result.text);files.push({name:id+'.py',text:result.text});}
 const source='import pandas as pd\n'.replace(/\\n/g,'\n');
 const code='import pandas as pd\ndf = pd.read_csv("input.csv")\nif len(df) > 0:\n    print(df)\nelse:\n    print("empty")\n'.replace(/\\n/g,'\n');
 const nodes=pyParse(code);check(nodes.length===3,'Missing recognized statements');check(nodes[1].type==='py_csv','CSV not recognized');check(nodes[2].type==='py_if','Condition not recognized');check(nodes[2].slots.then[0].type==='print','Nested print not recognized');files.push({name:'nested.py',text:pyP.generate(nodes)});
 for(const code of ['@decorator\ndef f():\n    return 1\n','with open("input.txt") as f:\n    print(f.read())\n','if x:\n    a()\nelif y:\n    b()\n','class Thing:\n    pass\n'].map(s=>s.replace(/\\n/g,'\n'))){const nodes=pyParse(code);check(nodes.length===1&&nodes[0].type==='raw','Unsupported construct was changed');check(nodes[0].values.text.trim()===code.trim(),'Raw code lost');}
 let failed=false;try{pyParse('if x:\n'.replace(/\\n/g,'\n'));}catch(e){failed=true;}check(failed,'Incomplete code accepted');
 const quotes=pyParse('x = "literal \\\\n"\n'.replace(/\\n$/,'\n'));files.push({name:'quoted.py',text:pyP.generate(quotes)});
 return files;})()`,c);
if(process.env.DEVKIT_TEST_OUTPUT){fs.mkdirSync(process.env.DEVKIT_TEST_OUTPUT,{recursive:true});for(const file of report)fs.writeFileSync(path.join(process.env.DEVKIT_TEST_OUTPUT,file.name),file.text);}assert(report.length>15);console.log('PASS: package operations, recursive Python parsing, opaque-block preservation and incomplete syntax detection.');
