const {chromium}=require(process.env.DEVKIT_PLAYWRIGHT||'playwright'),assert=require('node:assert/strict'),path=require('node:path'),{pathToFileURL}=require('node:url');
(async()=>{const browser=await chromium.launch({headless:true,...(process.env.DEVKIT_CHROME?{executablePath:process.env.DEVKIT_CHROME}:{})});try{const page=await browser.newPage({viewport:{width:1480,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 for(const entry of ['index.html','dist/devkit.html']){
 await page.goto(pathToFileURL(path.resolve(__dirname,'..',entry)).href);await page.evaluate(()=>{dkDrafts={};ddOpen('dockerfile','docker');});const code=page.getByLabel('Editable file preview');const source='FROM node:22-alpine\nWORKDIR /app\nENV NODE_ENV=production\nCOPY package.json /app/\nRUN npm install --omit=dev\nEXPOSE 3000\nCMD ["node", "server.js"]\n';await code.fill(source);await page.waitForFunction(()=>!ddState.sxDirty&&ddState.blocks.length===7);assert.deepEqual(await page.evaluate(()=>ddState.blocks.map(n=>n.type)),['from','workdir','env','copy','run_shell','expose','cmd']);assert.equal(await code.inputValue(),source);
 await page.getByLabel('Shell command',{exact:true}).fill('npm ci --omit=dev');assert((await code.inputValue()).includes('RUN npm ci --omit=dev'));await code.fill((await code.inputValue()).replace('node:22-alpine','node:24-alpine').replace('production','development').replace('3000','8080'));await page.waitForFunction(()=>!ddState.sxDirty);assert.equal(await page.getByLabel('Image',{exact:true}).inputValue(),'node:24-alpine');assert.equal(await page.getByLabel('Value',{exact:true}).first().inputValue(),'development');assert.equal(await page.getByLabel('Port',{exact:true}).inputValue(),'8080');
 await page.getByRole('button',{name:'Move ENV up',exact:true}).click();assert((await code.inputValue()).indexOf('ENV ')<(await code.inputValue()).indexOf('WORKDIR '));await page.getByRole('button',{name:'Undo',exact:true}).click();assert((await code.inputValue()).indexOf('WORKDIR ')<(await code.inputValue()).indexOf('ENV '));
 const good=await code.inputValue();await code.fill(good+'RUN ["echo",\n');await page.getByRole('button',{name:'Sync code to blocks now',exact:true}).click();assert(await page.evaluate(()=>ddState.sxDirty));assert.equal(await page.evaluate(()=>ddState.blocks.length),7);assert((await page.locator('#sx-status').textContent()).includes('JSON'));await page.getByRole('button',{name:'Undo',exact:true}).click();assert.equal(await code.inputValue(),good);
 await page.evaluate(()=>dkClose());await page.reload();await page.evaluate(()=>ddOpen('dockerfile','docker'));assert.equal(await code.inputValue(),good);assert.equal(await page.getByLabel('Shell command',{exact:true}).inputValue(),'npm ci --omit=dev');await page.getByRole('button',{name:'Keep as Custom code',exact:true}).click();assert.equal(await page.evaluate(()=>ddState.blocks[0].type),'sx_code');await page.getByRole('button',{name:'Sync code to blocks now',exact:true}).click();assert.equal(await page.evaluate(()=>ddState.blocks.length),7);assert(!await page.evaluate(()=>ddState.blocks.some(n=>n.type==='sx_code')));
 for(const id of ['bash','powershell','sql','jenkins','github-actions','gitlab-ci']){const text=await page.evaluate(id=>{const p=DD_PROFILES[id];ddOpen(id,['jenkins','github-actions','gitlab-ci'].includes(id)?'cicd':id);return p.generate(p.seed(p));},id);await code.fill(text);await page.getByRole('button',{name:'Sync code to blocks now',exact:true}).click();assert(!await page.evaluate(()=>ddState.sxDirty),id);assert(!await page.evaluate(()=>ddState.blocks.some(n=>n.type==='sx_code'||n.type==='object')),id+' lost built-in structure');}
 await page.evaluate(()=>ddOpen('terraform','terraform'));await code.fill('locals {\n  tags = {\n    "Name" = "app"\n    "Region" = var.region\n  }\n}\n');await page.getByRole('button',{name:'Sync code to blocks now',exact:true}).click();assert.equal(await page.evaluate(()=>ddState.blocks[0].slots.body[0].type),'object');await page.getByLabel('Text value',{exact:true}).fill('web');assert((await code.inputValue()).includes('"web"'));
 }
 await page.evaluate(()=>ddOpen('dockerfile','docker'));if(process.env.DEVKIT_SCREENSHOTS)await page.screenshot({path:path.join(process.env.DEVKIT_SCREENSHOTS,'docker-roundtrip.png')});await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Preview',exact:true}).click();assert(await codeVisible(page));assert.deepEqual(errors,[]);console.log('PASS: automatic Docker code→blocks→code, multiple edits, reorder/undo, invalid syntax preservation, draft reload, cross-module fresh parsing, Terraform object fields, mobile and both editions.');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
async function codeVisible(page){return page.getByLabel('Editable file preview').isVisible();}

