const {chromium}=require(process.env.DEVKIT_PLAYWRIGHT||'playwright');const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{pathToFileURL}=require('node:url');
(async()=>{const browser=await chromium.launch({headless:true,...(process.env.DEVKIT_CHROME?{executablePath:process.env.DEVKIT_CHROME}:{})});try{const page=await browser.newPage({acceptDownloads:true});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(pathToFileURL(path.resolve(__dirname,'../index.html')).href);await page.evaluate(()=>dkHome('bash'));
 const text='\uFEFF#!/bin/bash\r\n# Keep this comment\r\nprintf \'%s\\n\' "$HOME"\r\n';await page.getByLabel('Choose file to customize').setInputFiles({name:'existing.sh',mimeType:'text/plain',buffer:Buffer.from(text)});await page.waitForFunction(()=>ddState?.profile==='source');assert.equal(await page.evaluate(()=>ddOutput().text),text);assert.equal(await page.getByLabel('Output filename').inputValue(),'existing.sh');let pending=page.waitForEvent('download');await page.locator('#dd-download').click();let download=await pending;assert.equal(fs.readFileSync(await download.path(),'utf8'),text);
 await page.getByLabel('Editable file contents').fill('# Edited\necho hello\n');assert.equal(await page.evaluate(()=>ddOutput().text),'# Edited\r\necho hello\r\n');await page.locator('#dd-undo').click();assert.equal(await page.evaluate(()=>ddOutput().text),text);
 // An actual File drop opens structured JSON; the previous imported draft remains saved.
 const transfer=await page.evaluateHandle(()=>{const dt=new DataTransfer();dt.items.add(new File(['{"name":"app","enabled":true,"ports":[80]}'],'config.json',{type:'application/json'}));return dt;});await page.locator('.df-zone').dispatchEvent('drop',{dataTransfer:transfer});await page.waitForFunction(()=>ddState?.filename==='config.json');assert.equal(await page.evaluate(()=>ddState.profile),'json');await page.getByLabel('Numeric value').fill('443');assert.equal(await page.evaluate(()=>JSON.parse(ddOutput().text).ports[0]),443);
 const before=await page.evaluate(()=>JSON.stringify(ddState));await page.getByLabel('Choose file to customize').setInputFiles({name:'broken.json',mimeType:'application/json',buffer:Buffer.from('{bad')});await page.waitForFunction(()=>document.querySelector('.df-zone [role=status]').textContent.includes('Cannot build'));assert.equal(await page.evaluate(()=>JSON.stringify(ddState)),before);
 await page.getByLabel('File editing mode').selectOption('source');await page.getByLabel('Choose file to customize').setInputFiles({name:'broken.json',mimeType:'application/json',buffer:Buffer.from('{bad')});await page.waitForFunction(()=>ddState?.filename==='broken.json');assert.equal(await page.evaluate(()=>ddOutput().text),'{bad');
 await page.getByLabel('Choose file to customize').setInputFiles({name:'binary.bin',mimeType:'application/octet-stream',buffer:Buffer.from([0,1,2])});await page.waitForFunction(()=>document.querySelector('.df-zone [role=status]').textContent.includes('binary'));assert.equal(await page.evaluate(()=>ddState.filename),'broken.json');
 await page.reload();await page.evaluate(()=>ddOpen('source','bash',undefined,undefined,'upload:existing.sh'));assert.equal(await page.evaluate(()=>ddOutput().text),text);assert(await page.evaluate(()=>!!dkValidateBackup(dkBackup())));
 await page.evaluate(()=>{dkClose();abOpen();});await page.getByRole('button',{name:'Open / drop a file…'}).click();assert(await page.getByLabel('Choose file to customize').isVisible());
 await page.goto(pathToFileURL(path.resolve(__dirname,'../dist/devkit.html')).href);await page.evaluate(()=>dkHome('sql'));await page.getByLabel('Choose file to customize').setInputFiles({name:'query.sql',mimeType:'text/plain',buffer:Buffer.from('SELECT 1;\n')});await page.waitForFunction(()=>ddState?.filename==='query.sql');assert.equal(await page.evaluate(()=>ddOutput().text),'SELECT 1;\n');assert.deepEqual(errors,[]);console.log('PASS: file picker, File drop, source byte preservation, CRLF editing, invalid import rollback, source fallback, binary rejection, draft recovery, backup and both editions.');}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
