/* Platform-specific pipeline models; generated code is never executed. */
const ccLines=s=>s.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);
const ccOptional=(label,value='')=>ddField(label,value,'text',{required:false});
const ccMap=entries=>{const out=Object.create(null);for(const [k,v] of entries){if(Object.hasOwn(out,k))throw Error('Duplicate name: '+k);out[k]=v;}return out;};
function ccNeeds(jobs){
 const names=new Set(jobs.map(j=>j.name));if(names.size!==jobs.length)throw Error('Job names must be unique.');
 const visited=new Set(),active=new Set(),map=new Map(jobs.map(j=>[j.name,j]));
 function visit(j){if(active.has(j.name))throw Error('Needs contains a dependency cycle.');if(visited.has(j.name))return;active.add(j.name);for(const name of j.needs){if(!names.has(name))throw Error('Unknown dependency: '+name);visit(map.get(name));}active.delete(j.name);visited.add(j.name);}jobs.forEach(visit);
}
const ccPair=()=>ddType('Variable','One name/value pair. Do not put secret values in files; configure them on the CI platform.',{name:ddName('Variable name','APP_ENV'),value:ddField('Value','test','multiline')});
const ccCommand=()=>ddType('Shell command','One shell step. Multiline commands stay together with correct YAML formatting.',{text:ddField('Command','echo "Hello CI"','multiline')});
const ccCommands=nodes=>nodes.map(n=>{if(!n.values.text.trim())throw Error('A command is empty.');return n.values.text;});
const ccVars=nodes=>ccMap(nodes.map(n=>[n.values.name,n.values.value]));
{
 const p={id:'github-actions',title:'GitHub Actions workflow builder',filename:'ci.yml',description:'Choose events, add jobs, then add run steps or reusable actions. Save the downloaded file in .github/workflows/.',check:'Jobs are parallel unless linked by Needs; dragging steps changes execution order. Configure secrets in GitHub settings. Structural checks do not validate action inputs or shell commands. Validate the workflow in GitHub before use.',root:ddSlot('Workflow',['workflow'],1,1),types:{
 workflow:ddType('Workflow','Start here: name your workflow and choose when it runs.',{name:ddField('Workflow name','CI')},{events:ddSlot('When to run',['event','schedule'],1),env:ddSlot('Workflow variables',['variable','secret']),jobs:ddSlot('Jobs',['job'],1)}),
 event:ddType('Trigger event','Branch filters apply to push or pull request; manual dispatch ignores this field.',{event:ddChoice('Event','push',['push','pull_request','workflow_dispatch']),branches:ddField('Branches (one per line; blank means all)','main','multiline')}),
 schedule:ddType('Scheduled trigger','Five-field cron, in UTC. GitHub schedules run on the default branch.',{cron:ddField('UTC cron','0 6 * * 1-5')}),
 variable:ccPair(),secret:ddType('Secret reference','Enter the name stored in GitHub Actions secrets, not the secret value.',{name:ddName('Environment variable','API_TOKEN'),secret:ddName('GitHub secret name','API_TOKEN')}),
 job:ddType('Job','Needs is a list of other job IDs, one per line. Leave it empty to allow parallel execution.',{name:ddName('Job ID','test'),runner:ddField('Runner label','ubuntu-latest'),needs:ddField('Needs (job IDs, one per line)','','multiline'),timeout:ddField('Timeout in minutes','20','integer')},{env:ddSlot('Job variables',['variable','secret']),matrix:ddSlot('Matrix axes (optional)',['axis']),steps:ddSlot('Steps',['run','action'],1)}),
 axis:ddType('Matrix axis','Creates one job per value combination. Refer to an axis using an expression such as ${{ matrix.python }}.',{name:ddName('Axis name','python'),values:ddField('Values (one per line)','3.12\n3.13','multiline')}),
 run:ddType('Run command','Runs in the job workspace. Each block is a separate shell process.',{name:ddField('Step name','Run tests'),text:ddField('Shell commands','python -m unittest discover -v','multiline'),shell:ddChoice('Shell','default',['default','bash','pwsh','sh','cmd']),condition:ccOptional('If expression (optional)')},{env:ddSlot('Step variables',['variable','secret'])}),
 action:ddType('Use an action','Use owner/repository@ref or a local ./path. Add action inputs under With.',{name:ddField('Step name','Checkout repository'),uses:ddField('Action reference','actions/checkout@v7'),condition:ccOptional('If expression (optional)')},{inputs:ddSlot('With: action inputs',['input']),env:ddSlot('Step variables',['variable','secret'])}),
 input:ddType('Action input','Input names are defined by the chosen action. Expressions are supported as values.',{name:ddField('Input name','python-version'),value:ddField('Input value','3.13','multiline')})
 }};
 const env=nodes=>ccMap(nodes.map(n=>[n.values.name,n.type==='secret'?'${{ secrets.'+n.values.secret+' }}':n.values.value]));
 p.generate=nodes=>{const w=nodes[0],on=Object.create(null);for(const e of w.slots.events){if(e.type==='schedule'){if(e.values.cron.trim().split(/\s+/).length!==5)throw Error('A schedule needs five cron fields.');(on.schedule??=[]).push({cron:e.values.cron});}else{const key=e.values.event;if(Object.hasOwn(on,key))throw Error('Duplicate trigger: '+key);on[key]=key!=='workflow_dispatch'&&ccLines(e.values.branches).length?{branches:ccLines(e.values.branches)}:{};}}
 const jobs=w.slots.jobs;ccNeeds(jobs.map(j=>({name:j.values.name,needs:ccLines(j.values.needs)})));
 const out={name:w.values.name,on,permissions:{contents:'read'}};if(w.slots.env.length)out.env=env(w.slots.env);
 out.jobs=ccMap(jobs.map(j=>{const v=j.values,s=j.slots;if(Number(v.timeout)<=0)throw Error('Job timeout must be positive.');const job={'runs-on':v.runner,'timeout-minutes':Number(v.timeout)};if(ccLines(v.needs).length)job.needs=ccLines(v.needs);if(s.env.length)job.env=env(s.env);if(s.matrix.length){const matrix=ccMap(s.matrix.map(a=>{const values=ccLines(a.values.values);if(!values.length)throw Error('A matrix axis needs values.');return [a.values.name,values];}));job.strategy={matrix};}
 job.steps=s.steps.map(step=>{const x=step.values,res={name:x.name};if(step.type==='run'){if(!x.text.trim())throw Error('A run step needs a command.');res.run=x.text;if(x.shell!=='default')res.shell=x.shell;}else{res.uses=x.uses;if(!/^(\.\/|docker:\/\/|[^\s]+@[^\s]+$)/.test(x.uses))throw Error('Action references need @ref, ./path or docker://.');if(step.slots.inputs.length)res.with=ccMap(step.slots.inputs.map(i=>[i.values.name,i.values.value]));}if(x.condition.trim())res.if=x.condition;if(step.slots.env.length)res.env=env(step.slots.env);return res;});return [v.name,job];}));return dkYaml(out);};
 p.seed=p=>{const n=(t,v={},s={})=>ddNode(p,t,v,s);return [n('workflow',{}, {events:[n('event'),n('event',{event:'pull_request',branches:''})],jobs:[n('job',{}, {steps:[n('action'),n('action',{name:'Set up Python',uses:'actions/setup-python@v6'},{inputs:[n('input')]}),n('run')]})]})];};DD_PROFILES[p.id]=p;
}
{
 const p={id:'gitlab-ci',title:'GitLab CI pipeline builder',filename:'.gitlab-ci.yml',description:'Add stages in execution order and jobs inside each stage. Each command becomes a correctly formatted script entry.',check:'Save .gitlab-ci.yml at the repository root and validate with GitLab CI Lint. Configure masked secrets in project/group CI/CD variables. Images require a compatible runner executor. Rules, commands and runner availability are not validated here.',root:ddSlot('Pipeline',['pipeline'],1,1),types:{
 pipeline:ddType('Pipeline','Choose a default container image, then build stages from top to bottom.',{image:ccOptional('Default image','python:3.13')},{variables:ddSlot('Pipeline variables',['variable']),stages:ddSlot('Stages in order',['stage'],1)}),variable:ccPair(),
 stage:ddType('Stage','Jobs in a stage can run in parallel. Drag stages to change their execution order.',{name:ddField('Stage name','test')},{jobs:ddSlot('Jobs in this stage',['job'],1)}),
 job:ddType('Job','Needs may reference jobs in the same or earlier stages. A dependency can let this job start before the previous stage fully completes.',{name:ddField('Job name','unit_tests'),image:ccOptional('Override image'),tags:ddField('Runner tags (one per line)','','multiline'),needs:ddField('Needs (job names, one per line)','','multiline'),when:ddChoice('Default run policy','on_success',['on_success','manual','always','on_failure']),allowFailure:ddChoice('Allow failure','false',['false','true'])},{variables:ddSlot('Job variables',['variable']),before:ddSlot('Before script',['command']),script:ddSlot('Script commands',['command'],1),after:ddSlot('After script (separate shell)',['command']),rules:ddSlot('Rules (first matching rule wins)',['rule']),artifacts:ddSlot('Artifacts',['artifacts'],0,1),cache:ddSlot('Cache',['cache'],0,1)}),
 command:ccCommand(),rule:ddType('Conditional rule','Use a GitLab expression such as $CI_COMMIT_BRANCH == "main". Blank If creates a fallback rule.',{condition:ccOptional('If expression','$CI_COMMIT_BRANCH == "main"'),when:ddChoice('When matched','on_success',['on_success','manual','always','never','on_failure']),allowFailure:ddChoice('Allow failure','false',['false','true'])}),
 artifacts:ddType('Save artifacts','Paths relative to the project directory. Generated files can be downloaded after the job.',{paths:ddField('Paths (one per line)','dist/','multiline'),expire:ddField('Expire after','1 week'),when:ddChoice('Save when','on_success',['on_success','always','on_failure'])}),
 cache:ddType('Dependency cache','Cache is an optimization and may be missing; installation steps still need to work.',{key:ddField('Cache key','$CI_COMMIT_REF_SLUG'),paths:ddField('Cached paths (one per line)','.cache/pip/','multiline')})
 }};
 p.generate=nodes=>{const r=nodes[0],stages=r.slots.stages,stageNames=stages.map(s=>s.values.name);if(new Set(stageNames).size!==stageNames.length)throw Error('Stage names must be unique.');const all=stages.flatMap((s,i)=>s.slots.jobs.map(j=>({node:j,name:j.values.name,needs:ccLines(j.values.needs),stage:s.values.name,index:i})));ccNeeds(all);const reserved=new Set(['stages','default','variables','include','workflow','image','services','cache','before_script','after_script','spec','pages','types','true','false','nil']);const out={stages:stageNames};if(r.values.image.trim())out.default={image:r.values.image};if(r.slots.variables.length)out.variables=ccVars(r.slots.variables);
 for(const info of all){const {node:j,name,stage}=info,v=j.values,s=j.slots;if(name.startsWith('.')||reserved.has(name)||name.length>255)throw Error('Use a visible, non-reserved job name: '+name);for(const dependency of info.needs)if(all.find(x=>x.name===dependency).index>info.index)throw Error('Needs cannot reference a later stage: '+dependency);const job={stage,script:ccCommands(s.script),when:v.when,allow_failure:v.allowFailure==='true'};if(v.image.trim())job.image=v.image;if(ccLines(v.tags).length)job.tags=ccLines(v.tags);if(info.needs.length)job.needs=info.needs;if(s.variables.length)job.variables=ccVars(s.variables);if(s.before.length)job.before_script=ccCommands(s.before);if(s.after.length)job.after_script=ccCommands(s.after);if(s.rules.length)job.rules=s.rules.map(n=>({...n.values.condition.trim()?{if:n.values.condition}:{},when:n.values.when,allow_failure:n.values.allowFailure==='true'}));
 for(const key of ['artifacts','cache'])if(s[key].length){const a=s[key][0].values,paths=ccLines(a.paths);if(!paths.length)throw Error(key+' needs at least one path.');job[key]=key==='artifacts'?{paths,expire_in:a.expire,when:a.when}:{key:a.key,paths};}Object.defineProperty(out,name,{value:job,enumerable:true});}return dkYaml(out);};
 p.seed=p=>{const n=(t,v={},s={})=>ddNode(p,t,v,s);return [n('pipeline',{}, {stages:[n('stage',{}, {jobs:[n('job',{}, {script:[n('command',{text:'python -m unittest discover -v'})]})]})]})];};DD_PROFILES[p.id]=p;
}
{
 const steps=['sh','bat','echo','checkout','archive','junit','retry','directory'];
 const p={id:'jenkins',title:'Jenkins Declarative Pipeline builder',filename:'Jenkinsfile',description:'Pick an agent, build sequential or parallel stages, and add steps. Groovy quoting and braces are generated automatically.',check:'Validate with the Declarative Pipeline linter on your Jenkins controller. Plugin steps and agent tools must be available on that installation. Credential blocks store an ID, not a secret value. Shell commands are not executed or validated here.',root:ddSlot('Pipeline',['pipeline'],1,1),types:{
 pipeline:ddType('Pipeline','Any uses an available agent; Label selects agents with your Jenkins label expression.',{agent:ddChoice('Agent selection','any',['any','label']),label:ccOptional('Agent label','linux'),timeout:ddField('Pipeline timeout (minutes)','30','integer')},{env:ddSlot('Environment',['variable','credential']),stages:ddSlot('Stages in order',['stage','parallel'],1),post:ddSlot('After the pipeline',['post'])}),
 variable:ccPair(),credential:ddType('Credential binding','Jenkins credentials() helper. The ID must already exist and support environment binding.',{name:ddName('Environment variable','API_TOKEN'),value:ddField('Jenkins credential ID','api-token')}),
 stage:ddType('Sequential stage','Stages execute top to bottom. Steps inside a stage also run in order.',{name:ddField('Stage name','Test')},{steps:ddSlot('Stage steps',steps,1)}),
 parallel:ddType('Parallel stage','Branches run concurrently on the selected pipeline agent. Use separate directories if branches write workspace files.',{name:ddField('Parallel stage name','Parallel checks')},{branches:ddSlot('Parallel branches',['stage'],2)}),
 sh:ddType('Unix shell command','Requires a Unix-like agent with sh. Multiline scripts are supported.',{text:ddField('Shell commands','python3 -m unittest discover -v','multiline')}),
 bat:ddType('Windows batch command','Requires a Windows agent.',{text:ddField('Batch commands','python -m unittest discover -v','multiline')}),
 echo:ddType('Print message','Literal message; Groovy interpolation is escaped.',{text:ddField('Message','Pipeline complete','multiline')}),
 checkout:ddType('Checkout repository','checkout scm uses the SCM configured for a multibranch or Pipeline-from-SCM job.'),
 archive:ddType('Archive artifacts','Comma-separated Ant patterns; requires generated files to exist.',{text:ddField('Artifact patterns','dist/**')}),
 junit:ddType('Publish JUnit results','Requires the JUnit plugin and test reports in JUnit XML format.',{text:ddField('Report patterns','reports/*.xml')}),
 retry:ddType('Retry steps','Retry a failing group; choose commands that can safely run again.',{count:ddField('Attempts','3','integer')},{steps:ddSlot('Steps to retry',steps,1)}),
 directory:ddType('Change directory','Run nested steps in a workspace subdirectory.',{path:ddField('Relative directory','app')},{steps:ddSlot('Steps in directory',steps,1)}),
 post:ddType('Post condition','Add cleanup or reporting after the pipeline completes.',{condition:ddChoice('Run after','always',['always','success','failure','unstable','aborted','cleanup'])},{steps:ddSlot('Post steps',steps,1)})
 }};
 const quote=s=>"'"+s.replace(/\\/g,'\\\\').replace(/'/g,"\\'").replace(/\r/g,'\\r').replace(/\n/g,'\\n')+"'";
 const wrap=(head,body)=>head+' {\n'+ddIndent(body)+'\n}';
 function emit(nodes){return nodes.map(n=>{const v=n.values;if(['sh','bat','echo'].includes(n.type)){if(!v.text.trim())throw Error('A step needs text.');return n.type+' '+quote(v.text);}if(n.type==='checkout')return 'checkout scm';if(n.type==='archive')return 'archiveArtifacts artifacts: '+quote(v.text)+', fingerprint: true';if(n.type==='junit')return 'junit '+quote(v.text);if(n.type==='retry'){if(Number(v.count)<1)throw Error('Retry attempts must be positive.');return wrap('retry('+Number(v.count)+')',emit(n.slots.steps));}if(n.type==='directory')return wrap('dir('+quote(v.path)+')',emit(n.slots.steps));throw Error('Unknown Jenkins step.');}).join('\n');}
 function stages(nodes){ccMap(nodes.map(n=>[n.values.name,true]));return nodes.map(n=>wrap('stage('+quote(n.values.name)+')',n.type==='parallel'?wrap('parallel',stages(n.slots.branches)):wrap('steps',emit(n.slots.steps)))).join('\n');}
 p.generate=nodes=>{const n=nodes[0],v=n.values,s=n.slots;if(Number(v.timeout)<1)throw Error('Timeout must be positive.');if(v.agent==='label'&&!v.label.trim())throw Error('Enter an agent label.');let body=v.agent==='any'?'agent any':wrap('agent','label '+quote(v.label));body+='\n'+wrap('options','timeout(time: '+Number(v.timeout)+", unit: 'MINUTES')\nskipDefaultCheckout(true)");if(s.env.length){ccVars(s.env);body+='\n'+wrap('environment',s.env.map(e=>e.values.name+' = '+(e.type==='credential'?'credentials('+quote(e.values.value)+')':quote(e.values.value))).join('\n'));}body+='\n'+wrap('stages',stages(s.stages));if(s.post.length){ccMap(s.post.map(x=>[x.values.condition,true]));body+='\n'+wrap('post',s.post.map(x=>wrap(x.values.condition,emit(x.slots.steps))).join('\n'));}return wrap('pipeline',body)+'\n';};
 p.seed=p=>{const n=(t,v={},s={})=>ddNode(p,t,v,s);return [n('pipeline',{}, {stages:[n('stage',{name:'Checkout'},{steps:[n('checkout')]}),n('stage',{}, {steps:[n('sh')]})],post:[n('post',{}, {steps:[n('echo')]})]})];};DD_PROFILES[p.id]=p;
}
