DK_GUIDES.cicd=['CI/CD pipeline builders','Choose your platform, start with a working structure, and customize its blocks.','Each platform has its own syntax, draft and export filename. DevKit builds files locally; it does not run pipelines.','Choose GitHub Actions, GitLab CI or Jenkins.','https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax'];
const ccPreviousRender=ddRender;
ddRender=function(){ccPreviousRender();const p=CC_PLATFORMS.find(p=>p.id===ddState.profile);if(!p)return;const output=document.querySelector('#dk-root .dk-output');output.prepend(dkEl('p','dd-tip','Save in your repository as '+p.destination+(p.id==='gitlab-ci'?'. Some browsers remove the leading dot on download; restore it so the filename is exactly .gitlab-ci.yml.':'.')));};
function ccCards(host,selected){const grid=dkEl('div','dk-recipes');for(const p of CC_PLATFORMS.filter(p=>!selected||p.id===selected)){const card=dkEl('section','dk-guide');card.append(dkEl('h3','',p.name),dkEl('p','',p.flow),dkEl('p','dk-help',p.hint),dkEl('code','',p.destination),dkBtn('Build '+p.name+' →',()=>ddOpen(p.id,'cicd'),'dk-btn primary'));const link=dkEl('a','dk-help','Official syntax reference ↗');link.href=p.url;link.target='_blank';link.rel='noopener';card.append(link);grid.append(card);}host.append(grid);}
const ccPreviousHome=dkHome;
dkHome=function(sheet){ccPreviousHome(sheet);if(sheet!=='cicd')return;const root=document.getElementById('dk-root');root.replaceChildren();const header=dkEl('header','dk-header'),title=dkEl('div');title.append(dkEl('span','dk-eyebrow','DEVKIT / CI/CD'),dkEl('h2','','Choose your pipeline platform'),dkEl('p','dk-help','Each builder remembers its own draft. Add blocks, fill in fields, then copy or download the finished file.'));header.append(title,dkBtn('Close ✕',dkClose));root.append(header);const body=dkEl('div','dk-home');ccCards(body);body.append(dkEl('p','dk-help','Have an existing file? Import opens YAML as editable data blocks or Jenkinsfile as source text. Platform-specific reverse parsing is not yet supported.'),dfZone('cicd'));root.append(body);};
const ccPreviousSheet=renderSheet;
renderSheet=function(key,q){ccPreviousSheet(key,q);if(key!=='cicd')return;const banner=document.querySelector('#main .dk-banner');if(banner){banner.replaceChildren();ccCards(banner,CC_PLATFORMS.some(p=>p.id===state.activeSection)?state.activeSection:null);}};
const ccPreviousSuggestions=ddSuggestions;
ddSuggestions=function(parent,slot){const p=ddProfile();if(!CC_PLATFORMS.some(x=>x.id===p.id))return ccPreviousSuggestions(parent,slot);const def=ddLaneDef(parent,slot),list=ddLane(parent,slot);if(list.length>=def.max)return [];const n=(t,v={},s={})=>ddNode(p,t,v,s),suggestions=[];const add=(label,type,make)=>{if(def.accept.includes(type))suggestions.push({label,make});};
 if(p.id==='github-actions'){add('Checkout repository','action',()=>n('action'));add('Set up Python','action',()=>n('action',{name:'Set up Python',uses:'actions/setup-python@v6'},{inputs:[n('input')]}));add('Install Python dependencies','run',()=>n('run',{name:'Install dependencies',text:'python -m pip install -r requirements.txt'}));add('Run Python tests','run',()=>n('run'));add('Manual run button','event',()=>n('event',{event:'workflow_dispatch',branches:''}));}
 if(p.id==='gitlab-ci'){add('Install requirements','command',()=>n('command',{text:'python -m pip install -r requirements.txt'}));add('Run Python tests','command',()=>n('command',{text:'python -m unittest discover -v'}));add('Install Node dependencies','command',()=>n('command',{text:'npm ci'}));add('Run Node tests','command',()=>n('command',{text:'npm test'}));}
 if(p.id==='jenkins'){add('Checkout repository','checkout',()=>n('checkout'));add('Unix Python tests','sh',()=>n('sh'));add('Windows Python tests','bat',()=>n('bat'));}
 return suggestions;};
