/* Local lexical coloring. The textarea remains the sole editable/accessibility surface. */
const hcEditors=new Map();
function hcLanguage(el){if(el.id==='ab-preview')return 'yaml';if(el.id==='dd-preview'){const p=ddState?.profile;if(['github-actions','gitlab-ci'].includes(p))return 'yaml';if(p==='source'){const f=ddState.filename||'';return /\.json$/i.test(f)?'json':/\.ya?ml$/i.test(f)?'yaml':/\.py$/i.test(f)?'python':/\.ps1$/i.test(f)?'powershell':/\.tf$/i.test(f)?'terraform':'bash';}return p;}return dkActive?.sheet||'bash';}
function hcTokens(text,lang){
 const out=[],hash=!['json','sql'].includes(lang),sql=lang==='sql';
 const re=/"""[\s\S]*?(?:"""|$)|'''[\s\S]*?(?:'''|$)|"(?:\\[\s\S]|[^"\\])*(?:"|$)|'(?:\\[\s\S]|''|[^'\\])*(?:'|$)|\/\*[\s\S]*?(?:\*\/|$)|#[^\n]*|--[^\n]*|\$\{[^}\n]*\}|\$[A-Za-z_][\w:]*|\b\d+(?:\.\d+)?\b|\b[A-Za-z_][\w.-]*\b|[{}\[\]():,=|<>;+*/!-]/g;
 const keywords=new Set(('if else elif then fi for while do done in function def class return import from as try except finally with raise pass break continue async await const let var true false null none and or not select from where join left right inner outer on group by order having limit insert into values update set delete create table alter drop union all distinct case when end terraform provider resource data variable output locals module pipeline agent stages stage steps environment post options parallel script FROM RUN CMD ENTRYPOINT COPY ADD WORKDIR ENV ARG EXPOSE USER VOLUME SHELL HEALTHCHECK STOPSIGNAL ONBUILD').toLowerCase().split(' '));
 let last=0;for(const m of text.matchAll(re)){if(m.index>last)out.push(['',text.slice(last,m.index)]);const t=m[0],tail=text.slice(m.index+t.length),before=text.slice(text.lastIndexOf('\n',m.index-1)+1,m.index);let kind='';
 if(t[0]==='#')kind=hash?'comment':'';else if(t.startsWith('--'))kind=sql?'comment':'flag';else if(t.startsWith('/*'))kind=['sql','terraform','jenkins'].includes(lang)?'comment':'';
 else if(t[0]==='"'||t[0]==="'")kind=/^\s*:/.test(tail)&&['json','yaml'].includes(lang)?'key':'string';
 else if(t[0]==='$')kind='variable';else if(/^\d/.test(t))kind='number';else if(/^[\w.-]+$/.test(t)){if(['yaml','json'].includes(lang)&&/^\s*:/.test(tail))kind='key';else if(keywords.has(t.toLowerCase()))kind='keyword';else if(/^\s*\(/.test(tail))kind='function';else if(lang==='dockerfile'&&!before.trim())kind='keyword';}
 else kind='punctuation';out.push([kind,t]);last=m.index+t.length;}if(last<text.length)out.push(['',text.slice(last)]);return out;
}
function hcAttach(el){if(hcEditors.has(el))return;const style=getComputedStyle(el),wrap=document.createElement('div');wrap.className='hc-editor';wrap.style.minHeight=style.minHeight;wrap.style.height=Math.max(el.offsetHeight,parseFloat(style.minHeight)||100)+'px';el.before(wrap);wrap.append(el);const layer=document.createElement('pre');layer.className='hc-layer';layer.setAttribute('aria-hidden','true');const content=document.createElement('code');layer.append(content);wrap.prepend(layer);el.classList.add('hc-input');el.wrap='off';const item={el,wrap,layer,content,value:null,lang:null};hcEditors.set(el,item);el.addEventListener('input',()=>hcPaint(item));el.addEventListener('scroll',()=>hcScroll(item));item.observer=new ResizeObserver(()=>hcMetrics(item));item.observer.observe(el);hcMetrics(item);hcPaint(item);}
function hcMetrics(item){const s=getComputedStyle(item.el);for(const key of ['fontFamily','fontSize','fontWeight','fontStyle','lineHeight','letterSpacing','tabSize','paddingTop','paddingRight','paddingBottom','paddingLeft','borderTopWidth','borderRightWidth','borderBottomWidth','borderLeftWidth','borderRadius'])item.layer.style[key]=s[key];hcScroll(item);}
function hcScroll(item){item.content.style.transform='translate('+(-item.el.scrollLeft)+'px,'+(-item.el.scrollTop)+'px)';}
function hcPaint(item){const value=item.el.value,lang=hcLanguage(item.el);if(value===item.value&&lang===item.lang)return;item.value=value;item.lang=lang;const fragment=document.createDocumentFragment();if(value.length>200000){fragment.append(document.createTextNode(value));}else for(const [kind,text] of hcTokens(value,lang)){if(!kind)fragment.append(document.createTextNode(text));else{const span=document.createElement('span');span.className='hc-'+kind;span.textContent=text;fragment.append(span);}}fragment.append(document.createTextNode('\n'));item.content.replaceChildren(fragment);hcScroll(item);}
function hcScan(){for(const [el,item] of hcEditors)if(!el.isConnected){item.observer.disconnect();hcEditors.delete(el);}for(const el of document.querySelectorAll('#dd-preview,#ab-preview,#dk-preview,#sx-command-preview'))hcAttach(el);}
new MutationObserver(hcScan).observe(document.body,{childList:true,subtree:true});
// Programmatic block edits update textarea.value without emitting an input event.
setInterval(()=>{for(const item of hcEditors.values())if(item.el.getClientRects().length){hcPaint(item);hcMetrics(item);}},120);
hcScan();

