/* New documents start quietly. Existing drafts and explicitly chosen examples are retained. */
function dxInitial(p,seed){if(seed)return {blocks:seed,sxDirty:false,pyDirty:false,sxCode:undefined,pyCode:undefined};const text=p.id==='bash'?'#!/usr/bin/env bash\n':p.id==='python'?'#!/usr/bin/env python3\n':'';return {blocks:[],sxDirty:false,pyDirty:false,sxCode:p.id==='python'?undefined:text,sxSignature:sxSignature([]),pyCode:p.id==='python'?text:undefined,pySyncSig:p.id==='python'?pySignature([]):undefined};}
function dxFiles(root){for(const zone of root.querySelectorAll('.df-zone')){if(zone.parentElement.tagName==='DETAILS')continue;const details=dkEl('details','dx-files');details.append(dkEl('summary','','Open or drop a file'));zone.before(details);details.append(zone);details.addEventListener('dragenter',e=>{if(Array.from(e.dataTransfer?.types||[]).includes('Files'))details.open=true;});}}
const dxRefresh=ddRefresh;ddRefresh=function(){dxRefresh();if(ddState&&ddState.blocks.length===0){const code=ddState.profile==='python'?ddState.pyCode:ddState.sxCode;if(typeof code==='string')document.getElementById('dd-preview').value=code;}};
const dxRender=ddRender;ddRender=function(){dxRender();const root=document.getElementById('dk-root');dxFiles(root);for(const input of root.querySelectorAll('textarea.dk-input')){const fit=()=>input.rows=Math.max(1,Math.min(6,input.value.split('\n').length));fit();input.addEventListener('input',fit);}for(const tip of root.querySelectorAll('.dd-editor > .dd-tip'))tip.textContent='Add a block below or type in the code pane. Drag ⋮⋮ to reorder.';const code=document.getElementById('dd-preview');code.placeholder='Start typing here, or add your first block…';if(!ddState.blocks.length){const help=dkEl('div','dx-start');help.append(dkEl('strong','','Start with code or blocks'),dkEl('p','dk-help','Your page is empty. Add a block on the left, type here, or choose Load starter for a complete example.'));code.before(help);}ddRefresh();};
const dxAbRender=abRender;abRender=function(){dxAbRender();dxFiles(document.getElementById('ab-dialog'));axSuggestions();};
/* Completion actions are visible without opening a disclosure. Only show changed lines. */
axSuggestions=function(){const status=document.getElementById('sx-ansible-status');if(!status)return;let host=document.getElementById('ax-completions');if(!host){host=dkEl('section','dx-completions');host.id='ax-completions';host.setAttribute('aria-label','YAML completion suggestions');status.after(host);}host.replaceChildren();
 const source=abState.sxCode??document.getElementById('ab-preview').value;
 const hasError=!!(abState.sxDirty&&abState.sxError);let candidates=hasError?axCompletions(source):[];
 if(!source.trim())candidates=[{label:'Start a named '+(['tasks','handlers'].includes(abState.kind)?'task':'play'),code:['playbook','tasks','handlers'].includes(abState.kind)?'- name: ""\n':'name: ""\n'}];
 host.hidden=!candidates.length&&!hasError;if(host.hidden)return;if(abState.sxError)status.textContent='Unfinished YAML — choose a repair, keep typing, or resume your last valid blocks.';
 host.append(dkEl('strong','dx-completion-title',abState.sxError?'Fix unfinished YAML':'Start your YAML'),dkEl('p','dk-help','Review the change, then apply it. Your text stays unchanged until you choose.'));
 for(const item of candidates){const card=dkEl('div','dx-completion');const before=source.split('\n'),after=item.code.split('\n');let first=0;while(first<before.length&&first<after.length&&before[first]===after[first])first++;let last=after.length-1;while(last>first&&!after[last])last--;const snippet=after.slice(first,Math.min(last+1,first+5)).join('\n');card.append(dkEl('span','dx-completion-label',item.label),dkEl('pre','',snippet));const button=abButton('Apply: '+item.label,()=>{if((abState.sxCode??document.getElementById('ab-preview').value)!==source)return;abHistory();abState.sxCode=item.code;abState.sxDirty=true;delete abState.sxError;document.getElementById('ab-preview').value=item.code;abSave();sxAnsibleSync();},'ab-button primary');card.append(button);host.append(card);}if(hasError)host.append(abButton('Discard invalid YAML and resume last valid blocks',()=>{abHistory();delete abState.sxCode;delete abState.sxSignature;delete abState.sxError;abState.sxDirty=false;abSave();abRender();}));
};

