/* Recursive syntax trees. No generated code is evaluated or executed. */
const DD_PROFILES={};
const ddField=(label,value='',type='text',extra={})=>({label,value,type,...extra});
const ddChoice=(label,value,choices)=>ddField(label,value,'choice',{choices});
const ddName=(label,value)=>ddField(label,value,'name');
const ddSlot=(label,accept,min=0,max=Infinity)=>({label,accept,min,max});
const ddType=(label,hint,fields={},slots={})=>({label,hint,fields,slots});
let ddSerial=0;
const ddId=()=> 'n'+Date.now().toString(36)+'_'+(++ddSerial);
function ddNode(profile,type,values={},slots={}){const def=profile.types[type];return {id:ddId(),type,values:{...Object.fromEntries(Object.entries(def.fields).map(([k,f])=>[k,JSON.parse(JSON.stringify(f.value))])),...values},slots:Object.fromEntries(Object.keys(def.slots).map(k=>[k,slots[k]||[]]))};}
const ddIndent=(s,n=1)=>s.split('\n').map(l=>l?'  '.repeat(n)+l:l).join('\n');
const ddIdent=v=>{if(!/^[A-Za-z_][A-Za-z0-9_]*$/.test(v))throw Error('Use a name containing letters, numbers and underscores.');return v;};
const ddSQLName=v=>v.split('.').map(x=>x==='*'?'*':'"'+x.replace(/"/g,'""')+'"').join('.');
const ddSQLText=v=>"'"+v.replace(/'/g,"''")+"'";
const ddHCLText=v=>JSON.stringify(v).replace(/\$\{/g,()=>'$${').replace(/%\{/g,'%%{');
const DD_VALUE_TYPES=['object','array','text','number','boolean','null'];
function ddValueTypes(expressions=false){
 const all=[...DD_VALUE_TYPES,...(expressions?['expression']:[])],key=()=>ddField('Property name','value','text',{required:false});
 return {
  object:ddType('Object / mapping','Named properties. Add as many nested values as you need.',{key:key()},{items:ddSlot('Properties',all)}),
  array:ddType('List / array','Ordered items; property names are ignored inside lists.',{key:key()},{items:ddSlot('Items',all)}),
  text:ddType('Text','Quotes and multiline formatting are handled automatically.',{key:key(),value:ddField('Text value','','multiline')}),
  number:ddType('Number','A numeric value, not a quoted string.',{key:key(),value:ddField('Numeric value','0','decimal')}),
  boolean:ddType('True / false','A real boolean value.',{key:key(),value:ddChoice('Boolean','true',['true','false'])}),
  null:ddType('Null','An explicit empty value.',{key:key()}),
  ...(expressions?{expression:ddType('Terraform expression','Advanced: emitted as HCL, without quotes. For example var.region or string.',{key:key(),value:ddField('HCL expression','var.region','expression')})}:{})
 };
}
function ddValue(n){const v=n.values;if(n.type==='object'){const out={};for(const child of n.slots.items){const key=child.values.key;if(!key.trim())throw Error('Object properties need a name.');if(Object.hasOwn(out,key))throw Error('Duplicate property: '+key);Object.defineProperty(out,key,{value:ddValue(child),enumerable:true});}return out;}if(n.type==='array')return n.slots.items.map(ddValue);if(n.type==='text')return v.value;if(n.type==='number'){if(!/^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$/.test(v.value)||!Number.isFinite(Number(v.value)))throw Error('Enter a finite number.');return Number(v.value);}if(n.type==='boolean')return v.value==='true';if(n.type==='null')return null;throw Error('Unsupported value type.');}
function ddFromValue(profile,value,key=''){const type=value===null?'null':Array.isArray(value)?'array':typeof value==='object'?'object':typeof value==='boolean'?'boolean':typeof value==='number'?'number':'text';const node=ddNode(profile,type,{key,...(['text','number','boolean'].includes(type)?{value:String(value)}:{})});if(type==='object')node.slots.items=Object.entries(value).map(([k,v])=>ddFromValue(profile,v,k));if(type==='array')node.slots.items=value.map(v=>ddFromValue(profile,v));return node;}
for(const format of ['yaml','json'])DD_PROFILES[format]={id:format,title:format.toUpperCase()+' document editor',description:'Build typed properties, nested objects and ordered lists. Formatting, escaping and indentation are automatic.',filename:'config.'+(format==='yaml'?'yml':'json'),types:ddValueTypes(),root:ddSlot(format==='yaml'?'Documents':'Root value',DD_VALUE_TYPES,1,format==='json'?1:Infinity),generate:nodes=>format==='json'?JSON.stringify(ddValue(nodes[0]),null,2)+'\n':nodes.map(n=>dkYaml(ddValue(n))).join(''),seed:p=>[ddFromValue(p,{name:'my-app',enabled:true,settings:{port:8080},items:['first','second']})],check:'Structural syntax is checked. Target application schemas still need their own validation.'};

// Script nodes share an editor, but have language-specific syntax and quoting.
for(const language of ['bash','powershell','python']){
 const ps=language==='powershell',py=language==='python';
 const statements=['comment','variable','arrayVariable','print','command','pipeline','if','foreach','while','function','return',...(ps||py?['try']:[]),'raw'];
 const scalarFields={mode:ddChoice('Value kind','literal',['literal','variable','expression']),value:ddField('Value','hello','multiline')};
 const body=()=>ddSlot('Steps',statements),types={
  comment:ddType('Comment','Describe why a step exists.',{text:ddField('Comment','Describe this step','multiline')}),
  variable:ddType('Set a variable','Choose a literal value or reference another variable.',{name:ddName('Variable name','message'),...scalarFields}),
  arrayVariable:ddType('Set an array variable','Literal items, one per line. Use this variable in a for-each loop.',{name:ddName('Variable name','items'),items:ddField('Items','first\nsecond','multiline')}),
  print:ddType('Print a value','A literal stays literal; quotes and dollar signs are escaped.',scalarFields),
  command:ddType('Run a command','Add arguments individually. You do not need to quote literal arguments.',{program:ddField('Executable / command',ps?'Get-ChildItem':'echo')},{args:ddSlot('Arguments',ps?['parameter','argument']:['argument'])}),
  pipeline:ddType('Command pipeline',py?'Run commands as a subprocess pipeline using captured text output. Best for small text output.':'Connect commands with pipes in their visible order.',{},{commands:ddSlot('Pipeline commands',['command'],2)}),
  ...(ps?{parameter:ddType('Named parameter / switch','The editor supplies the hyphen; literal parameter values are quoted.',{name:ddName('Parameter name','Path'),kind:ddChoice('Parameter kind','value',['value','switch']),...scalarFields})}:{}),
  argument:ddType('Command argument','One argument per block. Choose variable to insert its value.',scalarFields),
  if:ddType('If / else','Choose a comparison and build each branch.',{left:ddName('Variable to test','message'),operator:ddChoice('Comparison','equals',['equals','not equals','greater than','less than','is empty','is not empty']),right:ddField('Compare with','hello')},{then:ddSlot('Then',statements),else:ddSlot('Otherwise (optional)',statements)}),
  foreach:ddType('For each item','Iterate over literal values, or an existing array variable.',{name:ddName('Item variable','item'),source:ddChoice('Items come from','literal list',['literal list','array variable']),items:ddField('Items (one per line), or array variable name','first\nsecond','multiline')},{body:body()}),
  while:ddType('While a condition holds','The loop body must change the condition when you want it to stop.',{left:ddName('Variable to test','running'),operator:ddChoice('Comparison','equals',['equals','not equals','greater than','less than','is empty','is not empty']),right:ddField('Compare with','yes')},{body:body()}),
  function:ddType('Function','Define a reusable group of steps. Use a command block to call shell functions; Python calls can use an advanced statement.',{name:ddName('Function name','main')},{body:body()}),
  return:ddType('Return from function',py?'Return a literal, variable or expression.':'Return a status code from the function.',py?scalarFields:{value:ddField('Status code','0','integer')}),
  raw:ddType('Advanced statement','Escape hatch: this text is not syntax-checked. Indentation follows its parent.',{text:ddField('Code','', 'multiline')}),
  ...(ps||py?{try:ddType('Try / catch / finally','Handle failures and optionally add cleanup.',{error:ddName('Exception variable','error')},{body:ddSlot('Try',statements),catch:ddSlot('Catch',statements),finally:ddSlot('Finally (optional)',statements)})}:{})
 };
 const profile={id:language,title:(ps?'PowerShell':py?'Python':'Bash')+' script editor',description:'Build nested functions, loops and conditions. Add commands with individual arguments; the editor supplies quoting and block syntax.',filename:py?'script.py':ps?'script.ps1':'script.sh',types,root:ddSlot('Script steps',statements),check:'Generated code is not executed. Advanced expressions require your review. Validate with '+(py?'Python ast.parse.':ps?'the PowerShell parser.':'bash -n script.sh.')};
 const quote=py?JSON.stringify:ps?dkPS:dkQ;
 const scalar=v=>v.mode==='variable'?(py?ddIdent(v.value):ps?'$'+ddIdent(v.value):'"${'+ddIdent(v.value)+'}"'):v.mode==='expression'?(v.value.trim()||(()=>{throw Error('An expression is empty.');})()):quote(v.value);
 const condition=v=>{const name=ddIdent(v.left),left=py?name:ps?'$'+name:'"${'+name+'}"';if(v.operator==='is empty'||v.operator==='is not empty'){const empty=v.operator==='is empty';return py?left+(empty?' == ':' != ')+"''":ps?'[string]::IsNullOrEmpty('+left+')'+(empty?'':' -eq $false'):'[[ '+(empty?'-z ':'-n ')+left+' ]]';}const numeric=['greater than','less than'].includes(v.operator);if(numeric&&!/^-?\d+$/.test(v.right))throw Error('Numeric comparisons need a whole number.');const op=py?{'equals':'==','not equals':'!=','greater than':'>','less than':'<'}:ps?{'equals':'-eq','not equals':'-ne','greater than':'-gt','less than':'-lt'}:{'equals':'==','not equals':'!=','greater than':'-gt','less than':'-lt'};return (py||ps?'':'[[ ')+left+' '+op[v.operator]+' '+(numeric?v.right:quote(v.right))+(py||ps?'':' ]]');};
 function lines(nodes,inside=false){return nodes.map(n=>emit(n,inside)).join('\n');}
 function child(nodes){let text=lines(nodes,true);if(!nodes.some(n=>n.type!=='comment'&&!(n.type==='raw'&&!n.values.text.trim())))text+=(text?'\n':'')+(py?'pass':ps?'# Add steps here':':');return ddIndent(text);}
 function emit(n,inside){const v=n.values,s=n.slots;
  if(py&&typeof pyEmit==='function'){const result=pyEmit(n);if(result!==null)return result;}
  if(n.type==='comment')return v.text.split('\n').map(t=>'# '+t).join('\n');
  if(n.type==='raw')return v.text;
  if(n.type==='variable')return (ps?'$':'')+ddIdent(v.name)+(py||ps?' = ':'=')+scalar(v);
  if(n.type==='arrayVariable'){const items=v.items.split('\n').map(quote);return (ps?'$':'')+ddIdent(v.name)+(py?' = ['+items.join(', ')+']':ps?' = @('+items.join(', ')+')':'=('+items.join(' ')+')');}
  if(n.type==='print')return py?'print('+scalar(v)+')':ps?'Write-Output ('+scalar(v)+')':"printf '%s\\n' "+scalar(v);
  if(n.type==='command'){const args=s.args.map(a=>a.type==='parameter'?'-'+ddIdent(a.values.name)+(a.values.kind==='switch'?'':' '+scalar(a.values)):scalar(a.values));if(py)return 'subprocess.run(['+[JSON.stringify(v.program),...args.map(x=>'str('+x+')')].join(', ')+'], check=True)';return (ps?'& ':'')+quote(v.program)+(args.length?' '+args.join(' '):'');}
  if(n.type==='pipeline'){if(py)return s.commands.map((c,i)=>'_pipeline_result = '+emit(c,inside).replace(/, check=True\)$/,', check=True, text=True, capture_output=True'+(i?', input=_pipeline_result.stdout':'')+')')).join('\n')+'\nprint(_pipeline_result.stdout, end="")';return s.commands.map(c=>emit(c,inside)).join(' | ');}
  if(n.type==='if'){const test=condition(v);return py?'if '+test+':\n'+child(s.then)+(s.else.length?'\nelse:\n'+child(s.else):''):ps?'if ('+test+') {\n'+child(s.then)+'\n}'+(s.else.length?' else {\n'+child(s.else)+'\n}':''):'if '+test+'; then\n'+child(s.then)+(s.else.length?'\nelse\n'+child(s.else):'')+'\nfi';}
  if(n.type==='while'){const test=condition(v);return py?'while '+test+':\n'+child(s.body):ps?'while ('+test+') {\n'+child(s.body)+'\n}':'while '+test+'; do\n'+child(s.body)+'\ndone';}
  if(n.type==='foreach'){const name=ddIdent(v.name),items=v.source==='array variable'?(py?ddIdent(v.items):ps?'$'+ddIdent(v.items):'"${'+ddIdent(v.items)+'[@]}"'):v.items.split('\n').map(quote).join(py||ps?', ':' ');return py?'for '+name+' in '+(v.source==='array variable'?items:'['+items+']')+':\n'+child(s.body):ps?'foreach ($'+name+' in '+(v.source==='array variable'?items:'@('+items+')')+') {\n'+child(s.body)+'\n}':'for '+name+' in '+items+'; do\n'+child(s.body)+'\ndone';}
  if(n.type==='function')return py?'def '+ddIdent(v.name)+'():\n'+child(s.body):ps?'function '+ddIdent(v.name)+' {\n'+child(s.body)+'\n}':ddIdent(v.name)+'() {\n'+child(s.body)+'\n}';
  if(n.type==='return'){if(!inside)throw Error('Place return inside a function.');return 'return '+(py?scalar(v):v.value);}
  if(n.type==='try')return py?'try:\n'+child(s.body)+'\nexcept Exception as '+ddIdent(v.error)+':\n'+child(s.catch)+(s.finally.length?'\nfinally:\n'+child(s.finally):''):'try {\n'+child(s.body)+'\n} catch {\n  $'+ddIdent(v.error)+' = $_\n'+child(s.catch)+'\n}'+(s.finally.length?' finally {\n'+child(s.finally)+'\n}':'');
  throw Error('Unsupported script block.');
 }
 profile.generate=nodes=>(py?'#!/usr/bin/env python3\nimport subprocess\n\n':ps?"# PowerShell script\n$ErrorActionPreference = 'Stop'\n\n":'#!/usr/bin/env bash\nset -euo pipefail\n\n')+lines(nodes)+'\n';
 profile.seed=p=>[ddNode(p,'variable',{name:'message',value:'Hello from DevKit'}),ddNode(p,'if',{left:'message',operator:'is not empty'},{then:[ddNode(p,'print',{mode:'variable',value:'message'})]})];DD_PROFILES[language]=profile;
}

// HCL blocks contain recursively typed values or nested blocks.
{
 const values=[...DD_VALUE_TYPES,'expression'],attributes=[...values,'nested'],types=ddValueTypes(true);
 for(const [id,label,fields] of [
  ['terraform','Terraform settings',{}],['provider','Provider',{label:ddField('Provider name','aws')}],['variable','Input variable',{label:ddName('Variable name','region')}],['output','Output',{label:ddName('Output name','result')}],['locals','Local values',{}],
  ['resource','Resource',{kind:ddField('Resource type','aws_s3_bucket'),label:ddName('Local resource name','example')}],['data','Data source',{kind:ddField('Data source type','aws_caller_identity'),label:ddName('Local data name','current')}],['module','Module',{label:ddName('Module name','example')}],['nested','Nested block',{name:ddName('Block type','lifecycle'),labels:ddField('Labels, one per line (optional)','','multiline')}]
 ])types[id]=ddType(label,'Add typed arguments or nested blocks. Names and supported arguments depend on the provider.',fields,{body:ddSlot('Arguments & nested blocks',attributes)});
 const p={id:'terraform',title:'Terraform HCL editor',description:'Compose provider, variable, resource, data and module blocks. Choose literal values or explicit Terraform expressions.',filename:'main.tf',types,root:ddSlot('Configuration blocks',['terraform','provider','variable','locals','resource','data','module','output']),check:'Use terraform fmt, then terraform validate after initializing providers. Provider argument schemas are not bundled.'};
 const hvalue=n=>{if(n.type==='expression')return n.values.value;if(n.type==='text')return ddHCLText(n.values.value);if(n.type==='object'){unique(n.slots.items);return '{\n'+ddIndent(n.slots.items.map(x=>ddHCLText(x.values.key)+' = '+hvalue(x)).join('\n'))+'\n}';}if(n.type==='array')return '[\n'+ddIndent(n.slots.items.map(hvalue).join(',\n'))+'\n]';return JSON.stringify(ddValue(n));};
 function unique(nodes){const keys=new Set();for(const n of nodes.filter(x=>values.includes(x.type))){if(!n.values.key.trim())throw Error('Every argument needs a name.');if(keys.has(n.values.key))throw Error('Duplicate argument: '+n.values.key);keys.add(n.values.key);}}
 function block(n){const v=n.values;unique(n.slots.body);let name=n.type==='nested'?ddIdent(v.name):n.type;const labels=n.type==='nested'?v.labels.split('\n').filter(Boolean):[v.kind,v.label].filter(Boolean);name+=labels.length?' '+labels.map(ddHCLText).join(' '):'';return name+' {\n'+ddIndent(n.slots.body.map(x=>values.includes(x.type)?ddIdent(x.values.key)+' = '+hvalue(x):block(x)).join('\n'))+'\n}';}
 p.generate=nodes=>nodes.map(block).join('\n\n')+'\n';p.seed=p=>[ddNode(p,'variable',{label:'region'},{body:[ddNode(p,'expression',{key:'type',value:'string'}),ddNode(p,'text',{key:'default',value:'us-east-1'})]}),ddNode(p,'provider',{label:'aws'},{body:[ddNode(p,'expression',{key:'region',value:'var.region'})]})];DD_PROFILES.terraform=p;
}

// SQL clauses are emitted in grammatical order, independent of palette order.
{
 const filters=['compare','group','nullcheck','in'],types={
  select:ddType('SELECT query','Add columns, joins and filters. Clause order is automatic.',{table:ddField('From table','users'),alias:ddField('Table alias (optional)','','text',{required:false}),distinct:ddChoice('Rows','all',['all','distinct']),limit:ddField('Limit (optional)','','optionalInteger')},{cte:ddSlot('Common table expressions',['cte']),columns:ddSlot('Columns',['column','aggregate','sqlExpression'],1),joins:ddSlot('Joins',['join']),where:ddSlot('WHERE · all must match',filters),group:ddSlot('GROUP BY',['column']),having:ddSlot('HAVING · all must match',filters),order:ddSlot('ORDER BY',['sort'])}),
  cte:ddType('Named subquery (CTE)','Build a SELECT query that the outer query can refer to by name.',{name:ddName('CTE name','filtered')},{query:ddSlot('Subquery',['select'],1,1)}),
  column:ddType('Column','A qualified column such as users.name; identifiers are quoted.',{name:ddField('Column','name'),alias:ddField('Alias (optional)','','text',{required:false})}),
  aggregate:ddType('Aggregate','Choose a function rather than writing its parentheses.',{function:ddChoice('Function','COUNT',['COUNT','SUM','AVG','MIN','MAX']),name:ddField('Column','*'),alias:ddField('Alias (optional)','total','text',{required:false})}),
  sqlExpression:ddType('Advanced SQL expression','Emitted without quoting; review SQL syntax yourself.',{text:ddField('SQL expression','COALESCE(name, \'Unknown\')','expression'),alias:ddField('Alias (optional)','','text',{required:false})}),
  join:ddType('Join a table','Match columns from two tables.',{kind:ddChoice('Join type','LEFT',['INNER','LEFT','RIGHT','FULL']),table:ddField('Joined table','orders'),alias:ddField('Alias (optional)','','text',{required:false}),left:ddField('Left column','users.id'),right:ddField('Right column','orders.user_id')}),
  compare:ddType('Compare values','Choose a column or aggregate, operator and typed comparison value.',{leftKind:ddChoice('Left-hand value','column',['column','COUNT','SUM','AVG','MIN','MAX']),column:ddField('Column','active'),operator:ddChoice('Operator','=', ['=','<>','>','>=','<','<=','LIKE']),kind:ddChoice('Right-hand value kind','text',['text','number','boolean','column','expression']),value:ddField('Compare with','yes')}),
  group:ddType('Nested filter group','Parentheses are inserted around this group.',{join:ddChoice('Match','ANY (OR)',['ALL (AND)','ANY (OR)'])},{conditions:ddSlot('Conditions',filters,1)}),
  nullcheck:ddType('Is null / not null','Use the SQL null predicate.',{column:ddField('Column','deleted_at'),operator:ddChoice('Test','IS NULL',['IS NULL','IS NOT NULL'])}),
  in:ddType('One of these values','Literal text values, one per line.',{column:ddField('Column','status'),values:ddField('Allowed values','active\npending','multiline')}),
  sort:ddType('Sort column','Choose the direction.',{column:ddField('Column','name'),direction:ddChoice('Direction','ASC',['ASC','DESC'])}),
  insert:ddType('INSERT rows','Define the column order, then add one or more rows of typed values.',{table:ddField('Table','users'),columns:ddField('Column names, one per line','name\nactive','multiline')},{rows:ddSlot('Rows',['row'],1)}),
  row:ddType('Row of values','Add a value for each column, in the same order.',{},{values:ddSlot('Values',['sqlValue'],1)}),
  sqlValue:ddType('Typed SQL value','Text is quoted; numbers, booleans and null are emitted with their proper syntax.',{kind:ddChoice('Value kind','text',['text','number','boolean','null','expression']),value:ddField('Value','example','multiline')}),
  update:ddType('UPDATE matching rows','Set column values and choose the rows to update.',{table:ddField('Table','users'),scope:ddChoice('Rows to change','matching rows',['matching rows','all rows'])},{assignments:ddSlot('Set column values',['assignment'],1),where:ddSlot('WHERE · all must match',filters)}),
  assignment:ddType('Set a column','Choose a value type; escaping is automatic for literals.',{column:ddField('Column','name'),kind:ddChoice('Value kind','text',['text','number','boolean','null','expression']),value:ddField('Value','example','multiline')}),
  delete:ddType('DELETE matching rows','Choose rows with structured filters.',{table:ddField('Table','users'),scope:ddChoice('Rows to change','matching rows',['matching rows','all rows'])},{where:ddSlot('WHERE · all must match',filters)}),
  create:ddType('CREATE TABLE','Build column definitions without remembering commas or parentheses.',{table:ddField('Table','example')},{columns:ddSlot('Column definitions',['definition'],1)}),
  definition:ddType('Table column','Choose a data type and basic constraints.',{name:ddName('Column name','id'),type:ddChoice('Type','INTEGER',['INTEGER','BIGINT','TEXT','BOOLEAN','DATE','TIMESTAMP','NUMERIC']),nullable:ddChoice('Nulls','NOT NULL',['NOT NULL','nullable']),primary:ddChoice('Primary key','no',['no','yes'])})
 };
 const p={id:'sql',title:'SQL query editor',description:'Build SELECT, INSERT, UPDATE, DELETE and CREATE TABLE statements with nested filters, joins and CTEs. PostgreSQL-style quoting and clause order are automatic.',filename:'query.sql',types,root:ddSlot('Statements',['select','insert','update','delete','create'],1),check:'Review against your database schema. This editor uses PostgreSQL-style SQL; it does not connect to a database.'};
 const alias=v=>v.alias?' AS '+ddSQLName(v.alias):'';
 const column=n=>n.type==='aggregate'?n.values.function+'('+ddSQLName(n.values.name)+')'+alias(n.values):n.type==='sqlExpression'?n.values.text+alias(n.values):ddSQLName(n.values.name)+alias(n.values);
 function literal(v){if(v.kind==='text')return ddSQLText(v.value);if(v.kind==='null')return 'NULL';if(v.kind==='column')return ddSQLName(v.value);if(v.kind==='number'&&!/^-?\d+(?:\.\d+)?$/.test(v.value))throw Error('A numeric value needs a number.');if(v.kind==='boolean'){if(!['true','false'].includes(v.value.toLowerCase()))throw Error('A boolean value needs true or false.');return v.value.toUpperCase();}if(v.kind==='expression'&&!v.value.trim())throw Error('An SQL expression is empty.');return v.value;}
 function filter(n){const v=n.values;if(n.type==='group')return '('+n.slots.conditions.map(filter).join(v.join==='ALL (AND)'?' AND ':' OR ')+')';if(n.type==='nullcheck')return ddSQLName(v.column)+' '+v.operator;if(n.type==='in')return ddSQLName(v.column)+' IN ('+v.values.split('\n').map(ddSQLText).join(', ')+')';return (v.leftKind==='column'?ddSQLName(v.column):v.leftKind+'('+ddSQLName(v.column)+')')+' '+v.operator+' '+literal(v);}
 function query(n){const v=n.values,s=n.slots;
  if(n.type==='insert'){const columns=v.columns.split('\n');if(columns.some(c=>!c.trim())||new Set(columns).size!==columns.length)throw Error('INSERT needs unique nonempty column names.');if(s.rows.some(r=>r.slots.values.length!==columns.length))throw Error('Each INSERT row needs exactly '+columns.length+' values.');return 'INSERT INTO '+ddSQLName(v.table)+' ('+columns.map(ddSQLName).join(', ')+')\nVALUES\n'+s.rows.map(r=>'  ('+r.slots.values.map(x=>literal(x.values)).join(', ')+')').join(',\n');}
  if(n.type==='update'||n.type==='delete'){if(v.scope==='matching rows'&&!s.where.length)throw Error('Add a filter or explicitly choose all rows.');if(v.scope==='all rows'&&s.where.length)throw Error('Remove filters or choose matching rows.');if(n.type==='update'&&new Set(s.assignments.map(a=>a.values.column)).size!==s.assignments.length)throw Error('A column can only be assigned once.');return (n.type==='delete'?'DELETE FROM '+ddSQLName(v.table):'UPDATE '+ddSQLName(v.table)+'\nSET '+s.assignments.map(a=>ddSQLName(a.values.column)+' = '+literal(a.values)).join(',\n    '))+(s.where.length?'\nWHERE '+s.where.map(filter).join(' AND '):'');}
  if(n.type==='create'){if(new Set(s.columns.map(c=>c.values.name)).size!==s.columns.length)throw Error('Column names must be unique.');if(s.columns.filter(c=>c.values.primary==='yes').length>1)throw Error('Use one primary key column; composite keys need an advanced SQL example.');return 'CREATE TABLE '+ddSQLName(v.table)+' (\n'+ddIndent(s.columns.map(c=>{const x=c.values;return ddSQLName(x.name)+' '+x.type+(x.nullable==='NOT NULL'?' NOT NULL':'')+(x.primary==='yes'?' PRIMARY KEY':'');}).join(',\n'))+'\n)';}
  return (s.cte.length?'WITH '+s.cte.map(c=>ddSQLName(c.values.name)+' AS (\n'+ddIndent(query(c.slots.query[0]))+'\n)').join(',\n')+'\n':'')+'SELECT '+(v.distinct==='distinct'?'DISTINCT ':'')+s.columns.map(column).join(', ')+'\nFROM '+ddSQLName(v.table)+alias(v)+s.joins.map(j=>{const x=j.values;return '\n'+x.kind+' JOIN '+ddSQLName(x.table)+alias(x)+' ON '+ddSQLName(x.left)+' = '+ddSQLName(x.right);}).join('')+(s.where.length?'\nWHERE '+s.where.map(filter).join(' AND '):'')+(s.group.length?'\nGROUP BY '+s.group.map(c=>ddSQLName(c.values.name)).join(', '):'')+(s.having.length?'\nHAVING '+s.having.map(filter).join(' AND '):'')+(s.order.length?'\nORDER BY '+s.order.map(c=>ddSQLName(c.values.column)+' '+c.values.direction).join(', '):'')+(v.limit!==''?'\nLIMIT '+v.limit:'');
 }
 p.generate=nodes=>nodes.map(query).join(';\n\n')+';\n';p.seed=p=>[ddNode(p,'select',{}, {columns:[ddNode(p,'column',{name:'id'}),ddNode(p,'column',{name:'name'})]})];DD_PROFILES.sql=p;
}

// Dockerfile instruction ordering is explicit and repeatable.
{
 const types={from:ddType('FROM · build stage','Start an image or another build stage.',{image:ddField('Image','python:3.12-slim'),alias:ddField('Stage name (optional)','','text',{required:false})}),workdir:ddType('WORKDIR','Set the working directory.',{path:ddField('Container directory','/app')}),copy:ddType('COPY','JSON-form paths are escaped automatically.',{source:ddField('Source','.'),destination:ddField('Destination','/app'),from:ddField('From stage (optional)','','text',{required:false})}),run:ddType('RUN','Executable plus literal arguments, without shell parsing.',{program:ddField('Executable','python')},{args:ddSlot('Arguments',['arg'])}),arg:ddType('Argument','One literal argument.',{value:ddField('Value','--version')}),env:ddType('ENV','Define a literal environment value.',{name:ddName('Variable name','APP_ENV'),value:ddField('Value','production')}),expose:ddType('EXPOSE','Document a listening port; publishing is a separate action.',{port:ddField('Port','8080','port')}),cmd:ddType('CMD','Default executable and arguments.',{program:ddField('Executable','python')},{args:ddSlot('Arguments',['arg'])}),entrypoint:ddType('ENTRYPOINT','Container executable and arguments.',{program:ddField('Executable','python')},{args:ddSlot('Arguments',['arg'])}),user:ddType('USER','Set the runtime user.',{name:ddField('User','1000')}),comment:ddType('Comment','Describe the stage.',{text:ddField('Comment','Application image')})};
 const p={id:'dockerfile',title:'Dockerfile editor',description:'Build repeated instructions and multiple stages. JSON-form command arguments avoid manual escaping.',filename:'Dockerfile',types,root:ddSlot('Instructions',Object.keys(types).filter(k=>k!=='arg'),1),check:'Use docker build --check . with a supported Docker version.'};
 p.generate=nodes=>{if(nodes.find(n=>n.type!=='comment')?.type!=='from')throw Error('Start the Dockerfile with a FROM stage.');return nodes.map(n=>{const v=n.values;if(['run','cmd','entrypoint'].includes(n.type))return n.type.toUpperCase()+' '+JSON.stringify([v.program,...n.slots.args.map(a=>a.values.value)]);if(n.type==='from')return 'FROM '+v.image+(v.alias?' AS '+v.alias:'');if(n.type==='copy')return 'COPY '+(v.from?'--from='+v.from+' ':'')+JSON.stringify([v.source,v.destination]);if(n.type==='env')return 'ENV '+ddIdent(v.name)+'='+JSON.stringify(v.value).replace(/\$/g,'\\$');if(n.type==='comment')return '# '+v.text;return n.type.toUpperCase()+' '+(v.path||v.port||v.name);}).join('\n')+'\n';};p.seed=p=>[ddNode(p,'from'),ddNode(p,'workdir'),ddNode(p,'copy'),ddNode(p,'cmd',{}, {args:[ddNode(p,'arg',{value:'/app/main.py'})]})];DD_PROFILES.dockerfile=p;
}

function ddValidate(profile,nodes){const errors=[],seen=new Set();let count=0;
 function walk(list,slot,path,depth=0,inFunction=false){if(depth>20){errors.push('Nesting is limited to 20 levels.');return;}if(!Array.isArray(list)){errors.push(path+': invalid block list.');return;}if(list.length<slot.min||list.length>slot.max)errors.push(path+': needs '+slot.min+(slot.max<Infinity?'–'+slot.max:' or more')+' blocks.');for(const n of list){if(++count>1500){errors.push('Document is limited to 1,500 blocks.');return;}const def=profile.types[n?.type];if(!def||!slot.accept.includes(n.type)||!n.values||!n.slots){errors.push(path+': incompatible block.');continue;}if(typeof n.id!=='string'||seen.has(n.id)){errors.push('Duplicate or missing block identity.');continue;}seen.add(n.id);const here=path+' / '+def.label;if(n.type==='return'&&!inFunction)errors.push(here+': place inside a function.');for(const [key,f] of Object.entries(def.fields)){const v=n.values[key];let message='';if(typeof v!=='string')message='Enter a value.';else if(f.required===false&&!v.trim())continue;else if(f.type==='name'&&!/^[A-Za-z_][A-Za-z0-9_]*$/.test(v))message='Use letters, numbers and underscores.';else if(['integer','optionalInteger','port'].includes(f.type)&&!(f.type==='optionalInteger'&&v==='')&&(!/^\d+$/.test(v)||!Number.isSafeInteger(+v)||(f.type==='port'&&(+v<1||+v>65535))))message='Enter a valid whole number.';else if(f.type==='decimal'&&(!/^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$/.test(v)||!Number.isFinite(+v)))message='Enter a finite number.';else if(f.type==='choice'&&!f.choices.includes(v))message='Choose an available option.';else if(f.type!=='multiline'&&/[\r\n\0]/.test(v))message='Use one line.';else if(!v.trim()&&!['multiline','optionalInteger'].includes(f.type)&&f.required!==false)message='Fill in this value.';if(message)errors.push(here+' / '+f.label+': '+message);}
 if(profile.id==='python')for(const key of ['name','left','error'])if(n.values[key]&&['False','None','True','and','as','assert','async','await','break','class','continue','def','del','elif','else','except','finally','for','from','global','if','import','in','is','lambda','nonlocal','not','or','pass','raise','return','try','while','with','yield'].includes(n.values[key]))errors.push(here+': '+n.values[key]+' is a Python keyword.');
 for(const [key,child] of Object.entries(def.slots))walk(n.slots[key],child,here+' / '+child.label,depth+1,inFunction||['function','py_function'].includes(n.type));}}
 walk(nodes,profile.root,'Document');return errors;
}
function ddGenerate(profile,nodes){const errors=ddValidate(profile,nodes);let text='';if(!errors.length)try{text=profile.generate(nodes);}catch(e){errors.push(e.message);}return {text,errors,filename:profile.filename};}
