/* One recursive editor for scripts, HCL, SQL and typed documents. */
let ddState=null,ddHistory=[],ddFuture=[],ddCollapsed=new Set(),ddDrag=null,ddInputSnapshot=false;
const ddProfile=()=>DD_PROFILES[ddState.profile];
function ddFind(id,list=ddState.blocks,parent=null,slot='root'){for(let index=0;index<list.length;index++){const node=list[index];if(node.id===id)return {node,list,index,parent,slot};for(const [key,children] of Object.entries(node.slots)){const found=ddFind(id,children,node,key);if(found)return found;}}return null;}
function ddLane(parent,slot){return parent?ddFind(parent).node.slots[slot]:ddState.blocks;}
function ddLaneDef(parent,slot){const def=parent?ddProfile().types[ddFind(parent).node.type].slots[slot]:ddProfile().root;let insideFunction=false,cursor=parent?ddFind(parent):null;while(cursor){if(['function','py_function'].includes(cursor.node.type))insideFunction=true;cursor=cursor.parent?ddFind(cursor.parent.id):null;}return insideFunction?def:{...def,accept:def.accept.filter(t=>t!=='return')};}
function ddSave(){try{dkDrafts[ddState.id]=dkClone(ddState);localStorage.setItem(DK_STORAGE,JSON.stringify(dkDrafts));document.getElementById('dd-save').textContent='Draft saved in this browser';}catch(e){document.getElementById('dd-save').textContent='Storage unavailable: download your work';}}
function ddRemember(){ddHistory.push(dkClone(ddState));if(ddHistory.length>80)ddHistory.shift();ddFuture=[];}
function ddChange(fn){ddRemember();fn();ddInputSnapshot=false;ddSave();ddRender();}
function ddFreshIds(n){n.id=ddId();for(const nodes of Object.values(n.slots))nodes.forEach(ddFreshIds);return n;}
function ddOpen(profileId,sheet,seed,filename,draftKey='default'){const p=DD_PROFILES[profileId];if(!p)return;dkStopTest();dkShow();ddHistory=[];ddFuture=[];ddCollapsed.clear();const id='deep:'+sheet+':'+profileId+':'+draftKey,saved=dkDrafts[id];
 // Keep invalid field values editable; reject malformed saved trees before rendering.
 function shape(nodes,depth=0){return depth<22&&Array.isArray(nodes)&&nodes.every(n=>n&&p.types[n.type]&&anMap(n.values)&&anMap(n.slots)&&Object.keys(p.types[n.type].slots).every(k=>shape(n.slots[k],depth+1)));}
 ddState=saved&&saved.profile===profileId&&shape(saved.blocks)?dkClone(saved):{id,sheet,profile:profileId,filename:filename||p.filename,...dxInitial(p,seed)};ddRender();ddSave();
}
function ddSeedFromRecipe(id){const r=DK_RECIPES[id],p=DD_PROFILES[/\.json$/.test(r.filename)?'json':'yaml'];const blocks=r.parts.map(part=>({key:part.key,values:dkPartValues(part)}));const text=r.generate(Object.fromEntries(blocks.map(b=>[b.key,b.values])),blocks,{shell:'posix'});const docs=p.id==='json'?[JSON.parse(text)]:jsyaml.loadAll(text);return {profile:p.id,nodes:docs.map(d=>ddFromValue(p,d)),filename:r.filename};}
const DD_SEEDS={docker:['docker:compose'],k8s:['k8s:deployment','k8s:configmap'],npm:['npm:package'],terraform:[],ansible:[]};
function ddChoices(sheet){const primary=({bash:['bash'],powershell:['powershell'],python:['python'],terraform:['terraform'],sql:['sql'],docker:['dockerfile']})[sheet]||[];return [...primary,...(!['bash','powershell','python','sql'].includes(sheet)?['bash','powershell']:[]),'yaml','json'].filter((v,i,a)=>a.indexOf(v)===i);}
const ddOldHome=dkHome;
dkHome=function(sheet){ddOldHome(sheet);const body=document.querySelector('#dk-root .dk-home');if(!body)return;const section=dkEl('section','dd-launch');section.append(dkEl('span','dk-eyebrow','BUILD A WHOLE FILE'),dkEl('h3','','Deep block editors'),dkEl('p','dk-help','Nested, repeatable blocks with context-aware choices. Start a document or continue your saved draft.'));
 const grid=dkEl('div','dd-launch-grid');for(const id of ddChoices(sheet)){const p=DD_PROFILES[id],button=dkBtn(p.title+' →',()=>ddOpen(id,sheet));button.dataset.deep=id;grid.append(button);}section.append(grid);
 const seeds=(DD_SEEDS[sheet]||[]).filter(id=>DK_RECIPES[id]);if(seeds.length){const label=dkEl('p','dk-help','Editable starting files, each with its own saved draft:');section.append(label);for(const id of seeds){const button=dkBtn('Start from '+DK_RECIPES[id].title,()=>{const seed=ddSeedFromRecipe(id);ddOpen(seed.profile,sheet,seed.nodes,seed.filename,id);});section.append(button);}}
 body.prepend(section);
};
function ddMove(id,parent,slot,index){const source=ddFind(id);if(!source)return false;const target=parent?ddFind(parent):null;if(parent&&!target)return false;let cursor=target;while(cursor){if(cursor.node.id===id)return false;cursor=cursor.parent?ddFind(cursor.parent.id):null;}const dest=ddLane(parent,slot),def=ddLaneDef(parent,slot);if(!def.accept.includes(source.node.type)||(dest!==source.list&&dest.length>=def.max))return false;if(source.list===dest&&source.index<index)index--;if(source.list===dest&&source.index===index)return false;ddChange(()=>{source.list.splice(source.index,1);dest.splice(index,0,source.node);});return true;}
function ddNewNode(type){const p=ddProfile(),node=ddNode(p,type);for(const [key,slot] of Object.entries(p.types[type].slots))for(let i=0;i<slot.min;i++)node.slots[key].push(ddNewNode(slot.accept[0]));return node;}
function ddRender(){const editorScroll=document.querySelector('.dd-editor')?.scrollTop||0,outputScroll=document.querySelector('.dk-output')?.scrollTop||0;const p=ddProfile(),root=document.getElementById('dk-root');root.replaceChildren();const header=dkEl('header','dk-header'),title=dkEl('div');title.append(dkEl('span','dk-eyebrow',SHEETS[ddState.sheet].name.toUpperCase()+' / DEEP BLOCK EDITOR'),dkEl('h2','',p.title),dkEl('p','dk-help',p.description));header.append(title,dkBtn('Close ✕',dkClose));root.append(header);
 const bar=dkEl('div','dk-toolbar');bar.append(dkBtn('← Workbench',()=>dkHome(ddState.sheet)));const save=dkEl('span','dk-muted','Draft saved in this browser');save.id='dd-save';bar.append(save);
 const undo=dkBtn('Undo',()=>{if(!ddHistory.length)return;ddFuture.push(dkClone(ddState));ddState=ddHistory.pop();ddRender();ddSave();});undo.id='dd-undo';undo.disabled=!ddHistory.length;const redo=dkBtn('Redo',()=>{if(!ddFuture.length)return;ddHistory.push(dkClone(ddState));ddState=ddFuture.pop();ddRender();ddSave();});redo.id='dd-redo';redo.disabled=!ddFuture.length;bar.append(undo,redo,dkBtn('Collapse all',()=>{function visit(nodes){nodes.forEach(n=>{ddCollapsed.add(n.id);Object.values(n.slots).forEach(visit);});}visit(ddState.blocks);ddRender();}),dkBtn('Expand all',()=>{ddCollapsed.clear();ddRender();}),dkBtn('New blank file',()=>ddChange(()=>{Object.assign(ddState,dxInitial(p));delete ddState.sxError;delete ddState.pyError;})),dkBtn('Load starter',()=>ddChange(()=>{ddState.blocks=p.seed(p);ddState.filename=p.filename;})));root.append(bar);
 const tabs=dkEl('div','dk-mobile-tabs');tabs.append(dkBtn('Build',()=>root.classList.remove('dk-preview-only')),dkBtn('Preview',()=>root.classList.add('dk-preview-only')));root.append(tabs);
 const layout=dkEl('div','dk-layout'),editor=dkEl('section','dk-editor dd-editor'),output=dkEl('section','dk-output');layout.append(editor,output);root.append(layout);
 const tip=dkEl('div','dd-tip','1. Add a block  →  2. Fill its fields  →  3. Add steps inside it. Drag a handle to a compatible section, or use ↑ / ↓. Empty sections show what can go there.');editor.append(tip);
 if(['yaml','json'].includes(p.id)){const row=dkEl('div','dd-import');const file=dkEl('input','dk-input');file.type='file';file.accept='.json,.yaml,.yml';file.setAttribute('aria-label','Import JSON or YAML file');const note=dkEl('small','dk-help','Import structured data to edit it as blocks. Comments and original styling are not preserved.');file.onchange=async()=>{try{const f=file.files[0];if(!f)return;if(f.size>1000000)throw Error('Use a document under 1 MB.');const text=await f.text(),values=/\.json$/i.test(f.name)?[JSON.parse(text)]:jsyaml.loadAll(text,{schema:jsyaml.JSON_SCHEMA});if(p.id==='json'&&values.length!==1)throw Error('JSON needs exactly one document.');let count=0;const active=new Set();function check(v,depth=0){if(++count>1500||depth>20)throw Error('Import is too large or deeply nested.');if(v&&typeof v==='object'){if(active.has(v))throw Error('Cyclic YAML aliases cannot be edited as a tree.');active.add(v);Object.values(v).forEach(x=>check(x,depth+1));active.delete(v);}}values.forEach(v=>check(v));const blocks=values.map(v=>ddFromValue(p,v));ddChange(()=>{ddState.blocks=blocks;ddState.filename=f.name.replace(/\.(json|ya?ml)$/i,p.id==='json'?'.json':'.yml');});}catch(e){note.textContent=e.message;}};row.append(file,note);editor.append(row);}
 ddRenderLane(editor,null,'root');
 const filelabel=dkEl('label','dk-field','Output filename'),name=dkEl('input','dk-input');name.value=ddState.filename;name.setAttribute('aria-label','Output filename');name.onchange=()=>ddChange(()=>ddState.filename=name.value);filelabel.append(name);output.append(filelabel);
 const preview=dkEl('textarea');preview.id='dd-preview';preview.readOnly=true;preview.spellcheck=false;preview.setAttribute('aria-label','Generated file');output.append(preview);const status=dkEl('div','dk-status');status.id='dd-status';status.setAttribute('role','status');output.append(status);
 const actions=dkEl('div','dk-actions');const copy=dkBtn('Copy file',async()=>{const result=ddOutput();if(result.errors.length)return;try{await navigator.clipboard.writeText(result.text);document.getElementById('dd-notice').textContent='Copied with formatting preserved.';}catch(e){preview.focus();preview.select();document.getElementById('dd-notice').textContent='Press Ctrl+C / Cmd+C to copy the selected file.';}},'dk-btn primary');copy.id='dd-copy';const download=dkBtn('Download file',()=>{const result=ddOutput();if(!result.errors.length)dkDownloadText(result.text,ddState.filename);});download.id='dd-download';actions.append(copy,download);output.append(actions);const notice=dkEl('p','dk-help');notice.id='dd-notice';output.append(notice,dkEl('p','dk-help',p.check));ddRefresh();editor.scrollTop=editorScroll;output.scrollTop=outputScroll;
}
function ddRenderLane(host,parent,slot){const nodes=ddLane(parent,slot),def=ddLaneDef(parent,slot),lane=dkEl('section','dd-lane');lane.dataset.parent=parent||'';lane.dataset.slot=slot;lane.setAttribute('aria-label',def.label);lane.append(dkEl('h4','dd-lane-title',def.label+' · '+nodes.length));host.append(lane);
 nodes.forEach((n,index)=>{const def=ddProfile().types[n.type],card=dkEl('article','dd-node');card.dataset.node=n.id;const head=dkEl('div','dd-node-head');const handle=dkBtn('⠿',()=>{},'dk-grip');handle.setAttribute('aria-label','Drag '+def.label);handle.title='Drag to a compatible section; arrow buttons also reorder.';handle.onpointerdown=e=>ddStartDrag(e,n.id,handle);head.append(handle);
 const summary=n.values.name||n.values.key||n.values.label||n.values.table||n.values.program||n.values.function||'';const toggle=dkBtn((ddCollapsed.has(n.id)?'▸ ':'▾ ')+def.label+(summary?' · '+summary:''),()=>{ddCollapsed.has(n.id)?ddCollapsed.delete(n.id):ddCollapsed.add(n.id);ddRender();},'dd-node-title');toggle.setAttribute('aria-expanded',String(!ddCollapsed.has(n.id)));head.append(toggle);
 for(const [label,delta] of [['↑',-1],['↓',1]]){const b=dkBtn(label,()=>ddMove(n.id,parent,slot,index+(delta<0?-1:2)),'dk-small');b.disabled=index+delta<0||index+delta>=nodes.length;b.setAttribute('aria-label','Move '+def.label+(delta<0?' up':' down'));head.append(b);}const duplicate=dkBtn('⧉',()=>ddChange(()=>nodes.splice(index+1,0,ddFreshIds(dkClone(n)))),'dk-small');duplicate.disabled=nodes.length>=ddLaneDef(parent,slot).max;duplicate.setAttribute('aria-label','Duplicate '+def.label);const remove=dkBtn('×',()=>ddChange(()=>nodes.splice(index,1)),'dk-small');remove.setAttribute('aria-label','Remove '+def.label);head.append(duplicate,remove);card.append(head);lane.append(card);
 if(ddCollapsed.has(n.id))return;const content=dkEl('div','dd-node-content');content.append(dkEl('p','dk-help',def.hint));const fields=dkEl('div','dd-fields');for(const [key,field] of Object.entries(def.fields)){
  if(key==='key'&&(['yaml','json'].includes(ddProfile().id))&&(!parent||ddFind(parent).node.type==='array'))continue;
  const label=dkEl('label','dk-field');label.append(dkEl('span','',field.label));let input;
  if(field.type==='choice'){input=dkEl('select','dk-input');for(const choice of field.choices){const o=dkEl('option','',choice);o.value=choice;input.append(o);}}
  else if(field.type==='multiline'){input=dkEl('textarea','dk-input');input.rows=3;}
  else input=dkEl('input','dk-input');input.value=n.values[key];input.setAttribute('aria-label',field.label);input.dataset.field=key;input.onfocus=()=>ddInputSnapshot=false;input.oninput=()=>{if(!ddInputSnapshot){ddRemember();ddInputSnapshot=true;}n.values[key]=input.value;ddSave();ddRefresh();};input.onchange=()=>{ddInputSnapshot=false;};label.append(input);
  if(ddProfile().id==='terraform'&&n.type==='expression'&&key==='value'){const choices=ddState.blocks.filter(x=>x.type==='variable').map(x=>['Input: '+x.values.label,'var.'+x.values.label]);if(n.values.key==='type')choices.unshift(...['string','number','bool','list(string)','map(string)'].map(v=>['Type: '+v,v]));if(choices.length){const picker=dkEl('select','dk-input');picker.setAttribute('aria-label','Insert Terraform reference or type');const placeholder=dkEl('option','','Choose a reference or type…');placeholder.value='';picker.append(placeholder);for(const [title,value] of choices){const o=dkEl('option','',title);o.value=value;picker.append(o);}picker.onchange=()=>{if(picker.value)ddChange(()=>n.values[key]=picker.value);};label.append(picker);}}
  fields.append(label);
 }content.append(fields);for(const key of Object.keys(def.slots))ddRenderLane(content,n.id,key);card.append(content);
 });
 const suggestions=ddSuggestions(parent,slot);if(suggestions.length){const row=dkEl('div','dd-suggestions');row.append(dkEl('small','','Suggested next pieces'));for(const suggestion of suggestions){const b=dkBtn('+ '+suggestion.label,()=>ddChange(()=>nodes.push(suggestion.make())));b.title=suggestion.hint||'Add this editable structure';row.append(b);}lane.append(row);}
 const add=dkEl('div','dd-add');const select=dkEl('select','dk-input');select.setAttribute('aria-label','Next block in '+def.label);for(const type of def.accept){const option=dkEl('option','',ddProfile().types[type].label);option.value=type;select.append(option);}const hint=dkEl('p','dk-help');const update=()=>hint.textContent=ddProfile().types[select.value].hint;select.onchange=update;update();const button=dkBtn('+ Add block',()=>ddChange(()=>nodes.push(ddNewNode(select.value))),'dk-btn primary');button.disabled=nodes.length>=def.max;add.append(select,button);lane.append(add,hint);if(nodes.length>=def.max)hint.textContent='This section holds '+def.max+' block'+(def.max===1?'':'s')+'. Edit, replace or remove it above.';
}
function ddOutput(){const result=ddGenerate(ddProfile(),ddState.blocks);if(!ddState.filename.trim()||/[\\/:*?"<>|\r\n]/.test(ddState.filename))result.errors.push('Choose a filename without directory separators or reserved characters.');return result;}
function ddRefresh(){const result=ddOutput();document.getElementById('dd-preview').value=result.text||'# Add or complete blocks to generate the file.';const status=document.getElementById('dd-status');status.replaceChildren();status.className='dk-status '+(result.errors.length?'incomplete':'ready');status.append(dkEl('strong','',result.errors.length?'Keep building':'Ready to copy'));result.errors.slice(0,5).forEach(e=>status.append(dkEl('p','',e)));document.getElementById('dd-copy').disabled=!!result.errors.length;document.getElementById('dd-download').disabled=!!result.errors.length;document.getElementById('dd-undo').disabled=!ddHistory.length;document.getElementById('dd-redo').disabled=!ddFuture.length;}
function ddStartDrag(event,id,handle){if(event.button!==0)return;event.preventDefault();const start={x:event.clientX,y:event.clientY},pointer=event.pointerId;let target=null,moved=false;handle.setPointerCapture(pointer);
 const clear=()=>document.querySelectorAll('.dd-drop-before,.dd-drop-after,.dd-drop-inside').forEach(e=>e.classList.remove('dd-drop-before','dd-drop-after','dd-drop-inside'));
 function move(e){if(Math.hypot(e.clientX-start.x,e.clientY-start.y)<5&&!moved)return;moved=true;clear();const hit=document.elementFromPoint(e.clientX,e.clientY),lane=hit?.closest('.dd-lane');target=null;if(!lane)return;const parent=lane.dataset.parent||null,slot=lane.dataset.slot,source=ddFind(id),dest=ddLane(parent,slot),def=ddLaneDef(parent,slot);let ancestor=parent?ddFind(parent):null;while(ancestor){if(ancestor.node.id===id)return;ancestor=ancestor.parent?ddFind(ancestor.parent.id):null;}if(!def.accept.includes(source.node.type)||(source.list!==dest&&dest.length>=def.max))return;
 const card=hit.closest('.dd-node');let index=dest.length;if(card&&card.parentElement===lane){const item=ddFind(card.dataset.node),rect=card.getBoundingClientRect(),after=e.clientY>rect.top+rect.height/2;index=item.index+(after?1:0);card.classList.add(after?'dd-drop-after':'dd-drop-before');}else lane.classList.add('dd-drop-inside');target={parent,slot,index};const scroller=lane.closest('.dd-editor'),r=scroller.getBoundingClientRect();if(e.clientY<r.top+55)scroller.scrollTop-=18;if(e.clientY>r.bottom-55)scroller.scrollTop+=18;
 }
 function end(e){clear();handle.removeEventListener('pointermove',move);handle.removeEventListener('pointerup',end);handle.removeEventListener('pointercancel',cancel);document.removeEventListener('keydown',key);if(handle.hasPointerCapture(pointer))handle.releasePointerCapture(pointer);if(e.type==='pointerup'&&moved&&target)ddMove(id,target.parent,target.slot,target.index);}
 function cancel(){end({type:'cancel'});}function key(e){if(e.key==='Escape')cancel();}handle.addEventListener('pointermove',move);handle.addEventListener('pointerup',end);handle.addEventListener('pointercancel',cancel);document.addEventListener('keydown',key);
}
