/* Context-aware completions and indentation for every editable code surface. */
const EA_CATALOG={
 bash:['echo ""','printf \'%s\\n\' ""','name=""','if [[ -n "${name}" ]]; then','for item in "${items[@]}"; do','while [[ -n "${value}" ]]; do','function name() {','return 0','set -euo pipefail'],
 powershell:['Write-Output ""','$name = ""','if ($name) {','foreach ($item in $items) {','while ($value) {','function Invoke-Task {','try {','return 0'],
 python:['import os','from pathlib import Path','def main():','if condition:','for item in items:','while condition:','try:','with open("path") as handle:','return None','print("")'],
 terraform:['terraform {','required_providers {','provider "" {','variable "" {','locals {','resource "" "" {','data "" "" {','module "" {','output "" {'],
 sql:['SELECT  FROM ;','WITH name AS (','INSERT INTO  () VALUES ();','UPDATE  SET  WHERE ;','DELETE FROM  WHERE ;','CREATE TABLE  ();','WHERE ','GROUP BY ','ORDER BY ','LIMIT 10;'],
 dockerfile:['FROM alpine:3.22','ARG NAME=""','WORKDIR /app','COPY . /app','RUN ','ENV NAME=""','EXPOSE 8080','USER app','ENTRYPOINT []','CMD []','HEALTHCHECK CMD '],
 json:['"name": ""','"enabled": true','"items": []','"config": {}','true','false','null'],
 yaml:['name: ""','hosts: ""','vars:','tasks:','handlers:','- name: ""','enabled: true','items: []'],
 github:['name: ""','on:','permissions:','env:','jobs:','runs-on: ubuntu-latest','needs:','steps:','- name: ""','uses: actions/checkout@v4','run: '],
 gitlab:['stages:','variables:','default:','image:','stage: test','needs:','script:','rules:','artifacts:','cache:','- echo ""'],
 jenkins:['pipeline {','agent any','options {','environment {','stages {','stage(\'\') {','steps {','sh \'\'','post {','always {'],
 ansible:['- name: ""','name: ""','hosts: ""','gather_facts: false','become: true','vars:','tasks:','handlers:','ansible.builtin.ping: {}','ansible.builtin.package:','ansible.builtin.service:','ansible.builtin.copy:','ansible.builtin.template:','ansible.builtin.command:','ansible.builtin.shell:']
};
function eaProfile(item){if(item.el.id==='ab-preview')return'ansible';if(item.el.id==='sx-command-preview')return'command';if(item.el.id==='dk-preview')return dkActive?.sheet||'command';const id=ddState?.profile;if(id==='github-actions')return'github';if(id==='gitlab-ci')return'gitlab';if(id==='jenkins')return'jenkins';if(id==='yaml')return'yaml';return id||'command';}
function eaIndentSize(profile){return['python','powershell'].includes(profile)?4:2;}
function eaPrevious(lines,index){for(let i=index-1;i>=0;i--)if(lines[i].trim())return{line:lines[i],index:i};return{line:'',index:-1};}
function eaYamlNext(profile,lines,index){const prev=eaPrevious(lines,index).line,trim=prev.trim();if(/^[-]?\s*name\s*:/.test(trim)){if(/^\s*-\s+name\s*:/.test(prev)&&lines.slice(0,index).some(x=>/^\s*(tasks|handlers|pre_tasks|post_tasks)\s*:\s*$/.test(x)))return['ansible.builtin.ping: {}','ansible.builtin.command: ""','ansible.builtin.package:'];return profile==='github'?['on:','jobs:']:profile==='gitlab'?['stages:','variables:']:['hosts: ""','gather_facts: false','become: true'];}if(/^hosts\s*:/.test(trim))return['gather_facts: false','become: true','vars:','tasks:'];if(/^(gather_facts|become)\s*:/.test(trim))return['vars:','tasks:','handlers:'];if(/^(tasks|handlers|pre_tasks|post_tasks|steps)\s*:\s*$/.test(trim))return['- name: ""'];if(/^on\s*:\s*$/.test(trim))return['push:','pull_request:','workflow_dispatch:'];if(/^jobs\s*:\s*$/.test(trim))return['build:'];if(/^stages\s*:\s*$/.test(trim))return['- build','- test','- deploy'];if(/^script\s*:\s*$/.test(trim))return['- echo ""'];return[];}
function eaNext(profile,lines,index){const trim=eaPrevious(lines,index).line.trim();if(['ansible','yaml','github','gitlab'].includes(profile))return eaYamlNext(profile,lines,index);if(profile==='dockerfile'){if(/^FROM\b/i.test(trim))return['WORKDIR /app','COPY . /app','RUN '];if(/^WORKDIR\b/i.test(trim))return['COPY . /app','RUN '];if(/^COPY\b/i.test(trim))return['RUN '];}if(profile==='python'){if(/^#!.*python/.test(trim))return['import os','from pathlib import Path'];if(/^def\b.*:\s*$/.test(trim))return['return None','pass'];if(/^(?:if|for|while|with)\b.*:\s*$/.test(trim)||/^try:\s*$/.test(trim))return['print("")','pass'];}if(profile==='bash'){if(/^#!/.test(trim))return['set -euo pipefail'];if(/(?:\bthen|\bdo|\{)\s*$/.test(trim))return['echo ""'];}if(profile==='powershell'&&/\{\s*$/.test(trim))return['Write-Output ""'];if(profile==='terraform'&&/\{\s*$/.test(trim))return[/^terraform\s*\{/.test(trim)?'required_version = ">= 1.6"':'name = ""'];if(profile==='sql'&&/^SELECT\b/i.test(trim)&&!trim.includes('FROM'))return['FROM '];if(profile==='json'&&/(?:\{|\[)\s*$/.test(trim))return[trim.endsWith('{')?'"name": ""':'""'];if(profile==='jenkins'){if(/^pipeline\s*\{/.test(trim))return['agent any','stages {'];if(/^stage\b.*\{/.test(trim))return['steps {'];if(/^steps\s*\{/.test(trim))return["sh ''"];if(/\{\s*$/.test(trim))return["echo ''"]; }return[];}
function eaCandidates(item){const cm=item.cm,cursor=cm.getCursor(),profile=eaProfile(item),line=cm.getLine(cursor.line)||'',before=line.slice(0,cursor.ch),indent=/^\s*/.exec(before)[0],body=before.slice(indent.length),lines=cm.getValue().split('\n');let fragment=/[A-Za-z_][\w.-]*$/.exec(body)?.[0]||'',start=cursor.ch-fragment.length,candidates=[];
 if(profile==='command'){const token=/[/-][\w-]*$/.exec(body)?.[0]||'';fragment=token;start=cursor.ch-token.length;candidates=(currentBuilder?.def?.flags||[]).map(flag=>flag.flag+(flag.valuePrompt?(flag.join===':'?':':' ')+'""':''));}
 if(profile==='python'){const m=/^\s*(?:import|from)\s+([\w.]*)$/.exec(before);if(m){fragment=m[1];start=cursor.ch-fragment.length;candidates=['os','sys','pathlib','subprocess','json','yaml','requests','httpx','numpy as np','pandas as pd','openpyxl','cv2','boto3','paramiko'];}}
 if(profile==='ansible'&&/ansible(?:\.builtin)?\.[\w.]*$/.test(body)){fragment=/[\w.]+$/.exec(body)[0];start=cursor.ch-fragment.length;candidates=EA_CATALOG.ansible.filter(x=>x.startsWith('ansible.'));}
 if(!candidates.length)candidates=[...eaNext(profile,lines,cursor.line),...(EA_CATALOG[profile]||[])];
 const clean=[...new Set(candidates)].filter(text=>!fragment||text.toLowerCase().startsWith(fragment.toLowerCase())).filter(text=>text!==fragment).slice(0,5);return clean.map(text=>({text,start,end:cursor.ch,fragment,display:text}));}
function eaClear(item){item.assistCompletion=null;if(item.assistMark){item.assistMark.clear();item.assistMark=null;}if(item.assist){item.assist.hidden=true;item.assist.replaceChildren();}}
function eaUpdate(item){if(!item?.el?.isConnected||item.writing)return;cancelAnimationFrame(item.assistFrame);item.assistFrame=requestAnimationFrame(()=>{eaClear(item);if(ceVim&&!item.cm.state.vim?.insertMode)return;const candidates=eaCandidates(item);if(!candidates.length)return;const completion=candidates[0],cursor=item.cm.getCursor(),suffix=completion.text.slice(completion.fragment.length);if(suffix){const ghost=document.createElement('span');ghost.className='ce-ghost';ghost.textContent=suffix.replace(/\n/g,' ↵ ');item.assistMark=item.cm.setBookmark(cursor,{widget:ghost,insertLeft:true});}item.assistCompletion=completion;item.assist.hidden=false;const lead=document.createElement('span');lead.className='ce-assist-lead';lead.textContent='Tab completes';item.assist.append(lead);for(const candidate of candidates.slice(0,3)){const button=document.createElement('button');button.type='button';button.className='ce-assist-option';button.textContent=candidate.display;button.onclick=()=>eaApply(item,candidate);item.assist.append(button);}});}
function eaApply(item,completion){const cm=item.cm,line=cm.getCursor().line;cm.operation(()=>{cm.replaceRange(completion.text,{line,ch:completion.start},{line,ch:completion.end},'+autocomplete');const quotes=completion.text.indexOf('""'),single=completion.text.indexOf("''"),slot=quotes>=0?quotes:single;if(slot>=0)cm.setCursor(line,completion.start+slot+1);else cm.setCursor(cm.posFromIndex(cm.indexFromPos({line,ch:completion.start})+completion.text.length));});eaUpdate(item);return true;}
function eaAccept(item){const completion=eaCandidates(item)[0];if(!completion)return false;return eaApply(item,completion);}
function eaEnter(item){const cm=item.cm,cursor=cm.getCursor(),profile=eaProfile(item),line=cm.getLine(cursor.line)||'',before=line.slice(0,cursor.ch),base=/^\s*/.exec(line)[0],size=eaIndentSize(profile);let indent=base;if(['ansible','yaml','github','gitlab'].includes(profile)){if(/^\s*-\s+name\s*:/.test(before)||/:\s*$/.test(before))indent+=' '.repeat(size);}else if(profile==='json'&&/(?:\{|\[)\s*$/.test(before))indent+=' '.repeat(size);else if(profile==='python'&&/:\s*(?:#.*)?$/.test(before))indent+=' '.repeat(size);else if(profile==='bash'&&/(?:\bthen|\bdo|\{)\s*$/.test(before))indent+=' '.repeat(size);else if(['powershell','terraform','jenkins'].includes(profile)&&/\{\s*$/.test(before))indent+=' '.repeat(size);else if(profile==='dockerfile'&&/\\\s*$/.test(before))indent+='    ';cm.replaceSelection('\n'+indent,'end','+input');setTimeout(()=>eaUpdate(item));return true;}
function eaMount(item){if(item.assist)return;const assist=document.createElement('div');assist.className='ce-assist';assist.setAttribute('role','status');assist.setAttribute('aria-live','polite');assist.hidden=true;item.cm.getWrapperElement().before(assist);item.assist=assist;eaUpdate(item);}
for(const item of CE_EDITORS.values())eaMount(item);
