/* Files stay in this browser. Source imports are never executed or heuristically rewritten. */
DD_PROFILES.source={id:'source',title:'Imported file editor',description:'Edit your original source directly. Comments and syntax are preserved; this file has not been converted into language blocks.',filename:'file.txt',types:{source:ddType('File contents','Edit the text, then copy or download the file. Source syntax is not validated.',{text:ddField('Editable file contents','','multiline')})},root:ddSlot('File',['source'],1,1),seed:p=>[ddNode(p,'source')],generate:nodes=>nodes[0].values.text,check:'Source mode preserves the original text on import. Editing uses the file’s original newline style. Nothing is executed.'};
function dfParse(name,text,mode='auto'){
 if(text.includes('\0'))throw Error('This appears to be a binary file. Open a UTF-8 text file.');
 const structured=mode==='blocks'||(mode==='auto'&&/\.(json|ya?ml)$/i.test(name));
 if(!structured)return {profile:'source',nodes:[ddNode(DD_PROFILES.source,'source',{text})]};
 const json=/\.json$/i.test(name),p=DD_PROFILES[json?'json':'yaml'];let values;
 try{values=json?[JSON.parse(text.replace(/^\uFEFF/,''))]:jsyaml.loadAll(text,{schema:jsyaml.JSON_SCHEMA,json:false});}catch(e){throw Error('Cannot build a data tree: '+e.message+' You can choose “Original source text” to edit the file as-is.');}
 if(!values.length||values.some(v=>v===undefined))throw Error('The file contains an empty document. Choose original source text or add a root value.');
 let count=0;const ancestors=new Set();function check(v,depth=0){if(++count>1500||depth>20)throw Error('Block imports allow up to 1,500 values and 20 nested levels. Use original source text for this file.');if(v&&typeof v==='object'){if(ancestors.has(v))throw Error('Cyclic YAML aliases cannot become a block tree. Use original source text.');ancestors.add(v);Object.values(v).forEach(x=>check(x,depth+1));ancestors.delete(v);}}
 values.forEach(v=>check(v));return {profile:p.id,nodes:values.map(v=>ddFromValue(p,v))};
}
async function dfRead(file){if(file.size>1000000)throw Error('Open a file under 1 MB.');const bytes=new Uint8Array(await file.arrayBuffer());if((bytes[0]===255&&bytes[1]===254)||(bytes[0]===254&&bytes[1]===255))throw Error('Save this UTF-16 file as UTF-8 before opening it here.');try{return new TextDecoder('utf-8',{fatal:true,ignoreBOM:true}).decode(bytes);}catch(e){throw Error('This is not UTF-8 text. Save the file as UTF-8 and try again.');}}
function dfZone(sheet){const zone=dkEl('section','df-zone');zone.setAttribute('aria-label','Open a local file');const title=dkEl('strong','','Drop a file here to customize it');const help=dkEl('p','dk-help','YAML/JSON, Terraform and supported scripts → connected code and blocks. Unrecognized syntax stays editable as custom code. Files stay on your computer.');
 const row=dkEl('div','df-controls'),file=dkEl('input','dk-input');file.type='file';file.setAttribute('aria-label','Choose file to customize');const mode=dkEl('select','dk-input');mode.setAttribute('aria-label','File editing mode');for(const [value,label] of [['auto','Detect from filename'],['blocks','YAML / JSON blocks'],['source','Original source text']]){const option=dkEl('option','',label);option.value=value;mode.append(option);}row.append(file,mode);const status=dkEl('p','dk-help');status.setAttribute('role','status');status.textContent='Block mode preserves data, not comments or original formatting. Choose source text when those matter.';zone.append(title,help,row,status);let busy=false;
 async function open(files){if(busy)return;if(files.length!==1){status.textContent='Choose one file at a time.';return;}busy=true;file.disabled=true;mode.disabled=true;status.textContent='Reading file locally…';try{const item=files[0],text=await dfRead(item),result=dfParse(item.name,text,mode.value);const previous=document.querySelector('#dk-root .dd-editor')&&ddState?dkClone(ddState):null;const id='deep:'+sheet+':'+result.profile+':upload:'+item.name;const candidate={id,sheet,profile:result.profile,filename:item.name,blocks:result.nodes,imported:true,newline:text.includes('\r\n')?'CRLF':text.includes('\r')?'CR':'LF',...(result.state||{})};
  const errors=ddValidate(DD_PROFILES[result.profile],candidate.blocks);if(errors.length)throw Error(errors[0]);
  // Commit only after decoding/parsing succeeds. Existing builder drafts remain saved.
  document.getElementById('ab-dialog')?.close();dkStopTest();dkShow();ddState=candidate;ddHistory=previous?[previous]:[];ddFuture=[];ddCollapsed.clear();ddRender();ddSave();
  document.getElementById('dd-notice').textContent=result.profile==='source'?'Opened '+item.name+' as original source. No automatic block conversion was applied.':'Opened '+item.name+' as editable '+result.profile.toUpperCase()+' blocks.';
 }catch(e){status.textContent=e.message;}finally{busy=false;file.disabled=false;mode.disabled=false;file.value='';}}
 file.onchange=()=>{if(file.files.length)open(Array.from(file.files));};
 zone.addEventListener('dragover',e=>{if(Array.from(e.dataTransfer?.types||[]).includes('Files')){e.preventDefault();e.stopPropagation();e.dataTransfer.dropEffect='copy';zone.classList.add('df-over');}});zone.addEventListener('dragleave',e=>{if(!zone.contains(e.relatedTarget))zone.classList.remove('df-over');});zone.addEventListener('drop',e=>{e.preventDefault();e.stopPropagation();zone.classList.remove('df-over');open(Array.from(e.dataTransfer?.files||[]));});return zone;
}
const dfHome=dkHome;dkHome=function(sheet){dfHome(sheet);document.querySelector('#dk-root .dk-home')?.prepend(dfZone(sheet));};
const dfRender=ddRender;ddRender=function(){dfRender();const editor=document.querySelector('#dk-root .dd-editor');editor?.querySelector('.dd-import')?.remove();editor?.prepend(dfZone(ddState.sheet));
 if(ddState.profile==='source'){const input=editor.querySelector('textarea[data-field="text"]');if(input){input.classList.add('df-source');input.spellcheck=false;const update=input.oninput;input.oninput=()=>{update();const value=input.value;ddState.blocks[0].values.text=ddState.newline==='CRLF'?value.replace(/\n/g,'\r\n'):ddState.newline==='CR'?value.replace(/\n/g,'\r'):value;ddSave();ddRefresh();};}editor.querySelector('.dd-tip').textContent='Edit the imported source below. Copy or download keeps your filename. This mode preserves code instead of guessing its structure.';}
};
const dfQuick=dkRender;dkRender=function(){dfQuick();document.querySelector('#dk-root .dk-editor')?.prepend(dfZone(dkActive.sheet));};
const dfAnsible=abRender;abRender=function(){dfAnsible();const shell=document.querySelector('#ab-dialog .ab-shell');if(shell&&!shell.querySelector('.df-ansible')){const button=dkBtn('Open / drop a file…',()=>{document.getElementById('ab-dialog').close();dkHome('ansible');},'ab-button df-ansible');shell.querySelector('.ab-header')?.append(button);}};
// Prevent accidental browser navigation if a file misses the visible drop zone.
document.addEventListener('dragover',e=>{if(Array.from(e.dataTransfer?.types||[]).includes('Files'))e.preventDefault();});
document.addEventListener('drop',e=>{if(Array.from(e.dataTransfer?.types||[]).includes('Files'))e.preventDefault();});
