/* Offline ZIP portability, durable snapshots and readable line diffs for projects. */
const PW_ZIP_MAX_TOTAL=20000000,PW_SNAPSHOT_MAX_TOTAL=5000000,PW_SNAPSHOT_MAX_CURRENT=2000000;
let pwCrcTable=null;
function pwCrc32(bytes){if(!pwCrcTable)pwCrcTable=Array.from({length:256},(_,n)=>{let c=n;for(let i=0;i<8;i++)c=(c&1)?0xedb88320^(c>>>1):c>>>1;return c>>>0;});let crc=0xffffffff;for(const byte of bytes)crc=pwCrcTable[(crc^byte)&255]^(crc>>>8);return (crc^0xffffffff)>>>0;}
function pwZipHeader(length){const bytes=new Uint8Array(length),view=new DataView(bytes.buffer);return {bytes,u16:(at,n)=>view.setUint16(at,n,true),u32:(at,n)=>view.setUint32(at,n>>>0,true)};}
function pwDosTime(date=new Date()){const year=Math.max(1980,date.getFullYear());return {time:(date.getHours()<<11)|(date.getMinutes()<<5)|(date.getSeconds()>>1),date:((year-1980)<<9)|((date.getMonth()+1)<<5)|date.getDate()};}
function pwZipEncode(entries){
 if(!Array.isArray(entries)||entries.length>PW_MAX_FILES+PW_MAX_FOLDERS)throw Error('ZIP archives exceed the project entry limit.');const encoder=new TextEncoder(),parts=[],central=[],stamp=pwDosTime();let offset=0,total=0;
 for(const entry of entries){const directory=!!entry.directory,path=pwPath(entry.path)+(directory?'/':''),name=encoder.encode(path),data=directory?new Uint8Array():entry.bytes instanceof Uint8Array?entry.bytes:encoder.encode(String(entry.text??''));if(name.length>65535||data.length>1000000)throw Error('A ZIP entry is too large: '+path);total+=data.length;if(total>PW_ZIP_MAX_TOTAL)throw Error('ZIP contents exceed 20 MB.');const crc=pwCrc32(data),local=pwZipHeader(30);local.u32(0,0x04034b50);local.u16(4,20);local.u16(6,0x800);local.u16(8,0);local.u16(10,stamp.time);local.u16(12,stamp.date);local.u32(14,crc);local.u32(18,data.length);local.u32(22,data.length);local.u16(26,name.length);local.u16(28,0);parts.push(local.bytes,name,data);central.push({path,name,data,crc,offset,directory});offset+=30+name.length+data.length;
 }
 const start=offset;for(const entry of central){const head=pwZipHeader(46);head.u32(0,0x02014b50);head.u16(4,20);head.u16(6,20);head.u16(8,0x800);head.u16(10,0);head.u16(12,stamp.time);head.u16(14,stamp.date);head.u32(16,entry.crc);head.u32(20,entry.data.length);head.u32(24,entry.data.length);head.u16(28,entry.name.length);head.u16(30,0);head.u16(32,0);head.u16(34,0);head.u16(36,0);head.u32(38,entry.directory?0x10:0);head.u32(42,entry.offset);parts.push(head.bytes,entry.name);offset+=46+entry.name.length;}
 const end=pwZipHeader(22);end.u32(0,0x06054b50);end.u16(4,0);end.u16(6,0);end.u16(8,central.length);end.u16(10,central.length);end.u32(12,offset-start);end.u32(16,start);end.u16(20,0);parts.push(end.bytes);return new Blob(parts,{type:'application/zip'});
}
async function pwInflate(bytes,expected){if(typeof DecompressionStream!=='function')throw Error('This browser cannot open compressed ZIP entries. Use a current browser or a stored ZIP.');let stream;try{stream=new Blob([bytes]).stream().pipeThrough(new DecompressionStream('deflate-raw'));}catch{throw Error('This browser cannot open deflated ZIP entries.');}const reader=stream.getReader(),chunks=[];let total=0;try{while(true){const {value,done}=await reader.read();if(done)break;total+=value.length;if(total>expected||total>1000000){await reader.cancel();throw Error('Expanded ZIP entry exceeds its declared size.');}chunks.push(value);}}catch(e){if(/exceeds/.test(e.message))throw e;throw Error('A deflated ZIP entry is damaged.');}const result=new Uint8Array(total);let at=0;for(const chunk of chunks){result.set(chunk,at);at+=chunk.length;}return result;}
async function pwZipRead(input){
 const bytes=input instanceof Uint8Array?input:new Uint8Array(input instanceof ArrayBuffer?input:await input.arrayBuffer()),view=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength);if(bytes.length<22||bytes.length>PW_ZIP_MAX_TOTAL+2000000)throw Error('Choose a ZIP archive under 22 MB.');let end=-1;for(let i=bytes.length-22;i>=Math.max(0,bytes.length-65557);i--)if(view.getUint32(i,true)===0x06054b50){end=i;break;}if(end<0)throw Error('ZIP end record was not found.');if(view.getUint16(end+4,true)||view.getUint16(end+6,true))throw Error('Multi-disk ZIP archives are not supported.');const count=view.getUint16(end+10,true),centralSize=view.getUint32(end+12,true),centralOffset=view.getUint32(end+16,true);if(count>PW_MAX_FILES+PW_MAX_FOLDERS||centralOffset+centralSize>end)throw Error('ZIP directory is invalid or too large.');const decoder=new TextDecoder('utf-8',{fatal:true}),files=[],folders=[],paths=new Set();let at=centralOffset,total=0;
 for(let index=0;index<count;index++){if(at+46>bytes.length||view.getUint32(at,true)!==0x02014b50)throw Error('ZIP directory entry is invalid.');const flags=view.getUint16(at+8,true),method=view.getUint16(at+10,true),crc=view.getUint32(at+16,true),compressed=view.getUint32(at+20,true),plain=view.getUint32(at+24,true),nameLength=view.getUint16(at+28,true),extraLength=view.getUint16(at+30,true),commentLength=view.getUint16(at+32,true),localOffset=view.getUint32(at+42,true),next=at+46+nameLength+extraLength+commentLength;if(next>bytes.length)throw Error('ZIP directory entry is truncated.');if(flags&1)throw Error('Encrypted ZIP entries are not supported.');if(![0,8].includes(method))throw Error('ZIP compression method '+method+' is not supported.');if(plain>1000000||compressed>1000000)throw Error('A ZIP entry exceeds the 1 MB file limit.');let rawName;try{rawName=decoder.decode(bytes.slice(at+46,at+46+nameLength));}catch{throw Error('ZIP filenames must be valid UTF-8.');}const directory=rawName.endsWith('/'),path=pwPath(directory?rawName.slice(0,-1):rawName),lower=path.toLowerCase();if(paths.has(lower))throw Error('ZIP paths must be unique: '+path);paths.add(lower);if(localOffset+30>bytes.length||view.getUint32(localOffset,true)!==0x04034b50)throw Error('ZIP local entry is invalid: '+path);const localName=view.getUint16(localOffset+26,true),localExtra=view.getUint16(localOffset+28,true),dataAt=localOffset+30+localName+localExtra;if(dataAt+compressed>bytes.length)throw Error('ZIP entry is truncated: '+path);const packed=bytes.slice(dataAt,dataAt+compressed),data=method===0?packed:await pwInflate(packed,plain);if(data.length!==plain||pwCrc32(data)!==crc)throw Error('ZIP integrity check failed: '+path);total+=data.length;if(total>PW_ZIP_MAX_TOTAL)throw Error('Expanded ZIP contents exceed 20 MB.');if(directory)folders.push(path);else{let text;try{text=decoder.decode(data);}catch{throw Error('ZIP file is not UTF-8 text: '+path);}files.push({path,text});}at=next;
 }
 const filePaths=new Set(files.map(f=>f.path.toLowerCase())),folderPaths=new Set(folders.map(f=>f.toLowerCase()));for(const file of files){const parts=file.path.toLowerCase().split('/');for(let i=1;i<parts.length;i++)if(filePaths.has(parts.slice(0,i).join('/')))throw Error('ZIP file paths conflict: '+file.path);if(folderPaths.has(file.path.toLowerCase()))throw Error('A ZIP path is both a file and folder: '+file.path);}if(files.length>PW_MAX_FILES||folders.length>PW_MAX_FOLDERS)throw Error('ZIP exceeds project file or folder limits.');
 return {files,folders};
}
function pwArchive(project){const entries=[],folders=new Set(project.folders);for(const file of project.files){const parts=file.path.split('/');for(let i=1;i<parts.length;i++)folders.add(parts.slice(0,i).join('/'));entries.push({path:file.path,text:pwText(dkDrafts[file.draftId])});}for(const folder of [...folders].sort())entries.unshift({path:folder,directory:true});return pwZipEncode(entries);}
function pwDownloadBlob(blob,name){const link=document.createElement('a'),url=URL.createObjectURL(blob);link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function pwArchiveName(project){return (project.name.replace(/[^A-Za-z0-9._-]+/g,'-').replace(/^-+|-+$/g,'')||'devkit-project')+'.zip';}
async function pwApplyArchive(project,archive,takeSnapshot=true){if(project.files.length+archive.files.length>PW_MAX_FILES)throw Error('The combined project would exceed '+PW_MAX_FILES+' files.');const incomingFolders=new Set(archive.folders);for(const entry of archive.files){const parts=entry.path.split('/');for(let i=1;i<parts.length;i++)incomingFolders.add(parts.slice(0,i).join('/'));}const newFolders=[...incomingFolders].filter(folder=>!project.folders.some(x=>x.toLowerCase()===folder.toLowerCase()));if(project.folders.length+newFolders.length>PW_MAX_FOLDERS)throw Error('The combined project would exceed '+PW_MAX_FOLDERS+' folders.');for(const entry of archive.files)if(pwPathConflict(project,entry.path))throw Error('A project path conflicts with '+entry.path);for(const folder of incomingFolders)if(pwPathConflict(project,folder,true))throw Error('A project file conflicts with folder '+folder);if(takeSnapshot&&project.files.length)pwSnapshot(project,'Before ZIP import');project.folders.push(...newFolders);for(const entry of archive.files)pwAddFile(project,entry.path,entry.text);pwPersist();ewPersist();return project;}
async function pwImportArchiveNew(file){const archive=await pwZipRead(file),name=file.name.replace(/\.zip$/i,'').slice(0,80)||'Imported project',project=pwCreateProject('blank',name);try{await pwApplyArchive(project,archive,false);return project;}catch(e){for(const item of project.files)delete dkDrafts[item.draftId];delete pwState.projects[project.id];pwPersist(false);ewPersist();throw e;}}
function pwSnapshotData(project){return {files:project.files.map(file=>({path:file.path,text:pwText(dkDrafts[file.draftId])})).sort((a,b)=>a.path.localeCompare(b.path)),folders:[...project.folders].sort(),variables:dkClone(project.variables)};}
function pwSnapshot(project,label='Manual snapshot'){const data=pwSnapshotData(project),currentBytes=data.files.reduce((n,f)=>n+f.text.length,0);if(currentBytes>PW_SNAPSHOT_MAX_CURRENT)throw Error('This project is too large for browser snapshot history. Export a ZIP before major changes.');const snapshot={id:pwId('s'),label:String(label||'Snapshot').trim().slice(0,100)||'Snapshot',createdAt:Date.now(),...data},signature=JSON.stringify(data),latest=project.snapshots[0];if(latest&&JSON.stringify({files:latest.files,folders:latest.folders,variables:latest.variables})===signature)return latest;project.snapshots.unshift(snapshot);while(project.snapshots.length>20||project.snapshots.reduce((n,s)=>n+s.files.reduce((m,f)=>m+f.text.length,0),0)>PW_SNAPSHOT_MAX_TOTAL)project.snapshots.pop();project.updatedAt=Date.now();if(!pwPersist(false)){project.snapshots=project.snapshots.filter(x=>x!==snapshot);throw Error('Browser storage is full. Export the project before continuing.');}return snapshot;}
function pwDiffLines(before,after){const a=String(before).split('\n'),b=String(after).split('\n'),out=[];if(a.length*b.length<=160000){const rows=Array.from({length:a.length+1},()=>new Uint16Array(b.length+1));for(let i=a.length-1;i>=0;i--)for(let j=b.length-1;j>=0;j--)rows[i][j]=a[i]===b[j]?rows[i+1][j+1]+1:Math.max(rows[i+1][j],rows[i][j+1]);let i=0,j=0;while(i<a.length||j<b.length){if(i<a.length&&j<b.length&&a[i]===b[j])out.push({type:'equal',text:a[i++]}),j++;else if(j<b.length&&(i===a.length||rows[i][j+1]>=rows[i+1][j]))out.push({type:'add',text:b[j++]});else out.push({type:'remove',text:a[i++]});}return out;}let start=0;while(start<a.length&&start<b.length&&a[start]===b[start])out.push({type:'equal',text:a[start++]});let ai=a.length-1,bi=b.length-1,suffix=[];while(ai>=start&&bi>=start&&a[ai]===b[bi])suffix.unshift({type:'equal',text:a[ai--]}),bi--;for(;ai>=start;ai--)out.push({type:'remove',text:a[ai]});for(let j=start;j<=bi;j++)out.push({type:'add',text:b[j]});return out.concat(suffix);}
function pwSnapshotChanges(project,snapshot){const old=new Map(snapshot.files.map(f=>[f.path,f.text])),current=new Map(project.files.map(f=>[f.path,pwText(dkDrafts[f.draftId])])),paths=[...new Set([...old.keys(),...current.keys()])].sort(),changes=[];for(const path of paths){const before=old.get(path),after=current.get(path);if(before!==after)changes.push({path,status:before===undefined?'added':after===undefined?'removed':'modified',before:before??'',after:after??''});}return changes;}
function pwRestoreFile(project,snapshot,path){pwSnapshot(project,'Before restoring '+path);const saved=snapshot.files.find(f=>f.path===path),current=project.files.find(f=>f.path===path);if(!saved&&current){project.files=project.files.filter(f=>f!==current);project.openTabs=project.openTabs.filter(id=>id!==current.id);delete dkDrafts[current.draftId];}else if(saved&&current)dkDrafts[current.draftId]=pwDraft(project,current,saved.text);else if(saved)pwAddFile(project,saved.path,saved.text);project.activeFileId=null;pwPersist(false);ewPersist();}
function pwRestoreSnapshot(project,snapshot){pwSnapshot(project,'Before restoring '+snapshot.label);for(const file of project.files)delete dkDrafts[file.draftId];project.files=[];project.folders=dkClone(snapshot.folders);project.variables=dkClone(snapshot.variables);project.openTabs=[];project.activeFileId=null;for(const file of snapshot.files)pwAddFile(project,file.path,file.text);project.updatedAt=Date.now();pwPersist();ewPersist();pwShowProject(project.id);}
function pwShowDiff(project,snapshot){const root=document.getElementById('dk-root');root.replaceChildren();const header=dkEl('header','dk-header'),heading=dkEl('div');heading.append(dkEl('span','dk-eyebrow','PROJECT HISTORY'),dkEl('h2','',snapshot.label),dkEl('p','dk-help','Snapshot from '+new Date(snapshot.createdAt).toLocaleString()+' compared with the current project.'));header.append(heading,dkBtn('Close ✕',dkClose));root.append(header);const bar=dkEl('div','dk-toolbar');bar.append(dkBtn('← Project',()=>pwShowProject(project.id)),dkBtn('Restore whole snapshot',()=>{if(confirm('Replace the current project files and variables with this snapshot?'))pwRestoreSnapshot(project,snapshot);}));root.append(bar);const body=dkEl('main','pw-diff'),changes=pwSnapshotChanges(project,snapshot);if(!changes.length){body.append(dkEl('p','dk-empty','The current project matches this snapshot.'));root.append(body);return;}for(const change of changes){const details=dkEl('details','pw-diff-file');details.open=changes.length<=3;const summary=dkEl('summary','',change.path+' · '+change.status);details.append(summary);let oldLine=1,newLine=1,count=0;for(const line of pwDiffLines(change.before,change.after)){if(++count>1200){details.append(dkEl('div','pw-diff-limit','Diff shortened after 1,200 lines.'));break;}const row=dkEl('div','pw-diff-line '+line.type),numbers=(line.type==='add'?'  ':oldLine++)+' '+(line.type==='remove'?'  ':newLine++),text=dkEl('span','',line.text||' ');row.append(dkEl('code','pw-diff-number',numbers),dkEl('code','pw-diff-marker',line.type==='add'?'+':line.type==='remove'?'-':' '),text);details.append(row);}details.append(dkBtn('Restore this file',()=>{if(confirm('Restore '+change.path+' from this snapshot?')){pwRestoreFile(project,snapshot,change.path);pwShowProject(project.id);}},'dk-btn'));body.append(details);}root.append(body);}
function pwHistory(host,project){const section=dkEl('section','pw-card pw-history');section.append(dkEl('h3','','Project history'),dkEl('p','dk-help','Snapshots preserve file contents, folders and shared variables. ZIP imports and restores create safety snapshots automatically.'));section.append(dkBtn('Create snapshot',()=>{const label=prompt('Snapshot label','Manual snapshot');if(label!==null)try{pwSnapshot(project,label);pwShowProject(project.id);}catch(e){alert(e.message);}}));for(const snapshot of project.snapshots){const changes=pwSnapshotChanges(project,snapshot),row=dkEl('div','pw-snapshot');row.append(dkEl('strong','',snapshot.label),dkEl('small','dk-help',new Date(snapshot.createdAt).toLocaleString()+' · '+changes.length+' changed files'),dkBtn('Compare',()=>pwShowDiff(project,snapshot),'dk-small'),dkBtn('Restore',()=>{if(confirm('Replace the current project with '+snapshot.label+'?'))pwRestoreSnapshot(project,snapshot);},'dk-small'),dkBtn('Delete',()=>{project.snapshots=project.snapshots.filter(x=>x!==snapshot);pwPersist();pwShowProject(project.id);},'dk-small'));section.append(row);}host.append(section);}
const pwaBaseShow=pwShowProject;pwShowProject=function(projectId=pwState.activeProjectId){pwaBaseShow(projectId);const project=pwState.projects[projectId];if(project){const actions=document.querySelector('#dk-root .pw-project-actions'),side=document.querySelector('#dk-root .pw-side');if(actions){actions.insertBefore(dkBtn('Export ZIP',async()=>{try{pwDownloadBlob(pwArchive(project),pwArchiveName(project));}catch(e){alert(e.message);}},'dk-btn primary'),actions.children[3]||null);const zip=dkEl('input','dk-input');zip.type='file';zip.accept='.zip,application/zip';zip.setAttribute('aria-label','Import ZIP into project');zip.onchange=async()=>{try{const file=zip.files[0];if(!file)return;const archive=await pwZipRead(file);await pwApplyArchive(project,archive);pwShowProject(project.id);}catch(e){const status=document.getElementById('pw-status');if(status)status.textContent=e.message;}};actions.append(zip);}if(side)pwHistory(side,project);}else{const body=document.querySelector('#dk-root .pw-home'),zip=dkEl('input','dk-input');if(body){zip.type='file';zip.accept='.zip,application/zip';zip.setAttribute('aria-label','Import ZIP as new project');zip.onchange=async()=>{try{const file=zip.files[0];if(file)pwShowProject((await pwImportArchiveNew(file)).id);}catch(e){const status=document.getElementById('pw-status');if(status)status.textContent=e.message;}};body.append(dkEl('h3','','Import ZIP folder'),zip);}}};
