let pyTimer=null,pyTyping=false,pySearch='',pyGroup='All',pyTarget='root';
function pyIsActive(){return ddState?.profile==='python'&&!!document.querySelector('#dk-root .dd-editor');}
function pyClearPending(){clearTimeout(pyTimer);pyTimer=null;}
function pyStatus(message){const label=document.getElementById('py-sync-status');if(label)label.textContent=message;const editor=document.querySelector('#dk-root .dd-editor');if(editor&&ddState?.profile==='python'){editor.inert=!!ddState.pyDirty;const sidebar=document.querySelector('.py-sidebar');if(sidebar)sidebar.inert=!!ddState.pyDirty;}}
function pySync(){pyClearPending();if(!pyIsActive()||!ddState.pyDirty)return true;const preview=document.getElementById('dd-preview'),selection=preview?{start:preview.selectionStart,end:preview.selectionEnd,top:preview.scrollTop,focus:document.activeElement===preview}:null;
 try{const blocks=pyParse(ddState.pyCode);ddState.blocks=blocks;ddState.pySyncSig=pySignature(blocks);ddState.pyDirty=false;delete ddState.pyError;ddSave();ddRender();const next=document.getElementById('dd-preview');if(selection){if(selection.focus)next.focus();next.setSelectionRange(selection.start,selection.end);next.scrollTop=selection.top;}return true;}catch(e){ddState.pyError=e.message;ddSave();pyStatus(e.message);return false;}}
// Shared change coordination lives in editor-workspace.js.
const pyBaseOutput=ddOutput;ddOutput=function(){if(ddState?.profile!=='python')return pyBaseOutput();
 if(typeof ddState.pyCode==='string'&&(ddState.pyDirty||ddState.pySyncSig===pySignature(ddState.blocks)))return {text:ddState.pyCode,errors:ewFilenameErrors(ddState.filename),filename:ddState.filename};
 delete ddState.pyCode;delete ddState.pySyncSig;const out=pyBaseOutput();if(!out.errors.length)try{pyParse(out.text);}catch(e){out.errors.push(e.message);}return out;
};
const pyBaseRefresh=ddRefresh;ddRefresh=function(){const preview=document.getElementById('dd-preview');const selection=pyIsActive()&&document.activeElement===preview?{start:preview.selectionStart,end:preview.selectionEnd,top:preview.scrollTop}:null;pyBaseRefresh();if(ddState?.profile==='python'){if(selection){preview.setSelectionRange(selection.start,selection.end);preview.scrollTop=selection.top;}pyStatus(ddState.pyDirty?(ddState.pyError||'Typing… blocks update after a short pause.'):'Code and blocks are in sync.');}};
function pyDestinations(){const result=[{value:'root',label:'End of script',parent:null,slot:'root'}];function visit(nodes,path=''){for(const n of nodes){const label=pyP.types[n.type].label;for(const [key,children] of Object.entries(n.slots)){if(pyP.types[n.type].slots[key].accept.includes('variable'))result.push({value:n.id+':'+key,label:(path?path+' / ':'')+label+' → '+pyP.types[n.type].slots[key].label,parent:n.id,slot:key});visit(children,(path?path+' / ':'')+label);}}}visit(ddState.blocks);return result;}
function pyAdd(type){const dest=pyDestinations().find(d=>d.value===pyTarget)||pyDestinations()[0];ddChange(()=>{const node=ddNewNode(type);ddLane(dest.parent,dest.slot).push(node);ddCollapsed.delete(node.id);});}
const PY_STARTERS={
 'CSV → Excel':p=>[ddNode(p,'py_csv'),ddNode(p,'py_head'),ddNode(p,'py_excel_write')],
 'NumPy summary':p=>[ddNode(p,'py_array'),ddNode(p,'py_stats'),ddNode(p,'print',{mode:'variable',value:'average'})],
 'Edit Excel cells':p=>[ddNode(p,'py_workbook'),ddNode(p,'py_cell'),ddNode(p,'py_savebook')],
 'Resize an image':p=>[ddNode(p,'py_image'),ddNode(p,'py_if',{condition:'image is not None'},{then:[ddNode(p,'py_resize'),ddNode(p,'py_imwrite',{image:'resized'})],else:[ddNode(p,'print',{value:'Could not read the input image'})]})]
};
function pyLibrary(editor){const library=dkEl('section','py-library');library.append(dkEl('span','dk-eyebrow','WHAT DO YOU WANT TO DO?'));
 const starter=dkEl('details','py-starters');starter.append(dkEl('summary','','Start from a complete example'));const startrow=dkEl('div','py-chips');for(const [title,seed] of Object.entries(PY_STARTERS))startrow.append(dkBtn(title,()=>ddChange(()=>{ddState.blocks=seed(pyP);delete ddState.pyCode;ddState.pyDirty=false;})));starter.append(startrow,dkEl('p','dk-help','Replaces the current script. Undo restores it.'));library.append(starter);
 const search=dkEl('input','dk-input');search.placeholder='Search tasks: read Excel, resize, loop, import…';search.setAttribute('aria-label','Find a Python step');search.value=pySearch;library.append(search);
 const categories=dkEl('select','dk-input py-category');categories.setAttribute('aria-label','Python task category');for(const name of ['All','Basics','Modules',...new Set(Object.values(PY_OPS).map(op=>op.group).filter(g=>!['Basics','Modules'].includes(g)))]){const option=dkEl('option','',name);option.value=name;categories.append(option);}categories.value=pyGroup;categories.onchange=()=>{pyGroup=categories.value;draw();};library.append(categories);
 const targetLabel=dkEl('label','dk-field','Add the next step to');const target=dkEl('select','dk-input');target.setAttribute('aria-label','Add Python step to');for(const d of pyDestinations()){const o=dkEl('option','',d.label);o.value=d.value;target.append(o);}target.value=pyTarget;if(!target.value){pyTarget='root';target.value='root';}target.onchange=()=>pyTarget=target.value;targetLabel.append(target);library.append(targetLabel);
 const list=dkEl('div','py-step-list');library.append(list);function draw(){list.replaceChildren();categories.querySelectorAll('button').forEach(b=>b.classList.toggle('selected',b.textContent===pyGroup));const basics=['print','variable','arrayVariable','if','foreach','function','try','raw'];const all=[...Object.keys(PY_OPS),...basics,'py_if','py_for','py_function'];const q=pySearch.toLowerCase();for(const id of all){const def=pyP.types[id],op=PY_OPS[id],group=op?.group||'Basics';if(pyGroup!=='All'&&pyGroup!==group)continue;if(q&&!(def.label+' '+def.hint+' '+group).toLowerCase().includes(q))continue;const card=dkBtn('',()=>pyAdd(id),'py-step');card.dataset.pythonStep=id;card.append(dkEl('strong','','+ '+def.label),dkEl('small','',def.hint));list.append(card);}if(!list.children.length)list.append(dkEl('p','dk-help','No matching steps. Try another term or add a custom module.'));}search.oninput=()=>{pySearch=search.value;draw();};draw();
 const packages=dkEl('details','py-packages');packages.append(dkEl('summary','','Packages & custom modules'));const moduleSearch=dkEl('input','dk-input');moduleSearch.placeholder='Find a module: pathlib, SSH, boto3…';moduleSearch.setAttribute('aria-label','Find a Python module');packages.append(moduleSearch);const chips=dkEl('div','py-module-list');for(const [id,p] of Object.entries(PY_PACKAGES)){const row=dkEl('div','py-module-row');row.dataset.search=(p.title+' '+p.module+' '+(p.hint||'')).toLowerCase();const button=dkBtn('+ '+p.title,()=>ddChange(()=>{if(!ddState.blocks.some(n=>n.type==='py_import'&&n.values.module===p.module))ddState.blocks.unshift(ddNode(pyP,'py_import',{module:p.module,alias:p.alias}));}));row.append(button,dkEl('small','',p.pip?'pip install '+p.pip:'Built into Python'));if(p.hint)row.append(dkEl('small','',p.hint));if(p.url){const link=dkEl('a','','Documentation ↗');link.href=p.url;link.target='_blank';link.rel='noopener';row.append(link);}chips.append(row);}moduleSearch.oninput=()=>chips.querySelectorAll('.py-module-row').forEach(row=>row.hidden=!row.dataset.search.includes(moduleSearch.value.toLowerCase()));packages.append(chips,dkBtn('+ Custom module',()=>pyAdd('py_import')));
 const required=[...new Set(pyRequirements(ddState.blocks).map(id=>PY_PACKAGES[id].pip).filter(Boolean))];const command=dkEl('code','py-install',required.length?'python -m pip install '+required.join(' '):'Only built-in modules, or no additional packages selected.');packages.append(command);if(required.length)packages.append(dkBtn('Download requirements.txt',()=>dkDownloadText(required.join('\n')+'\n','requirements.txt')));packages.append(dkEl('p','dk-help','Install packages in your Python environment. DevKit only generates code; it does not install or run packages. Custom modules must already be importable.'));library.append(packages);editor.prepend(library);
}
const pyBaseRender=ddRender;ddRender=function(){pyBaseRender();const root=document.getElementById('dk-root');root.classList.toggle('py-workspace',ddState?.profile==='python');if(ddState?.profile!=='python')return;const editor=root.querySelector('.dd-editor'),output=root.querySelector('.dk-output');
 const zone=editor.querySelector('.df-zone');if(zone){const details=dkEl('details','py-file');details.append(dkEl('summary','','Open an existing file'),zone);editor.prepend(details);}
 editor.querySelector('.dd-tip').textContent='Choose a task in the step library. Edit its fields here, or type code on the right. To add inside a loop or branch, choose it in “Add the next step to”.';pyLibrary(editor);const sidebar=dkEl('aside','py-sidebar');sidebar.append(editor.querySelector('.py-library'));editor.before(sidebar);
 const heading=dkEl('h3','py-script-title','Your script steps');const lane=editor.querySelector(':scope > .dd-lane');lane?.before(heading);
 const preview=document.getElementById('dd-preview');preview.readOnly=false;preview.setAttribute('aria-label','Editable Python script');const label=dkEl('div','py-code-label','PYTHON CODE · EDITABLE');output.insertBefore(label,preview);const sync=dkEl('p','dk-help');sync.id='py-sync-status';sync.setAttribute('role','status');preview.after(sync);const apply=dkBtn('Sync code to blocks now',pySync);sync.after(apply);
 preview.onfocus=()=>pyTyping=false;preview.oninput=()=>{if(!pyTyping){ddRemember();pyTyping=true;}ddState.pyCode=preview.value;ddState.pyDirty=true;delete ddState.pyError;ddSave();pyStatus('Typing… blocks update after a short pause.');document.getElementById('dd-undo').disabled=false;pyClearPending();pyTimer=setTimeout(pySync,600);};preview.onkeydown=e=>{if(e.key==='Tab'){e.preventDefault();const start=preview.selectionStart,end=preview.selectionEnd;preview.setRangeText('    ',start,end,'end');preview.dispatchEvent(new Event('input'));}if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();pySync();}};
 pyStatus(ddState.pyDirty?(ddState.pyError||'Your code is saved. Continue typing, then sync.'):'Code and blocks are in sync.');
};
const pyOriginalFileParse=dfParse;dfParse=function(name,text,mode='auto'){if(mode==='auto'&&/\.py$/i.test(name)){let nodes,error;try{nodes=pyParse(text);}catch(e){nodes=[ddNode(pyP,'raw',{text})];error=e.message;}return {profile:'python',nodes,state:{pyCode:text,pySyncSig:pySignature(nodes),pyDirty:!!error,...(error?{pyError:error}:{})}};}return pyOriginalFileParse(name,text,mode);};
const pyHome=dkHome;dkHome=function(sheet){pyClearPending();document.getElementById('dk-root').classList.remove('py-workspace');pyHome(sheet);};
const pyQuickRender=dkRender;dkRender=function(){pyClearPending();document.getElementById('dk-root').classList.remove('py-workspace');pyQuickRender();};
