/* Curated operations toolkit; generated code is never executed by DevKit. */
const PY_OPS_MODULES=[
 ['sys','Python runtime','', 'sys','Access argv, interpreter details and exit status.','https://docs.python.org/3/library/sys.html'],
 ['platform','System identification','', 'platform','Read OS, architecture and Python version information.','https://docs.python.org/3/library/platform.html'],
 ['tempfile','Temporary files','', 'tempfile','Create temporary files and directories with cleanup.','https://docs.python.org/3/library/tempfile.html'],
 ['glob','Filename matching','', 'glob','Find paths using shell-style glob patterns.','https://docs.python.org/3/library/glob.html'],
 ['asyncio','Async I/O','', 'asyncio','Coordinate asynchronous network and I/O tasks.','https://docs.python.org/3/library/asyncio.html'],
 ['pathlib','Files and paths','', 'pathlib','Portable path handling and file discovery.','https://docs.python.org/3/library/pathlib.html'],
 ['os','Environment variables','', 'os','Read environment settings without embedding credentials.','https://docs.python.org/3/library/os.html'],
 ['shutil','Copy and archive files','', 'shutil','Copy files, create archives and inspect disk space.','https://docs.python.org/3/library/shutil.html'],
 ['subprocess','Run local programs','', 'subprocess','Execute argument lists with captured output and timeouts.','https://docs.python.org/3/library/subprocess.html'],
 ['json','JSON','', 'json','Read and write JSON configuration and API data.','https://docs.python.org/3/library/json.html'],
 ['csv','CSV','', 'csv','Process simple CSV inventories without pandas.','https://docs.python.org/3/library/csv.html'],
 ['re','Regular expressions','', 're','Extract patterns from logs and text.','https://docs.python.org/3/library/re.html'],
 ['logging','Logging','', 'logging','Add timestamps and severity levels to automation output.','https://docs.python.org/3/library/logging.html'],
 ['argparse','Command-line arguments','', 'argparse','Give scripts flags and help messages.','https://docs.python.org/3/library/argparse.html'],
 ['datetime','Timestamps','', 'datetime','Timezone-aware timestamps for reports.','https://docs.python.org/3/library/datetime.html'],
 ['time','Timing','', 'time','Measure durations or delay polling.','https://docs.python.org/3/library/time.html'],
 ['socket','TCP and DNS','', 'socket','Resolve hosts and test TCP connectivity.','https://docs.python.org/3/library/socket.html'],
 ['ipaddress','IP networks','', 'ipaddress','Validate addresses and check subnet membership.','https://docs.python.org/3/library/ipaddress.html'],
 ['futures','Parallel tasks','', 'concurrent.futures','Run independent I/O tasks in a thread pool.','https://docs.python.org/3/library/concurrent.futures.html'],
 ['sqlite3','SQLite','', 'sqlite3','Query local inventory databases.','https://docs.python.org/3/library/sqlite3.html'],
 ['hashlib','File checksums','', 'hashlib','Calculate streaming checksums for files.','https://docs.python.org/3/library/hashlib.html'],
 ['tomllib','TOML (Python 3.11+)','', 'tomllib','Read pyproject.toml and other TOML configuration.','https://docs.python.org/3/library/tomllib.html'],
 ['configparser','INI configuration','', 'configparser','Read section-based INI files.','https://docs.python.org/3/library/configparser.html'],
 ['requests','HTTP APIs','requests','requests','HTTP requests with explicit timeouts and status checks.','https://requests.readthedocs.io/en/latest/user/quickstart/'],
 ['httpx','HTTPX','httpx','httpx','Modern sync/async HTTP clients.','https://www.python-httpx.org/'],
 ['yaml','PyYAML','PyYAML','yaml','Parse YAML using safe_load.','https://pyyaml.org/wiki/PyYAMLDocumentation'],
 ['jinja2','Jinja2 templates','Jinja2','jinja2','Render trusted configuration templates.','https://jinja.palletsprojects.com/en/stable/api/'],
 ['dotenv','dotenv files','python-dotenv','dotenv','Load local environment settings without overriding existing values.','https://bbc2.github.io/python-dotenv/'],
 ['psutil','System metrics','psutil','psutil','Inspect CPU, memory and processes.','https://psutil.readthedocs.io/'],
 ['paramiko','SSH / SFTP','paramiko','paramiko','SSH commands and file transfers with known-host verification.','https://docs.paramiko.org/en/stable/api/client.html'],
 ['netmiko','Network-device SSH','netmiko','netmiko','Device-aware network CLI automation.','https://github.com/ktbyers/netmiko'],
 ['boto3','AWS SDK','boto3','boto3','Use AWS profiles and the standard credential chain.','https://boto3.amazonaws.com/v1/documentation/api/latest/index.html'],
 ['docker','Docker SDK','docker','docker','Inspect containers through your configured Docker daemon.','https://docker-py.readthedocs.io/en/stable/'],
 ['kubeclient','Kubernetes client','kubernetes','kubernetes.client','Read cluster resources.','https://github.com/kubernetes-client/python'],
 ['kubeconfig','Kubernetes configuration','kubernetes','kubernetes.config','Load an existing kubeconfig context.','https://github.com/kubernetes-client/python'],
 ['git','GitPython','GitPython','git','Inspect local repositories.','https://gitpython.readthedocs.io/en/stable/tutorial.html'],
 ['tenacity','Retry policies','tenacity','tenacity','Bound retries by attempt count and wait duration.','https://tenacity.readthedocs.io/'],
 ['rich','Readable console output','rich','rich','Print readable tables and structured results.','https://rich.readthedocs.io/en/stable/'],
 ['prometheus_client','Prometheus metrics','prometheus-client','prometheus_client','Create and export application metrics.','https://prometheus.github.io/client_python/'],
 ['pytest','pytest','pytest','pytest','Write tests for automation.','https://docs.pytest.org/en/stable/'],
 ['click','Click CLI','click','click','Build larger command-line tools.','https://click.palletsprojects.com/'],
 ['typer','Typer CLI','typer','typer','Type-hinted command-line applications.','https://typer.tiangolo.com/']
];
for(const [id,title,pip,module,hint,url] of PY_OPS_MODULES)PY_PACKAGES[id]={title,pip,module,alias:id==='kubeclient'?'k8s':id==='kubeconfig'?'kube_config':'',hint,url,builtin:!pip};
const opText=(label,value)=>ddField(label,value),opVar=(label,value)=>pyName(label,value),opInt=(label,value)=>ddField(label,String(value),'integer'),opQ=JSON.stringify;
const opSeconds=v=>{if(!Number.isSafeInteger(+v)||+v<1)throw Error('Timeouts and attempt counts must be positive whole numbers.');return v;};
const opJSON=v=>{const value=JSON.parse(v);return 'json.loads('+opQ(JSON.stringify(value))+')';};
const opAdd=(id,label,group,hint,fields,emit,imports)=>pyOp('ops_'+id,label,group,hint,fields,emit,imports);
opAdd('files','Find files','Files & OS','pathlib: list matching files under a directory.',{folder:opText('Directory','.'),pattern:opText('Glob pattern','**/*.log'),result:opVar('Save paths as','files')},v=>v.result+' = [p for p in pathlib.Path('+opQ(v.folder)+').glob('+opQ(v.pattern)+') if p.is_file()]',['pathlib']);
opAdd('read','Read text file','Files & OS','pathlib: read a UTF-8 configuration or log file.',{path:opText('File','app.log'),result:opVar('Save text as','text')},v=>v.result+' = pathlib.Path('+opQ(v.path)+').read_text(encoding="utf-8")',['pathlib']);
opAdd('write','Write text file','Files & OS','pathlib: write a text variable to a UTF-8 file.',{path:opText('Output file','report.txt'),text:opVar('Text variable','text')},v=>'pathlib.Path('+opQ(v.path)+').write_text('+v.text+', encoding="utf-8")',['pathlib']);
opAdd('env','Read environment setting','Files & OS','os: read an environment variable. No credential is stored in the generated script.',{key:opText('Environment variable','APP_ENV'),fallback:opText('Default if missing','development'),result:opVar('Save as','environment')},v=>v.result+' = os.environ.get('+opQ(v.key)+', '+opQ(v.fallback)+')',['os']);
opAdd('copy','Copy a file','Files & OS','shutil.copy2 preserves file metadata where supported.',{source:opText('Source file','source.conf'),destination:opText('Destination file','backup.conf')},v=>'shutil.copy2('+opQ(v.source)+', '+opQ(v.destination)+')',['shutil']);
opAdd('archive','Create ZIP archive','Files & OS','shutil: archive a directory. The output name is given without .zip.',{folder:opText('Directory','reports'),base:opText('Archive name without extension','reports-backup'),result:opVar('Save archive path as','archive')},v=>v.result+' = shutil.make_archive('+opQ(v.base)+', "zip", root_dir='+opQ(v.folder)+')',['shutil']);
opAdd('disk','Inspect disk space','Monitoring','shutil: total, used and free bytes for a path.',{path:opText('Path','.'),result:opVar('Save usage as','disk')},v=>v.result+' = shutil.disk_usage('+opQ(v.path)+')',['shutil']);
opAdd('process','Run command with timeout','CLI & Automation','subprocess: pass one literal argument per line; no implicit shell. Captures stdout/stderr and checks the exit code.',{program:opText('Executable','python'),args:ddField('Arguments, one per line','--version','multiline'),timeout:opInt('Timeout seconds',30),result:opVar('Save completed process as','process')},v=>v.result+' = subprocess.run('+JSON.stringify([v.program,...(v.args?v.args.split('\n'):[])])+', capture_output=True, text=True, check=True, timeout='+opSeconds(v.timeout)+')',['subprocess']);
opAdd('args','Parse CLI options','CLI & Automation','argparse: create --config and --verbose options with generated --help.',{config:opText('Default config file','config.yml'),result:opVar('Arguments variable','args')},v=>'parser = argparse.ArgumentParser(description="Operations helper")\nparser.add_argument("--config", default='+opQ(v.config)+')\nparser.add_argument("--verbose", action="store_true")\n'+v.result+' = parser.parse_args()',['argparse']);
opAdd('log','Configure logging','Monitoring','logging: include time, severity and message.',{level:ddChoice('Log level','INFO',['DEBUG','INFO','WARNING','ERROR']),message:opText('Initial message','Starting operation')},v=>'logging.basicConfig(level=logging.'+v.level+', format="%(asctime)s %(levelname)s %(message)s")\nlogging.info('+opQ(v.message)+')',['logging']);
opAdd('timestamp','UTC timestamp','Monitoring','datetime: use an explicit UTC timezone for reports.',{result:opVar('Save timestamp as','timestamp')},v=>v.result+' = datetime.datetime.now(datetime.timezone.utc).isoformat()',['datetime']);
opAdd('regex','Extract log matches','Monitoring','re: apply a regular expression to a text variable.',{pattern:opText('Regular expression','ERROR.*'),text:opVar('Text variable','text'),result:opVar('Save matches as','matches')},v=>v.result+' = re.findall('+opQ(v.pattern)+', '+v.text+', flags=re.MULTILINE)',['re']);
opAdd('metrics','Inspect CPU and memory','Monitoring','psutil: sample CPU for one second and inspect virtual memory.',{result:opVar('Save metrics as','metrics')},v=>v.result+' = {"cpu_percent": psutil.cpu_percent(interval=1), "memory_percent": psutil.virtual_memory().percent}',['psutil']);
opAdd('processes','List system processes','Monitoring','psutil: collect PID, name and user without terminating anything.',{result:opVar('Save processes as','processes')},v=>v.result+' = [p.info for p in psutil.process_iter(attrs=["pid", "name", "username"], ad_value=None)]',['psutil']);
opAdd('json_read','Read JSON config','Config','json + pathlib: decode a local JSON document.',{path:opText('JSON file','config.json'),result:opVar('Save configuration as','config')},v=>v.result+' = json.loads(pathlib.Path('+opQ(v.path)+').read_text(encoding="utf-8"))',['json','pathlib']);
opAdd('json_write','Write JSON report','Config','json + pathlib: encode a variable as indented JSON.',{path:opText('Output JSON','report.json'),data:opVar('Data variable','data')},v=>'pathlib.Path('+opQ(v.path)+').write_text(json.dumps('+v.data+', indent=2) + "\\n", encoding="utf-8")',['json','pathlib']);
opAdd('yaml_read','Read YAML config','Config','PyYAML: safe_load reads data without constructing arbitrary Python objects.',{path:opText('YAML file','config.yml'),result:opVar('Save configuration as','config')},v=>v.result+' = yaml.safe_load(pathlib.Path('+opQ(v.path)+').read_text(encoding="utf-8"))',['yaml','pathlib']);
opAdd('yaml_write','Write YAML config','Config','PyYAML: serialize a data variable with safe_dump.',{path:opText('Output YAML','output.yml'),data:opVar('Data variable','config')},v=>'pathlib.Path('+opQ(v.path)+').write_text(yaml.safe_dump('+v.data+', sort_keys=False), encoding="utf-8")',['yaml','pathlib']);
opAdd('toml','Read TOML config','Config','tomllib: built into Python 3.11 and later.',{path:opText('TOML file','pyproject.toml'),result:opVar('Save configuration as','config')},v=>'with open('+opQ(v.path)+', "rb") as config_file:\n    '+v.result+' = tomllib.load(config_file)',['tomllib']);
opAdd('ini','Read INI config','Config','configparser: load named sections and options.',{path:opText('INI file','settings.ini'),result:opVar('Save parser as','config')},v=>v.result+' = configparser.ConfigParser()\n'+v.result+'.read('+opQ(v.path)+', encoding="utf-8")',['configparser']);
opAdd('dotenv','Load dotenv settings','Config','python-dotenv: load a local .env file; existing environment variables take precedence.',{path:opText('dotenv file','.env')},v=>'dotenv.load_dotenv('+opQ(v.path)+', override=False)',['dotenv']);
opAdd('template','Render configuration template','Config','Jinja2: load a trusted template and fail on undefined values. Context is JSON data.',{folder:opText('Template directory','templates'),template:opText('Template filename','app.conf.j2'),context:ddField('Context (JSON object)','{"port": 8080, "environment": "production"}','multiline'),result:opVar('Save rendered text as','rendered')},v=>{const data=JSON.parse(v.context);if(!data||Array.isArray(data)||typeof data!=='object')throw Error('Template context must be a JSON object.');return 'template_env = jinja2.Environment(loader=jinja2.FileSystemLoader('+opQ(v.folder)+'), undefined=jinja2.StrictUndefined, autoescape=False)\n'+v.result+' = template_env.get_template('+opQ(v.template)+').render(**'+opJSON(v.context)+')';},['jinja2','json']);
opAdd('http','HTTP GET / API check','APIs','requests: verify TLS, use explicit connect/read timeouts, and raise on unsuccessful status codes.',{url:opText('URL','https://example.com/health'),timeout:opInt('Timeout seconds',10),result:opVar('Response variable','response')},v=>v.result+' = requests.get('+opQ(v.url)+', timeout=(5, '+opSeconds(v.timeout)+'))\n'+v.result+'.raise_for_status()',['requests']);
opAdd('http_json','Decode API response JSON','APIs','requests/HTTPX: turn an existing response into Python data.',{response:opVar('Response variable','response'),result:opVar('Save data as','data')},v=>v.result+' = '+v.response+'.json()',[]);
opAdd('http_post','POST JSON to an API','APIs','requests: encode JSON data and optionally read a bearer token from an environment variable.',{url:opText('URL','https://example.com/api'),payload:ddField('JSON payload','{"name": "example"}','multiline'),token:ddField('Token environment variable (optional)','','text',{required:false}),timeout:opInt('Timeout seconds',10),result:opVar('Response variable','response')},v=>v.result+' = requests.post('+opQ(v.url)+', json='+opJSON(v.payload)+(v.token?', headers={"Authorization": "Bearer " + os.environ['+opQ(v.token)+']}':'')+', timeout=(5, '+opSeconds(v.timeout)+'))\n'+v.result+'.raise_for_status()',['requests','json','os']);
opAdd('httpx','HTTPX request','APIs','httpx: use a client context with a timeout and TLS verification.',{url:opText('URL','https://example.com/health'),timeout:opInt('Timeout seconds',10),result:opVar('Response variable','response')},v=>'with httpx.Client(timeout='+opSeconds(v.timeout)+') as http_client:\n    '+v.result+' = http_client.get('+opQ(v.url)+')\n    '+v.result+'.raise_for_status()',['httpx']);
opAdd('retry','HTTP check with bounded retries','APIs','tenacity + requests: retry request failures only, with a fixed attempt limit.',{url:opText('URL','https://example.com/health'),attempts:opInt('Maximum attempts',3),wait:opInt('Wait between attempts (seconds)',2),result:opVar('Response variable','response')},v=>'for attempt in tenacity.Retrying(stop=tenacity.stop_after_attempt('+opSeconds(v.attempts)+'), wait=tenacity.wait_fixed('+opSeconds(v.wait)+'), retry=tenacity.retry_if_exception_type(requests.RequestException), reraise=True):\n    with attempt:\n        '+v.result+' = requests.get('+opQ(v.url)+', timeout=(5, 10))\n        '+v.result+'.raise_for_status()',['tenacity','requests']);
opAdd('dns','Resolve a hostname','SSH & Network','socket: resolve a hostname using the system resolver.',{host:opText('Hostname','example.com'),result:opVar('Save addresses as','addresses')},v=>v.result+' = sorted({item[4][0] for item in socket.getaddrinfo('+opQ(v.host)+', None)})',['socket']);
opAdd('tcp','Check TCP connectivity','SSH & Network','socket: connect to a host and port with a timeout, then close the connection.',{host:opText('Hostname','localhost'),port:ddField('Port','443','port'),timeout:opInt('Timeout seconds',5)},v=>'with socket.create_connection(('+opQ(v.host)+', '+v.port+'), timeout='+opSeconds(v.timeout)+'):\n    print("TCP connection succeeded")',['socket']);
opAdd('subnet','Check subnet membership','SSH & Network','ipaddress: test whether an address belongs to a CIDR network.',{address:opText('IP address','10.0.0.10'),network:opText('CIDR network','10.0.0.0/24'),result:opVar('Save result as','in_subnet')},v=>v.result+' = ipaddress.ip_address('+opQ(v.address)+') in ipaddress.ip_network('+opQ(v.network)+', strict=False)',['ipaddress']);
opAdd('ssh','Run SSH diagnostic','SSH & Network','Paramiko: uses your SSH agent/keys and known_hosts. Unknown host keys are rejected. Output is intended for short diagnostics.',{host:opText('SSH host','server.example.com'),user:opText('SSH user','admin'),command:opText('Remote command','uptime'),result:opVar('Output variable','ssh_output')},v=>'with paramiko.SSHClient() as ssh:\n    ssh.load_system_host_keys()\n    ssh.set_missing_host_key_policy(paramiko.RejectPolicy())\n    ssh.connect('+opQ(v.host)+', username='+opQ(v.user)+', timeout=10, auth_timeout=10, banner_timeout=10)\n    stdin, stdout, stderr = ssh.exec_command('+opQ(v.command)+', timeout=20)\n    stdin.close()\n    '+v.result+' = stdout.read().decode("utf-8", errors="replace")\n    ssh_errors = stderr.read().decode("utf-8", errors="replace")',['paramiko']);
opAdd('sftp','Download file with SFTP','SSH & Network','Paramiko: retrieve a file using existing SSH keys and verified host keys.',{host:opText('SSH host','server.example.com'),user:opText('SSH user','admin'),remote:opText('Remote file','/var/log/app.log'),local:opText('Local file','app.log')},v=>'with paramiko.SSHClient() as ssh:\n    ssh.load_system_host_keys()\n    ssh.set_missing_host_key_policy(paramiko.RejectPolicy())\n    ssh.connect('+opQ(v.host)+', username='+opQ(v.user)+', timeout=10, auth_timeout=10, banner_timeout=10)\n    with ssh.open_sftp() as sftp:\n        sftp.get_channel().settimeout(30)\n        sftp.get('+opQ(v.remote)+', '+opQ(v.local)+')',['paramiko']);
opAdd('netmiko','Inspect a network device','SSH & Network','Netmiko: run a show command. Password comes from an environment variable; host keys must be known.',{host:opText('Device hostname','switch.example.com'),device:opText('Netmiko device type','cisco_ios'),user:opText('Username','admin'),env:opText('Password environment variable','NET_PASSWORD'),command:opText('Show command','show version'),result:opVar('Save output as','device_output')},v=>'with netmiko.ConnectHandler(device_type='+opQ(v.device)+', host='+opQ(v.host)+', username='+opQ(v.user)+', password=os.environ['+opQ(v.env)+'], ssh_strict=True, system_host_keys=True, conn_timeout=10, auth_timeout=10, banner_timeout=10) as device:\n    '+v.result+' = device.send_command('+opQ(v.command)+', read_timeout=30)',['netmiko','os']);
opAdd('aws','Inspect AWS identity','Cloud & Containers','boto3: use an existing named profile, or the default credential chain if left blank.',{profile:ddField('AWS profile (optional)','','text',{required:false}),region:opText('AWS region','us-east-1'),result:opVar('Save identity as','identity')},v=>'aws = boto3.Session(region_name='+opQ(v.region)+(v.profile?', profile_name='+opQ(v.profile):'')+')\n'+v.result+' = aws.client("sts").get_caller_identity()',['boto3']);
opAdd('s3','List S3 objects with pagination','Cloud & Containers','boto3: list keys under a prefix using the standard credential chain and paginator.',{bucket:opText('Bucket name','example-bucket'),prefix:ddField('Key prefix (optional)','','text',{required:false}),result:opVar('Save object keys as','keys')},v=>'s3 = boto3.client("s3")\n'+v.result+' = []\nfor page in s3.get_paginator("list_objects_v2").paginate(Bucket='+opQ(v.bucket)+', Prefix='+opQ(v.prefix)+'):\n    '+v.result+'.extend(item["Key"] for item in page.get("Contents", []))',['boto3']);
opAdd('containers','List Docker containers','Cloud & Containers','Docker SDK: inspect the configured local/remote daemon; close the client afterwards.',{all:ddChoice('Containers','running',['running','all']),result:opVar('Save inventory as','containers')},v=>'docker_client = docker.from_env(timeout=15)\ntry:\n    '+v.result+' = [{"id": c.short_id, "name": c.name, "status": c.status} for c in docker_client.containers.list(all='+(v.all==='all'?'True':'False')+')]\nfinally:\n    docker_client.close()',['docker']);
opAdd('pods','List Kubernetes pods','Cloud & Containers','Kubernetes SDK: read pods from an existing kubeconfig context, with a request timeout.',{context:ddField('Kubeconfig context (optional)','','text',{required:false}),namespace:opText('Namespace','default'),result:opVar('Save pod list as','pods')},v=>'kube_config.load_kube_config(context='+(v.context?opQ(v.context):'None')+')\nwith k8s.ApiClient() as api_client:\n    '+v.result+' = k8s.CoreV1Api(api_client).list_namespaced_pod(namespace='+opQ(v.namespace)+', _request_timeout=20).items',['kubeclient','kubeconfig']);
opAdd('git','Inspect Git repository','CLI & Automation','GitPython: report the current commit and whether local changes exist.',{path:opText('Repository path','.'),result:opVar('Save repository status as','repo_status')},v=>'with git.Repo('+opQ(v.path)+') as repo:\n    '+v.result+' = {"commit": repo.head.commit.hexsha, "dirty": repo.is_dirty(untracked_files=True)}',['git']);
opAdd('hash','Calculate SHA-256 checksum','Files & OS','hashlib: read the file in chunks instead of loading it all into memory.',{path:opText('File path','artifact.tar.gz'),result:opVar('Save checksum as','checksum')},v=>'hasher = hashlib.sha256()\nwith open('+opQ(v.path)+', "rb") as checksum_file:\n    for chunk in iter(lambda: checksum_file.read(1048576), b""):\n        hasher.update(chunk)\n'+v.result+' = hasher.hexdigest()',['hashlib']);
opAdd('sqlite','Query SQLite read-only','Config','sqlite3: open an existing database in read-only mode and bind literal parameters.',{path:opText('Database file','inventory.db'),query:opText('SQL query','SELECT name FROM sqlite_master WHERE type = ?'),params:ddField('Parameters (JSON array)','["table"]','multiline'),result:opVar('Save rows as','rows')},v=>{if(!Array.isArray(JSON.parse(v.params)))throw Error('SQL parameters must be a JSON array.');return 'db = sqlite3.connect(pathlib.Path('+opQ(v.path)+').resolve().as_uri() + "?mode=ro", uri=True, timeout=10)\ntry:\n    '+v.result+' = db.execute('+opQ(v.query)+', '+opJSON(v.params)+').fetchall()\nfinally:\n    db.close()';},['sqlite3','pathlib','json']);
opAdd('inventory','Read CSV inventory','Config','csv: read column names and rows with DictReader.',{path:opText('CSV file','hosts.csv'),result:opVar('Save rows as','hosts')},v=>'with open('+opQ(v.path)+', newline="", encoding="utf-8") as inventory_file:\n    '+v.result+' = list(csv.DictReader(inventory_file))',['csv']);
opAdd('parallel','Map work across threads','CLI & Automation','concurrent.futures: call an existing function for each item, retaining input order.',{function:opVar('Existing function','check_host'),items:opVar('Items variable','hosts'),workers:opInt('Worker count',4),result:opVar('Save results as','results')},v=>'with concurrent.futures.ThreadPoolExecutor(max_workers='+opSeconds(v.workers)+') as executor:\n    '+v.result+' = list(executor.map('+v.function+', '+v.items+'))',['futures']);
opAdd('rich','Print structured results','Monitoring','Rich: display an existing Python value in the console.',{data:opVar('Variable to display','data')},v=>'rich.print('+v.data+')',['rich']);
opAdd('prometheus','Write Prometheus textfile metric','Monitoring','prometheus_client: write a gauge file for an existing node-exporter textfile collector directory.',{path:opText('Output .prom file','job.prom'),name:opText('Metric name','ops_job_success'),help:opText('Metric description','Last job succeeded'),value:opInt('Gauge value',1)},v=>{if(!/^[a-zA-Z_:][a-zA-Z0-9_:]*$/.test(v.name))throw Error('Use a valid Prometheus metric name.');return 'registry = prometheus_client.CollectorRegistry()\ngauge = prometheus_client.Gauge('+opQ(v.name)+', '+opQ(v.help)+', registry=registry)\ngauge.set('+v.value+')\nprometheus_client.write_to_textfile('+opQ(v.path)+', registry)';},['prometheus_client']);
// Offer new operation blocks in every compatible script body, not in argument lists.
const pyOpsKeys=Object.keys(PY_OPS).filter(k=>k.startsWith('ops_'));for(const def of [pyP,...Object.values(pyP.types)]){const slots=def===pyP?[pyP.root]:Object.values(def.slots);for(const slot of slots)if(slot.accept.includes('variable'))slot.accept=[...new Set([...slot.accept,...pyOpsKeys])];}
Object.assign(PY_STARTERS,{
 'API health check':p=>[ddNode(p,'ops_log'),ddNode(p,'ops_http'),ddNode(p,'print',{mode:'expression',value:'response.status_code'})],
 'Host health report':p=>[ddNode(p,'ops_timestamp'),ddNode(p,'ops_metrics'),ddNode(p,'ops_disk'),ddNode(p,'print',{mode:'variable',value:'metrics'}),ddNode(p,'print',{mode:'variable',value:'disk'})],
 'YAML → JSON':p=>[ddNode(p,'ops_yaml_read'),ddNode(p,'ops_json_write',{data:'config'})],
 'Kubernetes pod inventory':p=>[ddNode(p,'ops_pods'),ddNode(p,'py_for',{target:'pod',iterable:'pods'},{body:[ddNode(p,'print',{mode:'expression',value:'pod.metadata.name'})]})]
});
