let sxTimer=null;
function sxCancel(){clearTimeout(sxTimer);sxTimer=null;}
function sxSelection(el){return {start:el.selectionStart,end:el.selectionEnd,top:el.scrollTop,focus:document.activeElement===el};}
function sxRestore(id,s){const el=document.getElementById(id);if(!el||!s)return;if(s.focus)el.focus();el.setSelectionRange(s.start,s.end);el.scrollTop=s.top;}
function sxBind(preview,input,sync){preview.readOnly=false;preview.spellcheck=false;preview.oninput=input;preview.onkeydown=e=>{if(e.key==='Tab'){e.preventDefault();preview.setRangeText('  ',preview.selectionStart,preview.selectionEnd,'end');preview.dispatchEvent(new Event('input'));}if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();sync();}};}
function sxMessage(){const status=document.getElementById('sx-status');if(!status)return;const raw=JSON.stringify(ddState.blocks).includes('"type":"sx_code"');status.textContent=ddState.sxDirty?(ddState.sxError||'Typing… blocks update after a pause. Your text is saved.'):(raw?'Synced. Unrecognized syntax is kept in Custom code blocks; review it with the target tool.':'Code and blocks are synced. Typing updates blocks; block edits regenerate formatting.'+(['yaml','github-actions','gitlab-ci'].includes(ddState.profile)?' YAML comments and anchors are preserved until you edit a block.':''));document.querySelector('#dk-root .dd-editor').inert=!!ddState.sxDirty;}
function sxSync(){sxCancel();if(!ddState?.sxDirty)return true;const preview=document.getElementById('dd-preview'),selection=preview&&sxSelection(preview);try{const nodes=sxParse(ddProfile(),ddState.sxCode,ddState.blocks),errors=ddValidate(ddProfile(),nodes);if(errors.length)throw Error(errors[0]);ddState.blocks=nodes;ddState.sxSignature=sxSignature(nodes);ddState.sxDirty=false;delete ddState.sxError;ddSave();ddRender();sxRestore('dd-preview',selection);return true;}catch(e){ddState.sxError=e.message+' Your text is saved; fix it or keep it as a Custom code block.';ddSave();sxMessage();return false;}}
const sxBaseOutput=ddOutput;
ddOutput=function(){if(ddState?.profile==='python')return sxBaseOutput();if(typeof ddState?.sxCode==='string'&&(ddState.sxDirty||ddState.sxSignature===sxSignature(ddState.blocks)))return {text:ddState.sxCode,errors:ewFilenameErrors(ddState.filename),filename:ddState.filename};delete ddState.sxCode;delete ddState.sxSignature;return sxBaseOutput();};
const sxBaseRefresh=ddRefresh;
ddRefresh=function(){sxBaseRefresh();if(ddState?.profile!=='python')sxMessage();};
// Shared change coordination lives in editor-workspace.js.
const sxBaseRender=ddRender;
ddRender=function(){sxCancel();sxBaseRender();if(ddState.profile==='python')return;const preview=document.getElementById('dd-preview');preview.setAttribute('aria-label','Editable file preview');preview.before(dkEl('div','py-code-label','CODE · EDITABLE'));const status=dkEl('p','dk-help');status.id='sx-status';status.setAttribute('role','status');preview.after(status);const row=dkEl('div','dk-actions');row.append(dkBtn('Sync code to blocks now',()=>{if(!ddState.sxDirty){ddRemember();ddState.sxCode=preview.value;ddState.sxDirty=true;}sxSync();}),dkBtn('Keep as Custom code',()=>{ddRemember();const text=preview.value;ddState.blocks=[sxRaw(ddProfile(),text)];ddState.sxCode=text;ddState.sxSignature=sxSignature(ddState.blocks);ddState.sxDirty=false;ddSave();ddRender();}));status.after(row);let typing=false;
 sxBind(preview,()=>{if(!typing){ddRemember();typing=true;}ddState.sxCode=preview.value;ddState.sxDirty=true;delete ddState.sxError;ddSave();sxMessage();document.getElementById('dd-undo').disabled=false;sxCancel();const state=ddState;sxTimer=setTimeout(()=>{if(ddState===state&&document.getElementById('dd-preview')===preview)sxSync();},700);},sxSync);sxMessage();
};
const sxHome=dkHome;dkHome=function(sheet){sxCancel();sxHome(sheet);};
const sxClose=dkClose;dkClose=function(){sxCancel();sxClose();};
const sxFileParse=dfParse;dfParse=function(name,text,mode='auto'){if(mode==='auto'){const id=/\.tf$/i.test(name)?'terraform':/\.sh$/i.test(name)?'bash':/\.ps1$/i.test(name)?'powershell':/\.sql$/i.test(name)?'sql':/^Dockerfile(?:\..*)?$/i.test(name)?'dockerfile':/^Jenkinsfile$/i.test(name)?'jenkins':null;if(id){const p=DD_PROFILES[id];let nodes,error;try{nodes=sxParse(p,text,[]);const errors=ddValidate(p,nodes);if(errors.length)throw Error(errors[0]);}catch(e){nodes=[sxRaw(p,text)];error=e.message;}return {profile:id,nodes,state:{sxCode:text,sxSignature:sxSignature(nodes),sxDirty:false,...(error?{sxImportNote:error}:{})}};}}return sxFileParse(name,text,mode);};
/* Quick recipes: proven field edits retain controls; other edits become source-line blocks. */
function sxQuickSync(){sxCancel();if(!dkActive?.sxDirty)return;const preview=document.getElementById('dk-preview'),selection=sxSelection(preview),text=dkActive.sxCode;const fake={generate:blocks=>{const current=dkActive.blocks;dkActive.blocks=blocks;try{return sxQuickOutput().text;}finally{dkActive.blocks=current;}},types:Object.fromEntries(dkActive.blocks.map(b=>[b.key,{fields:Object.fromEntries(Object.keys(b.values).map(k=>[k,{type:'multiline'}])),slots:{}}])),root:{accept:dkActive.blocks.map(b=>b.key),min:0,max:Infinity}};
 // Quick recipe values have arrays and booleans too; retain a recipe only for proven scalar changes.
 const previous=dkActive.blocks.map((b,i)=>({id:String(i),type:b.key,values:b.values,slots:{}}));fake.generate=nodes=>{const old=dkActive.blocks;dkActive.blocks=nodes.map(n=>({key:n.type,values:n.values}));try{return sxQuickOutput().text;}finally{dkActive.blocks=old;}};
 let matched=null;try{matched=sxFieldEdit(fake,previous,text);}catch{}
 if(matched)dkActive.blocks=matched.map(n=>({key:n.type,values:n.values}));else{dkActive.sxFilename=sxQuickOutput().filename;dkActive.example=dkActive.example||{description:'Custom source. Edit text here or use the line blocks; Undo restores the guided recipe.',original:text};dkActive.blocks=text.split('\n').map(line=>({key:'line',values:{text:line}}));}delete dkActive.sxDirty;delete dkActive.sxCode;dkSave();dkRender();sxRestore('dk-preview',selection);
}
const sxQuickOutput=dkOutput;dkOutput=function(){const out=sxQuickOutput();if(dkActive?.sxDirty){out.text=dkActive.sxCode;out.errors=[];}if(dkActive?.sxFilename)out.filename=dkActive.sxFilename;return out;};
const sxQuickChange=dkChange;dkChange=function(fn){if(dkActive?.sxDirty)sxQuickSync();sxQuickChange(fn);};
const sxQuickRender=dkRender;dkRender=function(){sxCancel();sxQuickRender();const preview=document.getElementById('dk-preview'),status=dkEl('p','dk-help','Edit here or in blocks. Supported field edits retain their controls; other syntax becomes editable source-line blocks. Undo restores the previous builder.');preview.setAttribute('aria-label','Editable command preview');preview.after(status);status.after(dkBtn('Sync code to blocks now',sxQuickSync));let typing=false;sxBind(preview,()=>{if(!typing){dkRemember();typing=true;}dkActive.sxCode=preview.value;dkActive.sxDirty=true;dkSave();document.getElementById('dk-undo').disabled=false;document.querySelector('#dk-root .dk-editor').inert=true;sxCancel();const current=dkActive;sxTimer=setTimeout(()=>{if(current===dkActive&&document.getElementById('dk-preview')===preview)sxQuickSync();},700);},sxQuickSync);document.querySelector('#dk-root .dk-editor').inert=!!dkActive.sxDirty;};
/* Ansible uses a data tree already, so YAML edits map directly to its named blocks. */
function sxAnsibleSync(){sxCancel();if(!abState?.sxDirty)return true;const selection=sxSelection(document.getElementById('ab-preview'));try{const doc=axRead(abState.sxCode);const path=axChangedPath(abState.doc,doc,abState.path);abState.doc=doc;abState.path=path;abState.sxSignature=JSON.stringify(doc);abState.sxDirty=false;delete abState.sxError;abSave();abRender();sxRestore('ab-preview',selection);return true;}catch(e){abState.sxError=e.message;abSave();sxAnsibleStatus();axSuggestions();return false;}}
function sxAnsibleStatus(){const status=document.getElementById('sx-ansible-status');if(status)status.textContent=abState.sxDirty?(abState.sxError||'Typing… YAML blocks update after a pause. Text is saved.'):'YAML and blocks are synced. Code formatting is kept until you edit a block.';for(const el of document.querySelectorAll('#ab-dialog .ab-canvas, #ab-dialog .ab-outline'))el.inert=!!abState.sxDirty;axSuggestions();}
function axRead(text){const docs=sxSafeData(text);if(docs.length!==1)throw Error('This builder needs one YAML document.');const doc=docs[0],list=['playbook','tasks','handlers'].includes(abState.kind);if(list?!Array.isArray(doc):!anMap(doc))throw Error(list?'This file needs a YAML list.':'This file needs a YAML mapping.');function entries(items){if(!Array.isArray(items))return;for(const item of items){if(!anMap(item))throw Error('Each play or task needs named fields, for example - name: "".');for(const key of ['tasks','handlers','block','rescue','always','pre_tasks','post_tasks'])entries(item[key]);}}if(list)entries(doc);return doc;}
function axChangedPath(before,after,previous){
 function added(a,b,path){if(Array.isArray(b)){for(let i=0;i<b.length;i++){if((!Array.isArray(a)||i>=a.length)&&b[i]&&typeof b[i]==='object')return [...path,i];const found=added(a?.[i],b[i],[...path,i]);if(found)return found;}}else if(anMap(b))for(const key of Object.keys(b)){const found=added(a?.[key],b[key],[...path,key]);if(found)return found;}return null;}
 const addition=added(before,after,[]);if(addition)return addition;
 function changed(a,b,path){if(JSON.stringify(a)===JSON.stringify(b))return null;if(Array.isArray(b)){for(let i=0;i<b.length;i++)if(!Array.isArray(a)||i>=a.length)return b[i]&&typeof b[i]==='object'?[...path,i]:path;for(let i=0;i<b.length;i++){const found=changed(a?.[i],b[i],[...path,i]);if(found)return found;}return path;}if(anMap(b)){for(const key of Object.keys(b)){const found=changed(a?.[key],b[key],[...path,key]);if(found)return found;}return path;}return path.slice(0,-1);}
 const found=changed(before,after,[]);if(found)return found;let path=[...previous];while(path.length&&path.reduce((v,k)=>v?.[k],after)===undefined)path.pop();return path;
}
function axCompletions(text){
 const candidates=[],lines=text.split('\n');const add=(label,code)=>{if(code===text||candidates.some(c=>c.code===code))return;try{axRead(code);candidates.push({label,code});}catch{}};
 for(let index=0;index<lines.length;index++){
  const line=lines[index];const replace=(label,value)=>{const copy=[...lines];copy[index]=value;add(label,copy.join('\n'));};
  if(/^(\s*(?:-\s+)?)(?:name|hosts|tasks|handlers|vars|become|gather_facts)\s*$/.test(line))replace('Complete missing colon',line.trimEnd()+':'+(/\bname\s*$/.test(line)?' ""':''));
  if(/^(\s*(?:-\s+)?)(name|hosts)\s+[^:]+$/.test(line))replace('Add colon after field name',line.replace(/\b(name|hosts)\s+/, '$1: '));
  const value=/^\s*(?:-\s+)?[\w.]+:\s*(["'])/.exec(line);if(value){const quote=value[1];let open=false;for(let i=line.indexOf(':')+1;i<line.length;i++){if(quote==='"'&&line[i]==='\\'){i++;continue;}if(line[i]===quote){if(quote==="'"&&open&&line[i+1]==="'"){i++;continue;}open=!open;}}if(open)replace('Close unfinished '+(quote==='"'?'double':'single')+' quote',line+quote);}
 }
 // Only propose a bracket repair when the complete candidate passes the YAML parser.
 const stack=[];let quote=null,comment=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='\n')comment=false;if(comment)continue;if(quote){if(quote==='"'&&c==='\\'){i++;continue;}if(c===quote){if(quote==="'"&&text[i+1]==="'"){i++;continue;}quote=null;}continue;}if(c==='#'){comment=true;continue;}if(c==='"'||c==="'"){quote=c;continue;}if(c==='['||c==='{')stack.push(c==='['?']':'}');else if(c===']'||c==='}')stack.pop();}if(!quote&&stack.length)add('Close unfinished list or mapping',text.trimEnd()+stack.reverse().join('')+'\n');
 return candidates.slice(0,4);
}
function axSuggestions(){if(!document.getElementById('sx-ansible-status'))return;let host=document.getElementById('ax-completions');if(!host){host=dkEl('section','ab-hint');host.id='ax-completions';host.setAttribute('aria-label','YAML completion suggestions');document.getElementById('sx-ansible-status').after(host);}host.replaceChildren();if(!abState.sxDirty||!abState.sxError)return;const source=abState.sxCode,candidates=axCompletions(source);host.append(dkEl('strong','',candidates.length?'Suggested completion — review before applying':'Keep typing to fix the YAML; your last valid blocks are retained.'));for(const item of candidates){const card=dkEl('details');card.append(dkEl('summary','',item.label),dkEl('pre','',item.code));const button=abButton('Apply: '+item.label,()=>{if(abState.sxCode!==source)return;abHistory();abState.sxCode=item.code;delete abState.sxError;document.getElementById('ab-preview').value=item.code;abSave();sxAnsibleSync();});card.append(button);card.open=true;host.append(card);}}
const sxAbRefresh=abRefresh;abRefresh=function(){sxAbRefresh();if(typeof abState?.sxCode==='string'&&(abState.sxDirty||abState.sxSignature===JSON.stringify(abState.doc)))document.getElementById('ab-preview').value=abState.sxCode;else{delete abState.sxCode;delete abState.sxSignature;}sxAnsibleStatus();if(abState.sxDirty){document.getElementById('ab-copy').disabled=true;document.getElementById('ab-download').disabled=true;}};
const sxAbRender=abRender;abRender=function(){sxCancel();sxAbRender();const preview=document.getElementById('ab-preview');let status=document.getElementById('sx-ansible-status');if(!status){status=dkEl('p','ab-hint');status.id='sx-ansible-status';status.setAttribute('role','status');preview.after(status);status.after(abButton('Sync code to blocks now',sxAnsibleSync));}preview.setAttribute('aria-label','Editable Ansible YAML');let typing=false;sxBind(preview,()=>{if(!typing){abHistory();typing=true;}abState.sxCode=preview.value;abState.sxDirty=true;delete abState.sxError;abSave();sxAnsibleStatus();document.getElementById('ab-undo').disabled=false;document.getElementById('ab-copy').disabled=true;document.getElementById('ab-download').disabled=true;sxCancel();const current=abState;sxTimer=setTimeout(()=>{if(current===abState)sxAnsibleSync();},700);},sxAnsibleSync);sxAnsibleStatus();};
const sxAbEdit=abEdit;abEdit=function(fn){if(abState?.sxDirty&&!sxAnsibleSync())return;sxAbEdit(fn);};
/* The original command modal also gets an editable preview and a matching source block. */
const sxCommandString=buildCommandString;
buildCommandString=function(){return typeof currentBuilder?.sxCommand==='string'?currentBuilder.sxCommand:sxCommandString();};
function sxCommandSync(){sxCancel();if(!currentBuilder)return;const preview=document.getElementById('sx-command-preview'),text=preview.value,before=sxCommandString();if(text===before){delete currentBuilder.sxCommand;renderBuilderBody(currentBuilder.def);return;}
 let matched=false;for(const group of ['values','flagValues']){for(const key of Object.keys(currentBuilder[group]||{})){const old=currentBuilder[group][key];if(typeof old!=='string'||!old)continue;const pos=before.indexOf(old);if(pos<0||!text.startsWith(before.slice(0,pos))||!text.endsWith(before.slice(pos+old.length)))continue;const value=text.slice(pos,text.length-(before.length-pos-old.length));currentBuilder[group][key]=value;if(sxCommandString()===text){matched=true;break;}currentBuilder[group][key]=old;}if(matched)break;}
 if(matched){delete currentBuilder.sxCommand;renderBuilderBody(currentBuilder.def);return;}
 currentBuilder.sxCommand=text;const body=document.getElementById('builder-body');body.replaceChildren();const label=dkEl('label','dk-field','Custom command block'),input=dkEl('textarea','dk-input');input.value=text;input.rows=6;input.setAttribute('aria-label','Custom command block');input.oninput=()=>{currentBuilder.sxCommand=input.value;preview.value=input.value;};label.append(input);body.append(label,dkEl('p','dk-help','This command contains syntax outside the original options. It is preserved as one editable block.'),dkBtn('Restore guided options',()=>{delete currentBuilder.sxCommand;renderBuilderBody(currentBuilder.def);updateBuilderPreview();}));
}
const sxCommandPreview=updateBuilderPreview;updateBuilderPreview=function(){sxCommandPreview();const old=document.getElementById('builder-preview-text');if(!old)return;let preview=document.getElementById('sx-command-preview');if(!preview){preview=dkEl('textarea','dk-input');preview.id='sx-command-preview';preview.rows=4;preview.setAttribute('aria-label','Editable command');old.after(preview);preview.after(dkBtn('Sync command to blocks',sxCommandSync));}old.hidden=true;preview.value=buildCommandString();sxBind(preview,()=>{currentBuilder.sxCommand=preview.value;sxCancel();const current=currentBuilder;sxTimer=setTimeout(()=>{if(current===currentBuilder)sxCommandSync();},700);},sxCommandSync);};
