/* Every tool has a guide, local workflow and primary documentation link. */
const DK_GUIDES={
 gam7:['Google Workspace reports','Choose an account scope, select the report, then inspect the output before any bulk change.','GAM runs with the permissions of its configured credentials. Use reports to verify the exact user set; CSV input may affect many accounts.','gam version\ngam print users','https://github.com/GAM-team/GAM/wiki'],
 python:['Small, reusable scripts','Start with inputs, add a processing step, then print or write the result.','Indentation defines blocks. Use a virtual environment for project dependencies and pathlib for portable file paths.','python --version\npython -m py_compile helper.py','https://docs.python.org/3/tutorial/'],
 excel:['Formulas without guesswork','Choose the calculation, pick the source cells, and fill in the result or fallback.','Ranges and text are different: A2:A20 is a reference; "missing" is text. Use $ to lock rows or columns. Function availability and separators depend on Excel version and locale.','Use Excel’s Evaluate Formula tool to inspect intermediate results.','https://support.microsoft.com/en-us/excel/functions'],
 bash:['Shell commands and scripts','Separate the command, its options and its arguments. Quote paths and literal values.','Single quotes preserve literal text. A pipe feeds stdout into the next command; && runs the next command only after success. Bash is distinct from Windows CMD.','bash -n helper.sh\nhelp read','https://www.gnu.org/software/bash/manual/bash.html'],
 powershell:['Pipelines of objects','Choose a source, filter its objects, select properties, then export or display them.','PowerShell pipelines carry objects. Use Select-Object before Export-Csv; formatting commands produce display-oriented objects. -LiteralPath treats wildcard characters literally.','Get-Help Get-ChildItem -Full\nGet-Command Get-ChildItem -Syntax','https://learn.microsoft.com/en-us/powershell/scripting/overview'],
 cmd:['Windows command files','Choose a command and paths, then add only the switches you need.','CMD, PowerShell and Bash have different quoting. Batch files use %% variables where an interactive prompt uses %. These recipes target Windows CMD unless stated otherwise.','help\nrobocopy /?','https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/windows-commands'],
 git:['Review before recording changes','Inspect status and diffs, select files, write a commit, then synchronize deliberately.','Working files, staging and commits are separate. A path after -- is a pathspec. Rewriting history affects other people who have already fetched it.','git status --short\ngit diff\ngit diff --staged','https://git-scm.com/docs'],
 docker:['Containers and Compose files','Choose an image, add ports or environment values, then define storage if it must persist.','A published port maps host:container. A bind mount uses a host path; a named volume is managed by Docker. Compose service names provide discovery on the project network.','docker compose config\ndocker compose ps','https://docs.docker.com/reference/compose-file/'],
 sql:['Queries as ordered clauses','Start with SELECT and FROM, add filters, then ordering and a limit.','Identifiers, values and SQL expressions are different. The query recipe targets SQLite/PostgreSQL-style SELECT syntax; SQL Server and other dialects differ. Parameterize application queries.','Inspect a SELECT result and use your database’s EXPLAIN facility.','https://sqlite.org/lang_select.html'],
 linux:['Understand the host first','Identify the distribution and service manager, inspect state, then make a scoped change.','Package names and managers differ by distribution. systemctl applies to systemd hosts. Administrative changes may need elevated privileges.','cat /etc/os-release\nsystemctl --version','https://www.freedesktop.org/software/systemd/man/latest/systemctl.html'],
 terraform:['Infrastructure as configuration','Define inputs and resources, format the files, initialize providers, then review a plan.','State connects resources to remote objects. A plan may include replacements or deletions. The built-in file recipe uses Terraform’s supported .tf.json syntax to avoid hand-written HCL.','terraform fmt\nterraform init\nterraform validate\nterraform plan','https://developer.hashicorp.com/terraform/language/syntax/json'],
 ansible:['Automation in reusable blocks','Name the play, choose its inventory hosts, then add tasks and modules.','Tasks run in order. Handlers run when notified by a changed task. YAML formatting is automatic; Ansible runtime checks still require your actual inventory and installed modules.','ansible-playbook -i inventory.yml site.yml --syntax-check','https://docs.ansible.com/projects/ansible/latest/playbook_guide/index.html'],
 k8s:['Kubernetes manifests','Name the workload, select its image, then add ports, replicas and resource settings.','A Deployment selector must match its Pod labels. A Service selects Pods by labels. Check your current context and namespace before applying a manifest.','kubectl config current-context\nkubectl apply --dry-run=client -f deployment.yml','https://kubernetes.io/docs/concepts/workloads/controllers/deployment/'],
 aws:['Explicit AWS scope','Choose an operation and resource, then set profile and region when needed.','Profiles choose credentials; regions choose the regional endpoint. Read operations still need permissions. AWS examples use your locally configured CLI.','aws --version\naws sts get-caller-identity','https://docs.aws.amazon.com/cli/latest/reference/'],
 azure:['Account, group, resource','Confirm your subscription, choose the resource group, then inspect or configure a resource.','A resource group is not a subscription. CLI output can be filtered with --query and formatted with --output. Generated commands do not log you in.','az version\naz account show','https://learn.microsoft.com/en-us/cli/azure/reference-index'],
 gcloud:['Projects and configurations','Select the active identity and project, then choose a service and resource.','A project is separate from an account or region. Check configuration before commands that create, update or delete resources.','gcloud version\ngcloud config list\ngcloud auth list','https://cloud.google.com/sdk/gcloud/reference'],
 vim:['Know which mode you are in','Use Normal mode to navigate, Insert mode to type, and : commands to operate on the file.','Press Esc to return to Normal mode. A substitution range controls which lines change; the c flag asks before each replacement.','Vim: :help\nVim: :help :substitute','https://vimhelp.org/change.txt.html#%3Asubstitute'],
 tmux:['Sessions, windows, panes','Create a named session, add windows or panes, and detach without ending their processes.','The default key prefix is Ctrl+b. A tmux command and a prefix-key shortcut are different ways of controlling the same server.','tmux list-sessions\ntmux list-commands','https://github.com/tmux/tmux/wiki/Getting-Started'],
 regex:['Build and test a pattern','Combine literals, character classes and repetition; test against representative text.','This tester uses the browser’s JavaScript regex engine. PCRE, Python, grep and .NET differ. Tests run in a short-lived worker with a time limit.','Try matching and nonmatching examples; inspect the match boundaries.','https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp'],
 ssh:['Connections, keys and tunnels','Choose an alias or host, user and port; add a key or forwarding rule only when needed.','OpenSSH client configuration belongs in ~/.ssh/config. IdentityFile is a private-key path on the client. Never paste a private key into a builder.','ssh -G my-server\nssh -V','https://man.openbsd.org/ssh_config'],
 curl:['HTTP requests with clear inputs','Start with a URL, then choose a method, headers and a body.','A request header describes the request, while -I asks for a HEAD request. Quoting must match the shell used to run cURL. The workbench does not send requests.','curl --version\ncurl --help all','https://curl.se/docs/manpage.html'],
 net:['Network diagnostics in layers','Check local addresses, DNS, routing and reachability before investigating application traffic.','ICMP ping, TCP connectivity and HTTP health are different tests. Some diagnostic commands require privileges and available platform-specific tools.','ip addr\nip route\nnslookup example.com','https://nmap.org/book/man.html'],
 cisco:['Cisco IOS / IOS-XE context','Inspect the device in EXEC mode, enter the appropriate configuration context, then verify changes.','Interface names and available commands depend on hardware and software. Configuration changes and saving startup configuration are separate actions.','show version\nshow ip interface brief\nshow running-config','https://www.cisco.com/c/en/us/support/ios-nx-os-software/ios-xe/series.html'],
 aruba:['Choose the Aruba operating system','Identify OS-Switch versus AOS-CX before choosing commands from the reference.','Do not combine OS-Switch and AOS-CX interface syntax. The diagnostic recipe below is explicitly OS-Switch; use the appropriate reference section for CX.','show version\nshow system','https://arubanetworking.hpe.com/techdocs/'],
 fortigate:['FortiOS configuration contexts','Inspect the system, enter the relevant config table, edit its object and verify the result.','config, edit, set, next and end describe different context levels. Interface, policy and VDOM scope must match the device you are managing.','get system status\nget system performance status','https://docs.fortinet.com/product/fortigate'],
 juniper:['Candidate versus active configuration','Inspect operational state, enter configuration mode, compare changes, then validate the candidate.','Junos keeps a candidate configuration until commit. commit check validates it; commit confirmed can provide an automatic rollback window.','show version\nshow interfaces terse','https://www.juniper.net/documentation/us/en/software/junos/cli/'],
 netgear:['Use the exact switch family','Identify the model and firmware, then use its matching ProSAFE or Omada reference section.','This cheatsheet covers multiple vendors. The diagnostic recipe is for Netgear ProSAFE. TP-Link commands should be customized from the TP-Link section, not mixed into a Netgear session.','show version\nshow interface all','https://www.netgear.com/support/'],
 npm:['Project scripts and dependencies','Describe the project in package.json, add scripts, then install dependencies and commit the lockfile.','npm scripts run in a shell. npm ci expects a matching lockfile; package.json must be valid JSON. Dependency installation and script execution happen outside DevKit.','npm --version\nnpm run\nnpm ls --depth=0','https://docs.npmjs.com/cli/v11/configuring-npm/package-json/']
};
for(const [key,guide] of Object.entries(DK_GUIDES)){
 const sheet=SHEETS[key];if(!sheet)continue;
 sheet.sections.push({id:'dk-guide-'+key,title:'Workflow & troubleshooting',color:sheet.iconBg,cmds:[{cmd:guide[3],desc:guide[1]+' '+guide[2],platform:'Workflow guide'}]});
}
