/* Ranked offline discovery across commands, schemas, editors, recipes and Python tooling. */
const US_STOP=new Set(['a','an','and','do','for','how','i','in','me','my','of','please','the','to','want','with']);
const US_SYNONYMS={
 cicd:['pipeline','workflow','build','test','deploy'],pipeline:['cicd','workflow','build','deploy'],workflow:['pipeline','automation','cicd'],
 kubernetes:['k8s','cluster','pod','manifest'],k8s:['kubernetes','cluster','pod','manifest'],container:['docker','image','compose'],docker:['container','image','compose'],
 terraform:['iac','infrastructure','provision'],infrastructure:['terraform','iac','provision','cloud'],ansible:['playbook','configuration','fleet'],playbook:['ansible','yaml','hosts'],
 excel:['xlsx','spreadsheet','pandas','openpyxl'],xlsx:['excel','spreadsheet','openpyxl'],spreadsheet:['excel','xlsx','pandas'],
 network:['dns','tcp','connectivity','route'],connectivity:['network','tcp','ping','dns'],monitor:['metrics','observability','health'],observability:['monitor','metrics','logs','sre'],
 restart:['reload','systemctl'],service:['daemon','systemctl'],permissions:['chmod','chown','access'],files:['file','path','directory'],
 github:['actions','workflow','pipeline'],gitlab:['ci','pipeline'],jenkins:['pipeline','groovy'],powershell:['windows','pwsh','script'],bash:['shell','linux','script'],
 sql:['query','database','table'],python:['script','automation'],backup:['archive','copy','snapshot'],secret:['credential','token','password','variable']
};
const US_SHEET_TERMS={ansible:'playbook configure servers hosts fleet yaml',bash:'shell script linux automation',cicd:'pipeline workflow build test deploy github gitlab jenkins',docker:'container image compose registry',k8s:'kubernetes cluster pods manifests deploy secret configmap service ingress',linux:'system administration packages services files permissions logs',net:'network connectivity dns tcp route http',powershell:'windows script administration pwsh',python:'automation scripting data excel api modules',sql:'query database rows tables',terraform:'infrastructure as code iac cloud provision'};
let usIndex=null,usById=new Map(),usFilter='All',usLastQuery='';
function usNormalize(value){return String(value??'').normalize('NFKD').toLowerCase().replace(/[^a-z0-9+#.-]+/g,' ').trim();}
function usTokens(value){return usNormalize(value).split(/\s+/).filter(token=>token&&!US_STOP.has(token));}
function usDistance(a,b){if(a===b)return 0;if(!a.length)return b.length;if(!b.length)return a.length;let older=null,previous=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){const current=[i];for(let j=1;j<=b.length;j++){current[j]=Math.min(current[j-1]+1,previous[j]+1,previous[j-1]+(a[i-1]===b[j-1]?0:1));if(older&&j>1&&a[i-1]===b[j-2]&&a[i-2]===b[j-1])current[j]=Math.min(current[j],older[j-2]+1);}older=previous;previous=current;}return previous[b.length];}
function usWordScore(query,word){if(query===word)return 34;if(word.startsWith(query))return 25;if(query.length>=3&&query.startsWith(word))return 16;if(query.length>=3&&word.includes(query))return 14;if(query.length<3||word.length<3||query[0]!==word[0])return 0;const limit=Math.max(1,Math.floor(Math.max(query.length,word.length)*.3));if(Math.abs(query.length-word.length)>limit)return 0;const distance=usDistance(query,word);return distance<=limit?Math.max(5,13-distance*3):0;}
function usAdd(list,entry){entry.id=entry.id||entry.kind.toLowerCase()+':'+list.length;entry.sheetName=entry.sheet&&SHEETS[entry.sheet]?.name||entry.sheetName||'';const title=usTokens(entry.title),description=usTokens(entry.description),keywords=usTokens(entry.keywords+' '+(US_SHEET_TERMS[entry.sheet]||'')),weights=new Map();for(const [words,weight] of [[title,4],[keywords,2],[description,1]])for(const word of words)weights.set(word,Math.max(weight,weights.get(word)||0));entry.search={title,description,keywords,words:[...weights],all:usNormalize(entry.title+' '+entry.description+' '+entry.keywords+' '+entry.sheetName+' '+entry.kind)};list.push(entry);return entry;}
function usSheetForSchema(schema){return Object.entries(SHEETS).find(([,sheet])=>sheet===schema.sheet)?.[0]||DK_SCHEMA_PROFILE_SHEETS[schema.id]||schema.id;}
function usBuildIndex(){
 const list=[];
 for(const [sheetId,sheet] of Object.entries(SHEETS)){const guide=DK_GUIDES[sheetId]||[];usAdd(list,{id:'guide:'+sheetId,kind:'Guide',title:sheet.name,description:sheet.subtitle||guide.slice(0,3).join(' '),keywords:sheet.sections.map(section=>section.title).join(' '),sheet:sheetId,action:'guide',payload:{sheet:sheetId},actionLabel:'Browse guide'});sheet.sections.forEach((section,sectionIndex)=>section.cmds.forEach((command,commandIndex)=>usAdd(list,{id:'command:'+sheetId+':'+sectionIndex+':'+commandIndex,kind:'Command',title:command.cmd,description:command.desc,keywords:section.title+' '+(command.platform||''),sheet:sheetId,action:'command',payload:{sheet:sheetId,section:section.id,command:command.cmd},actionLabel:'View command'})));}
 for(const schema of Object.values(DK_SCHEMAS))if(schema.profile){const sheet=usSheetForSchema(schema);usAdd(list,{id:'editor:'+schema.id,kind:'Editor',title:schema.title,description:schema.description,keywords:'create edit file syntax blocks '+schema.assist.catalog.join(' '),sheet,action:'editor',payload:{profile:schema.id,sheet},actionLabel:'Open '+schema.title});if(schema.id!=='python')for(const type of [...new Set(schema.profile.root.accept)]){const def=schema.profile.types[type];if(def)usAdd(list,{id:'block:'+schema.id+':'+type,kind:'Block',title:def.label,description:def.hint,keywords:Object.values(def.fields||{}).map(field=>field.label+' '+(field.hint||'')).join(' '),sheet,action:'block',payload:{profile:schema.id,sheet,type},actionLabel:'Find this block'});}}
 for(const recipe of Object.values(DK_RECIPES))usAdd(list,{id:'recipe:'+recipe.id,kind:'Builder',title:recipe.title,description:recipe.description,keywords:recipe.filename+' '+recipe.check+' '+recipe.parts.map(part=>part.label+' '+part.hint+' '+Object.values(part.fields).map(field=>field.label+' '+field.hint).join(' ')).join(' '),sheet:recipe.sheet,action:'recipe',payload:{id:recipe.id},actionLabel:'Open builder'});
 for(const [key,def] of Object.entries(BUILDERS))if(!def.dkRecipe&&!DK_LEGACY.has(key)){const sheet=key.split('::')[0];usAdd(list,{id:'builder:'+key,kind:'Builder',title:def.name,description:def.description,keywords:[...(def.args||[]).map(x=>x.label+' '+(x.placeholder||'')),...(def.flags||[]).map(x=>x.flag+' '+x.desc)].join(' '),sheet,action:'legacy-builder',payload:{key},actionLabel:'Open builder'});}
 for(const [id,op] of Object.entries(PY_OPS)){const def=pyP.types[id];usAdd(list,{id:'python-step:'+id,kind:'Python step',title:def.label,description:def.hint,keywords:op.group+' '+op.imports.join(' ')+' '+Object.values(def.fields).map(field=>field.label).join(' '),sheet:'python',action:'python-step',payload:{id,title:def.label},actionLabel:'Open Python steps'});}
 for(const [id,pkg] of Object.entries(PY_PACKAGES))usAdd(list,{id:'python-module:'+id,kind:'Python module',title:pkg.title,description:pkg.hint||'Add '+pkg.module+' to a Python script.',keywords:pkg.module+' '+(pkg.pip||'standard library built in'),sheet:'python',action:'python-module',payload:{id,query:pkg.module},actionLabel:'Open Python modules'});
 usAdd(list,{id:'workspace:projects',kind:'Workspace',title:'Multi-file projects',description:'Create, import and edit connected files, folders, tabs, variables, snapshots and ZIP packages.',keywords:'project workspace repository ansible role terraform module container cicd files history diff',action:'projects',payload:{},actionLabel:'Open projects'});usAdd(list,{id:'workspace:recipe-packs',kind:'Workspace',title:'Recipe packs',description:'Import, export and manage safe JSON-only guided recipe extensions.',keywords:'recipe pack extension json template offline import custom builder',action:'recipe-packs',payload:{},actionLabel:'Manage packs'});
 usAdd(list,{id:'workspace:backup',kind:'Workspace',title:'Backup and move DevKit',description:'Export or restore browser notes, favorites, drafts, projects and preferences.',keywords:'portable transfer migrate restore browser data',action:'backup',payload:{},actionLabel:'Open backup'});
 usIndex=list;usById=new Map(list.map(entry=>[entry.id,entry]));return list;
}
function usScore(entry,query,cache=new Map()){const context=typeof query==='string'?{normalized:usNormalize(query),tokens:usTokens(query)}:query;if(!context.tokens.length)return 0;let score=entry.search.all.includes(context.normalized)?55:0,misses=0;for(const token of context.tokens){const alternatives=[token,...(US_SYNONYMS[token]||[])];let best=0;for(const candidate of alternatives)for(const [word,weight] of entry.search.words){const key=candidate+'\0'+word;let value=cache.get(key);if(value===undefined){value=usWordScore(candidate,word);cache.set(key,value);}best=Math.max(best,value*weight);}if(best)score+=best;else misses++;}if(misses===context.tokens.length||misses>Math.floor(context.tokens.length/2))return 0;if(!misses)score+=Math.min(context.tokens.length,3)*20;return score-misses*18+(entry.kind==='Editor'?5:entry.kind==='Builder'?3:0);}
function usSearch(query,limit=60){const context={normalized:usNormalize(query),tokens:usTokens(query)},cache=new Map(),scored=(usIndex||usBuildIndex()).map(entry=>({entry,score:usScore(entry,context,cache)})).filter(item=>item.score>0).sort((a,b)=>b.score-a.score||a.entry.title.localeCompare(b.entry.title));return scored.slice(0,limit);}
function usNavigate(sheet,section=null){state.activeSheet=sheet;state.activeSection=section;state.searchQuery='';const search=document.getElementById('search');if(search)search.value='';state.expandedSheets.add(sheet);save('expandedSheets');save('activeSheet');save('activeSection');renderSidebar();renderMain();document.getElementById('main').scrollTop=0;toggleMobileNav(false);}
function usOpenBlock(entry){ddOpen(entry.payload.profile,entry.payload.sheet);requestAnimationFrame(()=>{const select=document.querySelector('#dk-root .dd-lane[data-parent=""][data-slot="root"] > .dd-add select');if(!select||![...select.options].some(option=>option.value===entry.payload.type))return;select.value=entry.payload.type;select.dispatchEvent(new Event('change'));const add=select.parentElement.querySelector('button');add.classList.add('us-target');add.scrollIntoView({block:'center'});add.focus();});}
function usActivate(id){const entry=usById.get(id);if(!entry)return;const p=entry.payload;switch(entry.action){case'guide':usNavigate(p.sheet);break;case'command':usNavigate(p.sheet,p.section);requestAnimationFrame(()=>{const row=[...document.querySelectorAll('.cmd-item')].find(item=>item.dataset.id===cmdId(p.sheet,p.command));if(row){row.classList.add('us-target');row.tabIndex=-1;row.scrollIntoView({block:'center'});row.focus();}});break;case'editor':ddOpen(p.profile,p.sheet);break;case'block':usOpenBlock(entry);break;case'recipe':dkOpenRecipe(p.id);break;case'legacy-builder':openBuilder(p.key);break;case'python-step':pySearch=p.title;pyGroup='All';ddOpen('python','python');break;case'python-module':pySearch='';pyModuleSearch=p.query;ddOpen('python','python');break;case'projects':pwShowProject(null);break;case'recipe-packs':rpOpen();break;case'backup':dkTransfer();break;}}
function usCopyCommand(entry,button){copyCmd(button,entry.payload.command);}
function usText(host,text,query){const terms=usTokens(query).filter(term=>term.length>1).sort((a,b)=>b.length-a.length);if(!terms.length){host.textContent=text;return;}const regex=new RegExp('('+terms.map(term=>term.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')).join('|')+')','ig');for(const part of String(text).split(regex)){const node=terms.some(term=>part.toLowerCase()===term)?dkEl('mark','',part):document.createTextNode(part);host.append(node);}}
function usSetQuery(query){const input=document.getElementById('search');input.value=query;state.searchQuery=query;input.focus();renderMain();}
function usRenderSearch(query){
 const main=document.getElementById('main'),changed=query!==usLastQuery;if(changed){usLastQuery=query;usFilter='All';}const ranked=usSearch(query),counts=new Map();for(const {entry} of ranked)counts.set(entry.kind,(counts.get(entry.kind)||0)+1);const visible=ranked.filter(({entry})=>usFilter==='All'||entry.kind===usFilter),shown=visible.slice(0,50);main.replaceChildren();
 const header=dkEl('div','page-header us-header'),icon=dkEl('div','page-icon','⌕'),title=dkEl('div','page-title-block');icon.style.cssText='background:#4f8ef720;color:var(--accent);border:1px solid var(--accent-dim)';title.append(dkEl('div','page-title','Search DevKit'),dkEl('div','page-subtitle','Commands, builders, editors, blocks, Python tooling and guides — ranked by what you mean.'));const meta=dkEl('div','page-meta',ranked.length===60?'Top 60 matches':ranked.length+' result'+(ranked.length===1?'':'s'));meta.id='search-result-count';meta.setAttribute('role','status');header.append(icon,title,meta);main.append(header);
 const examples=dkEl('div','us-examples');examples.append(dkEl('span','','Try'));for(const text of ['restart a Linux service','build a GitHub pipeline','read an Excel file with Python','create Terraform infrastructure'])examples.append(dkBtn(text,()=>usSetQuery(text),'us-query'));main.append(examples);
 if(!ranked.length){const empty=dkEl('div','empty');empty.append(dkEl('div','empty-icon','⌕'),dkEl('p','','No useful match yet. Try the task, platform, file type, or tool name in different words.'));main.append(empty);updateStatusCount(0,'Search','result');return;}
 const filters=dkEl('div','us-filters');filters.setAttribute('role','group');filters.setAttribute('aria-label','Search result type');for(const [kind,count] of [['All',ranked.length],...counts]){const button=dkBtn(kind+' '+count,()=>{usFilter=kind;usRenderSearch(query);},'us-filter');button.setAttribute('aria-pressed',String(usFilter===kind));filters.append(button);}main.append(filters);
 const list=dkEl('section','us-results');list.setAttribute('aria-label','Ranked DevKit search results');for(const {entry} of shown){const card=dkEl('article','us-result');card.dataset.searchId=entry.id;const head=dkEl('div','us-result-head'),heading=dkEl('h2');usText(heading,entry.title,query);head.append(heading,dkEl('span','us-kind',entry.kind));card.append(head);const context=dkEl('div','us-context',(entry.sheetName?entry.sheetName+' · ':'')+entry.actionLabel);card.append(context);const description=dkEl('p','us-description');usText(description,entry.description,query);card.append(description);const actions=dkEl('div','us-actions'),open=dkBtn(entry.actionLabel,()=>usActivate(entry.id),'us-open');open.dataset.usResult=entry.id;actions.append(open);if(entry.kind==='Command'){actions.append(dkBtn('Copy',event=>usCopyCommand(entry,event.currentTarget),'us-secondary'));const builderKey=entry.payload.sheet+'::'+entry.payload.command;if(BUILDERS[builderKey])actions.append(dkBtn('Customize',()=>dkOpenExample(entry.payload.sheet,SHEETS[entry.payload.sheet].sections.flatMap(section=>section.cmds).find(command=>command.cmd===entry.payload.command)),'us-secondary'));}card.append(actions);list.append(card);}main.append(list);if(visible.length>shown.length)main.append(dkEl('p','us-limit','Showing the first '+shown.length+' of '+visible.length+' ranked results. Refine the query for a shorter list.'));updateStatusCount(ranked.length,'Search','result');
}
renderSearchResults=function(q){usRenderSearch(q);};
const usInput=document.getElementById('search');usInput.placeholder='Describe what you need: restart a service, build a pipeline…';usInput.setAttribute('aria-label','Search all DevKit tools by command or intent');usInput.setAttribute('aria-controls','main');usInput.addEventListener('keydown',event=>{if(event.key==='ArrowDown'){const first=document.querySelector('.us-open');if(first){event.preventDefault();first.focus();}}else if(event.key==='Enter'){const first=document.querySelector('.us-open');if(first){event.preventDefault();first.click();}}});
usBuildIndex();
